### ISSUE TITLE
Online help (F1) doesn't properly work if default browser is not IE/Edge

### ISSUE THREAD

**Issue by randrey** [OpenLiveWriter/OpenLiveWriter#102]
Chrome and Firefox attempt to save a file instead of redirecting to the help page. 

![olwhelp](https://cloud.githubusercontent.com/assets/798485/11761564/d3ff5316-a07c-11e5-8016-70f97e3b3608.png)

Address bar shows `openlivewriter.org/WriterRedirect/WriterHelpV3?Version=0.0&Build=5.0&Market=en-US`

Same when clicking 'Add Plug-in' on the Insert panel. The url is `openlivewriter.org/WriterRedirect/WriterDownloadPluginsURL?Version=0.0&Build=5.0&Market=en-US`.

**Comment by martinwoodward** [comment]
Hmm, weird. I wonder if I did something wrong with the redirect in GitHub pages. Do you mind posting the contents of the file?

**Comment by randrey** [comment]
Here is the content:
```
<!DOCTYPE html>
<meta charset=utf-8>
<title>Redirecting...</title>
<link rel=canonical href="http://openlivewriter.org/getting-started/index.html">
<meta http-equiv=refresh content="0; url=http://openlivewriter.org/getting-started/index.html">
<h1>Redirecting...</h1>
<a href="http://openlivewriter.org/getting-started/index.html">Click here if you are not redirected.</a>
<script>location='http://openlivewriter.org/getting-started/index.html'</script>
```
Also attaching... [WriterHelpV3.zip](https://github.com/OpenLiveWriter/OpenLiveWriter/files/60119/WriterHelpV3.zip)

**Comment by martinwoodward** [comment]
Hmm, looks like the server is returning a mime type of application/octet-stream which would cause this behaviour. @shiftkey - any idea what I'm doing wrong?  I was trying to do a redirect using GH Pages.  The Jekyll Front Matter is below:

```
---
layout: default
title: "Getting Started"
redirect_from:
  - /WriterRedirect/WriterHelpV3
  - /WriterRedirect/LearnMore
---
```

Martin.

**Comment by shiftkey** [comment]
I think this is something related to the redirect setup. I'm not entirely sure how the docs are strutured, but the `jekyll-redirect-from` gem has two rules:

- Redirects including a trailing slash will generate a corresponding subdirectory containing an `index.html`
- Redirects without a trailing slash will generate a corresponding filename without an extension, and without a subdirectory.

Source: https://github.com/jekyll/jekyll-redirect-from#usage

I *think* (full disclosure: I haven't tested this) - you should add the trailing slash to the redirect rules - both here and in the code for the F1 shortcut - so that Jekyll generates the corresponding `.html` file and the server knows to return the right `Content-Type` value to prevent the download action.

**Comment by martinwoodward** [comment]
I have /getting-started/index.html and tried the front matter of:

```
---
layout: default
title: "Getting Started"
redirect_from:
  - /WriterRedirect/WriterHelpV3/
  - /WriterRedirect/LearnMore/
---
```
And that didn't seem to work either - is that what you meant @shiftkey?

**Comment by shiftkey** [comment]
@martinwoodward that's what I was had in mind. Back to the drawing board I guess...

Are the docs sources somewhere I could clone them down and poke around?

**Comment by martinwoodward** [comment]
Can folks check if this is resolved now?  I think it might have just been a caching issue and that @shiftkey was right all along (as usual ;-) )

Works on my machine now anyway...

**Comment by shiftkey** [comment]
@martinwoodward working great here. Only thing I noticed from browsing Fiddler to verify is that some of the resources on the page are 404ing (this was in Firefox):

<img width="505" alt="screen shot 2015-12-15 at 6 44 00 am" src="https://cloud.githubusercontent.com/assets/359239/11792703/571b7992-a2f7-11e5-9999-1e34692e381b.png">

Seems to be some path shenanigans to look at:

```
<img src="\images\openlivewriter-purpleheader.png" alt="Open Live Writer"/>
...
<img title="" style="display: inline" alt="Enter title" src=".\title.png" width="465" height="316" />
...
<img title="story" style="display: inline" alt="An example blog post" src=".\story.png" width="465" height="308" />
```

**Comment by randrey** [comment]
Same here. Redirection works. Images don't load.

**Comment by martinwoodward** [comment]
Ok - think I've really fixed it this time sorry. Can folks confirm?

**Comment by randrey** [comment]
Confirming, everything is in place. I think this can be closed.

**Comment by shiftkey** [comment]
@martinwoodward :+1: on those fixes to the images
