### ISSUE TITLE
Errors when using invalid url to insert an image

### ISSUE THREAD

**Issue by randrey** [OpenLiveWriter/OpenLiveWriter#103]
1. Go to Insert -> Picture -> From the web
2. Type in an invalid url and cilck Insert. It will ask if you want to continue. Say Yes.
![picturefromtheweb](https://cloud.githubusercontent.com/assets/798485/11761822/75e106bc-a086-11e5-826c-564192a3fdba.png)

It will add a placeholder image and show an error
![uriexception](https://cloud.githubusercontent.com/assets/798485/11761823/7fd034f4-a086-11e5-805b-9e58701e6746.png)

Adding a hyperlink to the placeholder image throws a NullRefException.

**Comment by tomlane** [comment]
[Relevant source](https://github.com/OpenLiveWriter/OpenLiveWriter/blob/fb1cc45f48462981a5d3a44e360fbd6d8b289bf9/src/managed/OpenLiveWriter.PostEditor/PostHtmlEditing/ImageEditing/ImageEditingPropertyHandler.cs#L97)

What should be done here? A more friendly error message?

**Comment by hashhar** [comment]
I second this. A good way to handle this would be to send a request to the link and see if it was reachable or not.

**Comment by hashhar** [comment]
On second thought, why do we allow invalid links in the first place?

**Comment by pekiZG** [comment]
@hashhar make a fork, clone it localy and then make a pull req.
We should put it into wiki :)

**Comment by hashhar** [comment]
Thanks. One clarification I need is that whether we need to disallow invalid links or simply provide a better help message.

**Comment by pekiZG** [comment]
@hashhar I was thinking two things

1. Don't trust user input. If you can not correct what user entered inform him that there is something wrong.
2. If you know how good "payload" looks like accept it; everything else gets rejected with appropriate message to the user.

/me thinks option number two is better

**Comment by hashhar** [comment]
I'll try and get a pull ready by tomorrow. Excited.

**Comment by hashhar** [comment]
I got upto [this](https://github.com/hashhar/OpenLiveWriter/blob/issue-103/src/managed/OpenLiveWriter.PostEditor/PostHtmlEditing/ImageEditing/ImageEditingPropertyHandler.cs#L99-L107)

How can I display a nice error message that says "We couldn't find an image at the link you just entered." and two buttons, one for "Edit Link" which should take the user back to the form where they enter the link and the other for "Cancel" which should stop the image insertion and get them back to the editorContext.

And where is the dialog in the image above being called? I spent a lot of time trying to read through the stack traces by inserting breakpoints. I am not used to string resources (I could've just `Ctrl + F`ed the relevant words but they led me to the resource files.

I was able to use `DisplayMessage.Show()` but I couldn't figure out a way to change the dialog's contents other than the predefined ones set by the `MessageId` enum.

**Comment by pekiZG** [comment]
@hashhar, think I read somewhere here that enum is being generated from somewhere.
Guessing some .resx file or something similar.

Look through issues dealing with localization. Ill link it here if I find it again.

**Comment by hashhar** [comment]
I found the resx though. So I have to add the relevant xml to the resx and then call the `DisplayMessage.Show()` with the generated `MessageId`

**Comment by pekiZG** [comment]
Great :)
