### ISSUE TITLE
FAQs and WIKI mention helping but need more details.

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter#109]
There are several of us who want to help the effort but are not seasoned developers.  The FAQ and WIKI need to have more details on how to help.  I've seen other open source projects that had this process more fully documented.

For example, there are people who would like to test, but we need more direction.  Where do we find things to test? (I assume commits, but exactly which ones).  What process should we go through to test?

If we want to help out with coding an issue, what exactly do we need to do?

**Comment by kathweaver** [comment]
For example: In FAQs

Q: I found a bug, what do I do?

A: Please submit an issue via GitHub: https://github.com/OpenLiveWriter/OpenLiveWriter/issues/new


Change answer to:

A: Contribute to notifying the developers.

<ul>
<li>Search issues at https://github.com/OpenLiveWriter/OpenLiveWriter/issues and if you find a similar issue already submitted at to it by commenting appropriately, especially if you have something to add.
<li>If you do not find an appropriate issue, submit a new issue at  https://github.com/OpenLiveWriter/OpenLiveWriter/issues/new
</li>
</ul>

**Comment by pekiZG** [comment]
@kathweaver there is a discussion about making wiki and FAQ a repository.
Check it out https://github.com/OpenLiveWriter/OpenLiveWriter/issues/110

**Comment by RobDolin** [comment]
Thanks for the suggestion @kathweaver.  Thanks to issue #110 and PR #112, the FAQ is now faq.md in the repository so you (and all members of the community) can submit pull requests against the FAQ.

**Comment by kathweaver** [comment]
Great, I have proposed the above change.  We still need more directions on pulling builds -- something I'm not sure how to do yet.

**Comment by kathweaver** [comment]
I pulled the latest master and ran into the building issues.

Running .\build gave me this error message:
Added package 'squirrel.windows.1.2.1' to folder 'D:\Users\Kathleen\Downloads\OpenLiveWriter-master\OpenLiveWriter-master\src\managed\packages'
%OLW_CONFIG% not set, will default to 'Debug'
CSC : error CS2001: Source file 'D:\Users\Kathleen\Downloads\OpenLiveWriter-mas
ter\OpenLiveWriter-master\src\managed\MarketXmlGenerator\..\GlobalAssemblyVersi
onInfo.cs' could not be found. [D:\Users\Kathleen\Downloads\OpenLiveWriter-mast
er\OpenLiveWriter-master\src\managed\MarketXmlGenerator\MarketXmlGenerator.cspr
oj]
  OpenLiveWriter.Interop.Mshtml -> D:\Users\Kathleen\Downloads\OpenLiveWriter-m
  aster\OpenLiveWriter-master\src\managed\bin\Debug\i386\Writer\OpenLiveWriter.
  Interop.Mshtml.dll

However, building it in Visual Studio was successful, but then I couldn't run it:

"A project with an Output Type of Class Library cannot be started directly."

I could run it though in the command prompt with .\run

I was able to create a test post, but got:

ERROR: ProgID missing for extension: .wpost

**Comment by gep13** [comment]
>@kathweaver said...
However, building it in Visual Studio was successful, but then I couldn't run it:
"A project with an Output Type of Class Library cannot be started directly."

I had the same issue originally as well.  To correct this, go to solution explorer, right click on the `OpenLiveWriter` project, and select `Set as startup project`.  Then try running from within Visual Studio, and that should work for you.

![image](https://cloud.githubusercontent.com/assets/1271146/11766511/03464dee-a183-11e5-83f6-d20d94d13d27.png)


Hope that helps!

**Comment by kathweaver** [comment]
@gep13 Resolved my run issues.

This morning without making any changes to my computer my build issues were resolved.

**Comment by kathweaver** [comment]
So my last question is what do I test?  Does the current master have all the commits accepted so far?  Or is it the code that has been released already?

**Comment by timheuer** [comment]
@kathweaver Current master has all merged pull requests the team has accepted so far.  There are a bunch still not merged.  Basically if you look at the "Pull Requests" tab here in Github you will see the ones that haven't been merged and thus any issue they are attached to still exist in 'master' until that merge is completed after the reviews.

We had a nightly build setup going, I'm not sure if we published that well yet (we should) so that we could make it easier for people to just be on the nightly build and test.  @martinwoodward @willduff do we have nightly's working properly?

**Comment by kathweaver** [comment]
@martinwoodward  @willduff last comment asked if nightly build is working properly.  If so, how do we get to that?

**Comment by martinwoodward** [comment]
Sadly there was a bug with the Beta update channel in the 0.5.0.0 release (#131) and we'll have to wait until the next release to get it fixed so at the moment switching to the beta channel is broke in quite a few ways and you cannot switch to getting updates from it - you have to build from source instead.

Once the next release is in you will be able to switch to the Beta channel by adding/editing the following DWORD registry key and setting it to 1.

HKEY_CURRENT_USER\SOFTWARE\OpenLiveWriter\Updates\CheckForBetaUpdates

Note that while we often refer to it as "Nightly" and it has Nightly in the URL, it's actually a CI build - so will be freshly updated with every merged pull request by the server so definitely only for the brave!  OLW checks for updates around 10 seconds after starting up.  If it finds an update it downloads it in the background and then updates the version next time OLW is started. At the moment we have no UI to force a check for updates or tell the user when an update has happened.  (Be good to have some functionality in that area at some point in the future)

**Comment by kathweaver** [comment]
Closing since all the questions seem to be addressed.
