### ISSUE TITLE
Suggestion: Move FAQ from Wiki page to core repo so it can accept PRs

### ISSUE THREAD

**Issue by RobDolinMS** [OpenLiveWriter/OpenLiveWriter#110]
The FAQ is currently a wiki page: https://github.com/OpenLiveWriter/OpenLiveWriter/wiki/Frequently-Asked-Questions-(FAQ)  We could move this into the repo as a .md file so it's still relatively easy to read and edit, but so it could also accept pull requests.

**Comment by RobDolinMS** [comment]
Tagging @martinwoodward @shanselman @ScottIsAFool for perspective.

**Comment by martinwoodward** [comment]
I've been thinking the same - we should make this a folder called "Documentation". Note capital D so that it shows at the top of the page in GitHub's sort order.

**Comment by ScottIsAFool** [comment]
The wiki pages can be their own repo within the main repo, no need to move it out. Please see this https://help.github.com/articles/adding-and-editing-wiki-pages-locally/

**Comment by martinwoodward** [comment]
Sadly you can't do a PR though (or you didn't used to be able to anyway)

**Comment by pekiZG** [comment]
I just tried it and I get this screen
![screen shot 2015-12-12 at 19 44 50](https://cloud.githubusercontent.com/assets/1389274/11763392/e348e256-a108-11e5-9a14-278b2520efae.png)

**Comment by ScottIsAFool** [comment]
@pekizg Have you forked it?

**Comment by pekiZG** [comment]
I pushed clone to desktop;
Made some changes;
Committed changes locally;
Pressed sync and that's where it "breaks"

**Comment by RobDolin** [comment]
Please assign this to @RobDolin.  I can do this when back on a full-size PC.  Thanks.

Sent from my Windows Phone
________________________________

**Comment by gep13** [comment]
>@martinwoodward said...
Sadly you can't do a PR though (or you didn't used to be able to anyway)

It can be done, but it isn't pretty.  We do something for the Chocolatey Wiki currently, but I wouldn't recommend it.  Instead, before you get too far down the road, you might want to think about using [ReadTheDocs](https://readthedocs.org/dashboard/).  That is what we are away to move the Chocolatey Documentation to.  The documentation ends up residing directly within your source code, in a docs folder, and is therefore, much easier to maintain, and accept pull requests to.

**Comment by ScottIsAFool** [comment]
@pekizg it's the same as any other change you want to make, you need to fork it first, make tour changes, then submit a pull request.

**Comment by gep13** [comment]
>@ScottIsAFool said....
@pekizg it's the same as any other change you want to make, you need to fork it first, make tour changes, then submit a pull request.

That won't work though Scott, there is no UI in GitHub to accept PR's to the wiki.  It would all have to be done manually, unless you go the route that we have with Chocolatey, and push the entire wiki repo to a separate repo, which you can find here https://github.com/chocolatey/choco-wiki and then manually push to an upstream remote which is the actual wiki.  This becoming messy when you have people making changes directly, and also in the fork.  Having used this approach, I wouldn't recommend it.

**Comment by ScottIsAFool** [comment]
I stand corrected then :)

**Comment by RobDolin** [comment]
Thanks all.  (And thanks to my spouse who is driving so I can make these edits)
#112 has been merged.

**Comment by timheuer** [comment]
+1 to ReadTheDocs -- totally forgot about that
