### ISSUE TITLE
Password fail while running setup

### ISSUE THREAD

**Issue by Allison8713** [OpenLiveWriter/OpenLiveWriter#111]
I can't get through the setup!  It will not accept my userid and password. I changed my password, so it's current.  What am I supposed to do with this?

**Comment by pekiZG** [comment]
@Allison8713 could you please describe what you were trying to do?

**Comment by ScottIsAFool** [comment]
I this a blogger blog you're using?

**Comment by HiddenJewel** [comment]
This is occurring to me also while trying to connect to Blogger during initial setup of Open Live Writer.

**Comment by HiddenJewel** [comment]
I see from another thread that you have been working on this issue. Has there been any resolution?

**Comment by gabrielweyer** [comment]
Duplicate of #5 it won't work until someone adds Blogger support using OAuth 2.

**Comment by HiddenJewel** [comment]
Is that something that the developers have to do?

**Comment by gabrielweyer** [comment]
It's something a developer will have to do, the work is currently being tracked here #101

**Comment by HiddenJewel** [comment]
Thank you for the link to #101.

**Comment by timheuer** [comment]
Closing as dupe to #5
