### ISSUE TITLE
Can't Update Wiki - Building, Testing and Debugging

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter#118]
I would like to add the following to this Wiki page, but apparently don't have the appropriate privileges:

## Solving Problems

When attempting to run the project and you get the error message: "A project with an Output Type of Class Library cannot be started directly" 

Go to solution explorer, right click on the OpenLiveWriter project, and select "Set as startup project".

**Comment by ScottIsAFool** [comment]
I think the wiki may be moving, that certainly seems to be the discussion had on Gitter.

**Comment by RobDolin** [comment]
I moved the FAQ page of the wiki.

The Building, Testing, and Debugging page of the wiki should not me impacted; but I think edits or editors of the wiki may have been limited.

/CC @MartinWoodward

Sent from my Windows Phone
________________________________

**Comment by kathweaver** [comment]
@martinwoodward has this been fixed?

**Comment by martinwoodward** [comment]
Thanks @kathweaver - for the record it is here now  https://github.com/OpenLiveWriter/OpenLiveWriter/blob/master/faq.md

**Comment by kathweaver** [comment]
Yes, but I wanted to update the Building, Testing and Debugging Page, and couldn't.
