### ISSUE TITLE
OLW Does Not Work For Me

### ISSUE THREAD

**Issue by cosmo398** [OpenLiveWriter/OpenLiveWriter#120]
I cannot get OLW to work for me when I try to add my blog.  I get an error message saying it cannot find the server.  I have no clue what I need to do.

Fran

**Comment by timheuer** [comment]
Is your blog on Blogger/Blogspot?

**Comment by cosmo398** [comment]
It’s on Blogspot.  I forgot to mention I have the same problem with Windows Live Writer.

 

Fran 

 

My Blog

 <http://scallopsandswirls.blogspot.com/> http://scallopsandswirls.blogspot.com/

**Comment by ScottIsAFool** [comment]
Thanks for reporting this, we are aware of it and a fix is being worked on as we speak.

**Comment by timheuer** [comment]
Closing M as dupe of #5 (fix is in pull request #101 being reviewed)

**Comment by cosmo398** [comment]
That's good news. How will I know that all is fixed?

   Fran
  (Sent from my iPAD)

**Comment by vilianfa** [comment]
I have the same problem. I can´t acess my blog/blogger through OLW

**Comment by RobDolin** [comment]
Thanks for commenting @vilianfa.  Blogger blogs not working with Open Live Writer (and Windows Live Writer) is a known issue and the volunteer team is working on a fix for Open Live Writer hopefully to release this week.

Sent from my Windows Phone
________________________________
