### ISSUE TITLE
Update Community Server Provider

### ISSUE THREAD

**Issue by rhysgodfrey** [OpenLiveWriter/OpenLiveWriter#122]
"Community Server" appears as an option in the Blog Providers list.

"Community Server" has been re-branded under different names since version 5.x (released around 2009/10), primarily as "Telligent Community" (or some form of this), for a brief period it was known as "Zimbra Social (version 8.x)", and is now back to Telligent.

In version 8.x the URLs for the metablog API were updated, this, along with the old name, make the process of setting up a Telligent blog confusing.

Thinking that "Community Server" should be updated to the more widely used "Telligent Community", and an extra provider added with the new URL structure for version 8.x+. How does that sound?

I've given the changes a go in this branch: https://github.com/rhysgodfrey/OpenLiveWriter/tree/update-telligent-provider, but would be good to get some guidance on if the changes are wanted and acceptable before opening a PR :)

**Comment by ScottIsAFool** [comment]
I don't see why this shouldn't be submitted as a PR.

**Comment by martinwoodward** [comment]
+1 - send a PR in for it @rhysgodfrey - I'm not sure that all the market XML files are needed but the folks that would know can comment on the PR when they do.  When you submit it be sure to add in the comment that "this fixes #122"

**Comment by rhysgodfrey** [comment]
Thanks Both! PR Submitted :)
