### ISSUE TITLE
Add support for BlogEngine.NET

### ISSUE THREAD

**Issue by RobDolinMS** [OpenLiveWriter/OpenLiveWriter#135]
This is open source blog hosting software.  See: http://www.dotnetblogengine.net/

**Comment by ScottIsAFool** [comment]
Weird, they must have changed something then, because blogengine.net always used to work just fine (I ran a couple of blogs on it).

**Comment by crpietschmann** [comment]
I have successfully authored and posted a blog post using Open Live Writer to one of my blogs running BlogEngine.NET 2.8.

What version of BlogEngine.NET are you having difficulty with?

**Comment by ScottIsAFool** [comment]
I wonder if @tleclaire can comment on what version they are running?

**Comment by tleclaire** [comment]
Ok,
I tried at home and it actually works!
Looks like an issue with the proxy at that network.

Sorry for the hassle...

**Comment by ScottIsAFool** [comment]
That's ok. When you have got into Live Writer, be sure to go to the options and you can configure your proxy in there.

**Comment by RobDolinMS** [comment]
Thanks to @tleclaire and @crpietschmann for helping to confirm Open Live Writer v0.5 works with Blog Engine .NET (http://www.dotnetblogengine.net/)

**Comment by jrblack10** [comment]
Uh... new to Open Live Writer, but used to use MS Live Writer and loved it.  But I can't get either to work on my BlogEngine 3.1.0.1, while at work (no proxy) and while at home.  what can I check?

**Comment by ScottIsAFool** [comment]
@jrblack10 are you able to provide the domain for your blog so we can check it out?

**Comment by jrblack10** [comment]
Yeah, sure.  Jim.BlacksWeb.com  Haven'd  done much with it in quite some time, but with job change, I would like to.  I am working on upgrading it to the latest 3.3

**Comment by jrblack10** [comment]
It errors out on the step... Verifying Blog Publishing Interface...
![image](https://cloud.githubusercontent.com/assets/23705016/20572621/328ed9ce-b17a-11e6-9fd4-11f2bc533ae7.png)

**Comment by jrblack10** [comment]
OK... so maybe the problem was all in my understanding of how OLW would connect (based on my memory in the past).  I thought just choosing OTHER, providing my address, id and password would work... but I forced the s in https and caused a different error and a new screen where I can manually enter in the information needed to connect to my blog. I have it detailed here on my [blog](http://jim.blacksweb.com/post/2016/11/25/Open-Live-Writer).

**Comment by ScottIsAFool** [comment]
@jrblack10 hmmm, bit strange that it needed the https to get past that first screen, thanks for letting us know.

**Comment by jrblack10** [comment]
I would not have tried, but the initial error message posted above, listed the url with HTTPS, even though I was not entering it that way... so I tried it.
