### ISSUE TITLE
Problema de Autentificacion

### ISSUE THREAD

**Issue by VGG1955** [OpenLiveWriter/OpenLiveWriter#144]
El nuevo Open Live Write para bloger no me reconoce mis datos, (email y contraseña) ¿Cual es el problema, puesto que el viejo windows live wite tambien ha dejado de funcionar

Victor Guerra

**Comment by ScottIsAFool** [comment]
Thanks for reporting this, we are aware of the issue and is being tracked with #5, but a fix is in the works.

**Comment by ScottIsAFool** [comment]
Dupe of #63

**Comment by VGG1955** [comment]
Gracias, y el tema es acuciante, en tanto que uno y oiro sistema no funcionan y estamos desasistidos Gracias
