### ISSUE TITLE
Still can't update the Wiki

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter#150]
It was great that the FAQ was moved so we can update it, but we still can't update the rest of the pages in the Wiki.

I'd like to expand on building and testing, especially now that we have important stuff to test.

**Comment by martinwoodward** [comment]
Me or @RobDolin should do this soon sorry.

**Comment by kathweaver** [comment]
I'll leave it open until it happens.

**Comment by kathweaver** [comment]
I think everything has been moved now.
