### ISSUE TITLE
GoogleApiException

### ISSUE THREAD

**Issue by banders03** [OpenLiveWriter/OpenLiveWriter#153]
I just did a test page after setting OLW up and got this error message: 

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by martinwoodward** [comment]
Thanks for the report. 
 - Are you still getting this error with the latest build?  
 - Did you delete your Blogger account and re-add it?
 - Do you mind pointing us at the blog that you where trying to post to?

**Comment by banders03** [comment]
Yes, it was with the latest build
No, I did not. I will do that now
http://barspaperpursuits.blogspot.com

Thanks to all of you for working on OLW!

**Comment by banders03** [comment]
When I try to remove my account from OLW, the Remove option is not live--I have my account highlighted but the Remove button is grayed out.

Thanks!

**Comment by ScottIsAFool** [comment]
@banders03 is it still inactive after restarting OLW? I'm seeing it active right now on my install.

**Comment by banders03** [comment]
@ScottIsAFool The post that I got that error with was one that was in Local Draft mode and I kept trying to publish it and kept getting that error. I've since been able to publish three tests, one from Local Draft mode, so I'm assuming there was something wrong with that particular post?

Thank you!

**Comment by ScottIsAFool** [comment]
@banders03 Was it a draft that had been made prior to re-adding your updated Blogger account?

**Comment by banders03** [comment]
@ScottIsAFool Quite possibly, I really can't remember :(

**Comment by banders03** [comment]
@ScottIsAFool  I just wrote up a long post and when I published got this error: Can't Publish Files The remote server returned an error: (403) Forbidden.

I saved my post, closed OLW, reopened and tried again with the same results.

I've gotten that error with WLW before but closing and reopening always resolved it. Not this time.

**Comment by ScottIsAFool** [comment]
@banders03 we're taking a look at that error at the moment, in the meantime, people seem to be having some luck with this workaround http://www.madrasnow.com/2015/12/solved-open-live-writer-login-issue.html

**Comment by banders03** [comment]
Worked like a charm!! Thank you, thank you, thank you!! I hope you guys know how very appreciated you and your work are.

**Comment by Dinchy87** [comment]
tried the above suggestion from @ScottIsAFool but does not seem to work for me. I also get the same error like described above. Prior to this i published 2-3 Posts to draft but now something does not work.

**Comment by banders03** [comment]
@Dinchy87 I had to drill down one more layer--it wouldn't let me add my password on that screen.

Here's what I did: Options > Accounts > My Blog > Edit >Update Account Information and this is where I entered my password and told it to remember. My post got scheduled and looks good in Preview. Also my password is still there. I hope this helps!

**Comment by Dinchy87** [comment]
@branders03 i did the same but then it downloaded the theme again and like a new Setup, but afterwards it didnt work to poast anything..

**Comment by banders03** [comment]
@Dinchy87 Yes, mine did that, too, like a new set up but seems to have worked for me. I won't know for sure, I guess, until it posts as scheduled, but it's looking good in preview. Sorry I can't help more. I'd start a new issue if I were you and maybe one of the pros will respond.

**Comment by sboyd000** [comment]
Anybody have any suggestion for a 404 error that I get when posting directly from Live Writer or to Draft in google?  Can't post anything anywhere although everything was working fine yesterday and I did nothing but turn the machine off and then back on overnight.  Using Live Writer version 0.6 and windows 7.   Here's the error I've been getting all day long between my unsuccessful efforts to research a solution on line.

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()
