### ISSUE TITLE
I Can't Use "Split Post" and "Set Categories" Doesn't Appear

### ISSUE THREAD

**Issue by nelsonkodama** [OpenLiveWriter/OpenLiveWriter#154]
Hi, guys,

You all are doing a great job!!

I Can't Use "Split Post" and "Set Categories" Doesn't Appear:

![01](https://cloud.githubusercontent.com/assets/16329205/11858686/c1525638-a44a-11e5-82cc-d6f0ce4075f7.jpg)

Thankyou so much!!

**Comment by martinwoodward** [comment]
Is this against Blogger / Blogspot?

**Comment by nelsonkodama** [comment]
Yes, I use Blogger.

**Comment by martinwoodward** [comment]
Thanks. Issue #157 is tracking support for labels/categories/tags etc. PR #163 is tracking the functionality to support split post.  Closing this as a duplicate for now, if you want to subscribe to notifications on the other two issues you should see when they get merged in.
