### ISSUE TITLE
Support for Labels/Tags/Categories in Blogger

### ISSUE THREAD

**Issue by n0tb0dy** [OpenLiveWriter/OpenLiveWriter#157]
H!
Thank you very much for your excellent work! But was very upset that it is not possible to add tags. You plan to fix it?

**Comment by SteveP-UK** [comment]
I miss the 'tag' function too. Is it possible to bring them back or has Blogger dropped them as a feature?

**Comment by ScottIsAFool** [comment]
@n0tb0dy Unfortunately, it looks like Blogger has dropped them from the most up to date API.

**Comment by martinwoodward** [comment]
actually, I think these may be called labels in the new Blogger API (https://developers.google.com/blogger/docs/3.0/reference/posts#resource). 

I'm not finding a way to get the list of labels for a current blog though - but the Blogger online editor can find them.

Let's keep this open for now and see if we can figure out a way of making it happen.

**Comment by ScottIsAFool** [comment]
@martinwoodward my bad, I thought Will said they weren't in the new API :)

**Comment by SteveP-UK** [comment]
Yes, I'd like to have the 'tag' feature return too.

Regards

Steve

**Comment by SteveP-UK** [comment]
Sorry,  I meant 'labels'  not 'tags'

Regards

Steve

**Comment by martinwoodward** [comment]
@ScottIsAFool - yeah, I don't think we thought they where in the API. I just found the "label" reference now and playing with it (/cc @willduff)

**Comment by ScottIsAFool** [comment]
@martinwoodward @willduff I wonder if it's because you can't get them for a blog. We could provide labels for blog posts, but not previous labels (unless we stored them locally)

**Comment by justmalt** [comment]
The labels are actually attached to the posts themselves on blogger so I don't think they are stored locally in any way.  I use them extensively.

**Comment by ScottIsAFool** [comment]
@justmalt But Blogger gives us no way to actually retrieve a list of your labels, hence why we'd have to store them locally.

**Comment by Indy27** [comment]
Then how did WLW did it? I don't think it received a whole label/category list, thus why we have to label each post manually.

**Comment by ScottIsAFool** [comment]
@indy27 WLW was using an older end point for Blogger which did allow access to that information. Google has removed it from the most recent versions.

**Comment by justmalt** [comment]
I know it worked as a pull-down list on WLW so there must have been code to do it?  It was to the left of the set post date.  The labels are blog-sensitive as well so if you change blogs, the pull-down list changes.  You can add them later on the blogger web interface, but it was more convenient to add them in Live Writer.

**Comment by ScottIsAFool** [comment]
@justmalt see my reply to Indy27.

**Comment by Indy27** [comment]
I would hate to say if this, too, may have to start from scratch.

**Comment by justmalt** [comment]
Saw it...I think you replied at the same time I was posting.  Makes sense.  The web interface still supports it so maybe there's some way to pull the labels in to OLW using that setup.  I say this with little knowledge of the coding you guys are doing and what you can and can't do.  I use labels all the time so I'm hoping there's a way to incorporate them in the future.

**Comment by Indy27** [comment]
Just a guess but what I think have you tried copying the code from WLW to OLW (doubt it'll work), and maybe tweak it to Blogger's new authentication settings? If I know where the coding for Blogger labels is in WLW, I could find a way to implement it in OLW, although I know very little coding experience (unlike my brother, who knows a lot).

**Comment by ScottIsAFool** [comment]
@Indy27 the new authentication won't allow you to use the old code, and the old code can't be used because you can't get authenticated.

**Comment by justmalt** [comment]
So here's a clue/hitch that may help.  I create a new post in OLW and post it.  No labels.  I go to the blogger web interface, add labels and publish.  Labels appear.  I open that same post in OLW and publish it again.  Labels REMOVED.  If you edit your post in OLW it removes the labels so there must be some code in there writing labels to blogger.

If we can't figure out how to make the labels available in OLW, we should consider removing the code that's removing them when you edit.

**Comment by Indy27** [comment]
I'm trying to figure out is that even possible?

**Comment by justmalt** [comment]
So this thread has been merged into #164?

**Comment by martinwoodward** [comment]
Sorry @justmalt - this means that we've fixed this using the code in #164. That fix will not show up in your version of Open Live Writer for a few days though, we need to do a new release for that to happen. We're just trying to fix some bugs around the new Blogger support and then we'll create a new release.

**Comment by n0tb0dy** [comment]
Did you publish this version with label suppurt? Is it ready for distribution?

**Comment by martinwoodward** [comment]
Afraid not (see the answer above).  Version will be coming in a few days once we've ironed out some other issues folks are reporting with the new Blogger support.

**Comment by n0tb0dy** [comment]
Thanks for your work!
