### ISSUE TITLE
TestPlan does not exist for testing new code

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter#162]
There is no test plan for testing new builds and codes.  

I have started one, and am happy for any help.
[OpenLiveWriterTestPlan.xlsx](https://github.com/OpenLiveWriter/OpenLiveWriter/files/65521/OpenLiveWriterTestPlan.xlsx)

Let's use this attached and expand on it as we go.

**Comment by kathweaver** [comment]
[OpenLiveWriterTestPlan.xlsx](https://github.com/OpenLiveWriter/OpenLiveWriter/files/65952/OpenLiveWriterTestPlan.xlsx)

Added new install worksheet

**Comment by kathweaver** [comment]
We might be ready to put this somewhere in the project so that we can check it in and out as we develop it.

**Comment by kathweaver** [comment]
Added worksheet for the File tab.
[OpenLiveWriterTestPlan.xlsx](https://github.com/OpenLiveWriter/OpenLiveWriter/files/66930/OpenLiveWriterTestPlan.xlsx)

**Comment by kathweaver** [comment]
Added Insert Tab and Blog Account

[OpenLiveWriterTestPlan.xlsx](https://github.com/OpenLiveWriter/OpenLiveWriter/files/67669/OpenLiveWriterTestPlan.xlsx)


So I have questions @martinwoodward Where would we put this?  I assume we need to add it to the existing branch?

I haven't done GitHub before.

**Comment by RobStand** [comment]
An Excel workbook may not be the right choice as it is difficult to merge when multiple people edit it. Do you think you could convert it to Markdown (an .md file)?

**Comment by kathweaver** [comment]
I'm not sure -- is there a tool for that?

**Comment by kathweaver** [comment]
Fun,I try to upload an .md file and Github won't let me.

**Comment by RobStand** [comment]
I can help you get the .md file into Github. You an either:

1. Clone the repo, add your file, commit, push, submit a pull request. (there are instructions on how to do this)
2. Go to the OLW repo in GitHub, click "New file", enter your markdown, give the file a name, and then click the "Create a new branch for this commit and start a pull request" radio button. Name your pull request (maybe "Issue162") and click "Create Pull Request".

For this fix, option 2 will be easiest and for the long term, learning how to do option 1 will be useful. Let me know if you have any questions.

**Comment by kathweaver** [comment]
I think I've done that -- pull request #193 
Option 1?

**Comment by RobStand** [comment]
Nice job. :+1:
