### ISSUE TITLE
Publishing fails but no errors thrown?

### ISSUE THREAD

**Issue by quadrathon** [OpenLiveWriter/OpenLiveWriter#165]
First of all thanks for taking on the OLW project it's a great product and I am sure it will only get better now!

Now the issue;

Created a post, included images, links, embedded video (you tube). Clicked publish, I get the uploading window but my blog does not update

Tried a hello world post and same thing, albeit faster

Double checked account settings couldn't see any problems

Running 0.5.1.2

**Comment by kathweaver** [comment]
Which blogging platform are you using?  Blogger? Wordpress?

**Comment by quadrathon** [comment]
@kathweaver Blogger http://quadrathon.blogspot.com/

**Comment by kathweaver** [comment]
Can you look a the log and see what it says:

:\AppData\Local\OpenLiveWriter\Open Live Writer.txt

**Comment by quadrathon** [comment]
There you go, thanks
[Open Live Writer.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/65792/Open.Live.Writer.txt)

**Comment by heyduke50** [comment]
I am using blogger and I get a 403 error returned when I paste images... just text works fine but images pasted via the clipboard seems to be a problem

**Comment by martinwoodward** [comment]
@heyduke50 - we have an issue with the Picasa integration that we're figuring out right now. Sounds like you might be running into it. Hopefully have that fixed soon

**Comment by kathweaver** [comment]
That log looks pretty helpful @guadrathon  -- however, beyond gathering information for Developers I can't do much.

**Comment by quadrathon** [comment]
Ok something happened at it's fixed!

**Comment by drhamptn** [comment]
I have a similar problem - published fine once today, then never again.  Here's the text file, thanks

[Open Live Writer.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/66110/Open.Live.Writer.txt)

**Comment by willduff** [comment]
@drhamptn I looked at your logs and you are hitting issue #170. I'll work on a fix for that soon!
