### ISSUE TITLE
Line spacing of indented test is lost on retrieved posts

### ISSUE THREAD

**Issue by drhamptn** [OpenLiveWriter/OpenLiveWriter#166]
When an exiting blog post is retrieved from Blogger, by:
  Click on File...Open Recent Post
  Highlight category Blog Name (at the bottom of the left pane)
  Click on a post to retrieve from the right pane

When the post is retrieved, line spacings are removed between paragraphs of indented text.

When I place the cursor at the end of a line and hit CR/LF, two LFs are introduced, not one.

The extra LF must be removed.

After the changes are made in OLW to re-introduce the paragraph spacing, the post publishes without errors and looks okay. 

  thanks!

**Comment by martinwoodward** [comment]
Do you have an example of a blog post you are doing with indented text?

**Comment by drhamptn** [comment]
Hi, Martin,  I tried with several previous posts and it seems to be corrected now.  I’ll see if it recurs, thanks for checking.  Best, Dave

**Comment by martinwoodward** [comment]
Thanks Dave - I'll close for now but please re-open if this happens again.
