### ISSUE TITLE
Jekyll support for github pages

### ISSUE THREAD

**Issue by angshuman** [OpenLiveWriter/OpenLiveWriter#168]
This is a much needed feature. Jekyll is not even officially supported on Windows and I think the 'Open Live Writer' product will gain a lot of traction if github pages is supported. Because of course, all the cool kids are using github. Thanks!

**Comment by martinwoodward** [comment]
Agreed - take a look at #55 where some smart folks are trying to figure this out.

Closing as a duplicate of #55.

**Comment by rebornix** [comment]
@angshuman we are working on GitHub Page integration and have implemented a few basic functions. You can follow https://github.com/rebornix/OpenLiveWriter/issues/1 for update.
