### ISSUE TITLE
The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by cgroveacademy** [OpenLiveWriter/OpenLiveWriter#170]
I just installed OLW yesterday and linked it to my blogger blog.  First post I try to make and I am getting this error.  Also, unrelated, I noticed that there is no way to tag posts, I figure it's in the works...but wanted to point it out, just in case.  Thanks!

**Comment by pulipulichen** [comment]
Try this: http://www.madrasnow.com/2015/12/solved-open-live-writer-login-issue.html

**Comment by martinwoodward** [comment]
We're working on a problem with Blogger oAuth token timeouts, hopefully have a fix coming out soon. That fix will also include the ability to label Blogger posts and use Split Post.

**Comment by Dinchy87** [comment]
@martinwoodward thanks for this clarification :) both of my wuestions are answered now.

**Comment by beingyogiraj** [comment]
[Here is a quick solution](http://www.thegeekydude.com/2015/12/fix-remote-server-returned-error-403.html)

**Comment by farsideoffifty** [comment]
I am still getting Forbidden 403 for my blog posts even though I have saved my password in the account settings and updated my account setting as suggested in the fix.  I have four blogs. 
beingyrogiraj that fix does not work for everyone.

**Comment by beingyogiraj** [comment]
Use any uninstaller program to completly uninstall it and then reinstall latest version from here. I have 15 blogger blogs, 3 WordPress and all of them are working fine.

**Comment by AmusedtoLife** [comment]
Same issues here, and the above listed fix didn't work.
My solution that has worked 100% of the time is to save my draft, republish a blog that is already loaded, go back to my draft, and voila, no problem uploading.

**Comment by willduff** [comment]
I have pull request #210 out now that should fix this. If anyone would like to help test the fix, can you install OpenLiveWriterSetup.exe from here and post to Blogger with an image in your post: 
https://ci.appveyor.com/project/dotnetfoundation/openlivewriter/build/0.5.0.60-idgdcsvi/artifacts

Thanks!
/cc @AmusedtoLife @beingyogiraj @Dinchy87 @pulipulichen @cgroveacademy @farsideoffifty @anserq

**Comment by farsideoffifty** [comment]
willduff I tried it and it returned NO ERROR.   Yeah!  You fixed it!   Thank you!

**Comment by martinwoodward** [comment]
Looks like the public build of 0.5.1.3 is fixing this issue. Closing for now. Thanks @willduff - you rock!

**Comment by AmusedtoLife** [comment]
Further confirmation. It's working fine-thx!

**Comment by esouza14** [comment]
I'm trying to post using Open Live Writer and currently getting this error Can't Publish box "The remote server returned an error: (403) Forbidden."
What to do??
