### ISSUE TITLE
Automatic Linking is not working

### ISSUE THREAD

**Issue by manuti** [OpenLiveWriter/OpenLiveWriter#173]
I add a lot of **Terms** and **Weblinks** but nothing happens in the post in local or even in publish mode. when edited published post. In new post is working OK and add Automatic Links everytime a write a Term in the List.

**Comment by jannavarro** [comment]
@willduff i will try to check this. how do i add a term or weblink? Is it via the Insert>Hyperlink?

**Comment by ScottIsAFool** [comment]
@jannavarro yes, you add a hyperlink then tick the box that says automatically link to this. You can also do it from File > Options > Automatic Linking

**Comment by jannavarro** [comment]
@manuti is this the step?

1.) Publish a post in OLW.
2.) Close or create a new post in OLW.
3.) Reopen published post.
4.) Add web link / hyperlink.

This is working for me. Let me know if your steps are different.

**Comment by manuti** [comment]
OK, works when you write by tipping but not when you Paste some text from other sources.
