### ISSUE TITLE
Blog accounts dropdown not updated

### ISSUE THREAD

**Issue by jtbworld** [OpenLiveWriter/OpenLiveWriter#174]
After using "Add blog account" the Blog accounts dropdown is not updated with the new account unless restarting OLW. Tested with Blogger accounts. Release 0.5.1.2

**Comment by rebornix** [comment]
While implementing GitHub provider, I ran into this situation half of times adding new accounts, I thought it was introduced by my code. Now it turns out to be a legacy code bug.

**Comment by ScottIsAFool** [comment]
Yep, long standing bug :)
