### ISSUE TITLE
Can't update user name and input my password in OLW...

### ISSUE THREAD

**Issue by ezbiker** [OpenLiveWriter/OpenLiveWriter#176]
Hello I tried to search this issue here, before submitting a ticket and didn't find it. In OLW, In photo1 (I have purposely copied and left out some of the original information for security purposes) I'm wanting to replace that information with my actual username information and also to remember my password. But once I've entered my information and click the next button, I get the error message as seen in photo 2. How can I update this information, please. :-D
Thanks
![photo1](https://cloud.githubusercontent.com/assets/16262330/11901237/778e7eda-a578-11e5-8025-fb145808bad1.png)
![photo2](https://cloud.githubusercontent.com/assets/16262330/11901244/7ae0cf34-a578-11e5-869f-521d145fd3b2.png)

**Comment by kathweaver** [comment]
Try pulling the latest build - https://olw.blob.core.windows.net/nightly/Releases/OpenLiveWriterSetup.exe

If that doesn't work, can you pull a log:

You can get access to your Open Live Writer logs by going to File, About Open Live Writer, Show log file. If you can see an error message that looks to be related to your issue then please include details of that as well.

**Comment by ezbiker** [comment]
I have uploaded the version you suggested and have input the information.
It's analyzing the information (See enclosed photo); but this has been
going on for about 5 min..  Is that normal? How do I generate a log for
this?

​
​

**Comment by ezbiker** [comment]
Duh... here's the file log... Thanks for your assistance in this. :-D

**Comment by ezbiker** [comment]
Update, still get the same incorrect password user name error. :-(

**Comment by kathweaver** [comment]
Odd I don't see the log file -- I can't do much but ask for the stuff the dev needs, but happy to help.

**Comment by ezbiker** [comment]
Sorry, I thought the attachment was in the email. I have enclosed it again
and just cut and pasted in in this email. :-)

OpenLiveWriter,1.6708,None,00001,18-Dec-2015 11:33:25.550,"Starting Open
Live Writer 0.5.1.2",""
OpenLiveWriter,1.6708,None,00002,18-Dec-2015 11:33:25.550,".NET version:
4.0.30319.34209",""
OpenLiveWriter,1.6708,None,00003,18-Dec-2015 11:33:26.145,"499 499",""
OpenLiveWriter,1.6708,None,00004,18-Dec-2015
11:33:26.268,"UpdateSemanticHtmlPreviewAsyncOperation started for
blog(93bebe8e-354e-47d8-bab7-6a14eaebe914)",""
OpenLiveWriter,1.6708,None,00005,18-Dec-2015 11:33:26.524,"Creating a
readable ribbon istream for
C:\Users\Ken\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.6708,None,00006,18-Dec-2015 11:33:42.192,"Creating a
writable ribbon istream for
C:\Users\Ken\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.6708,None,00007,18-Dec-2015 11:34:00.514,"Creating a
writable ribbon istream for
C:\Users\Ken\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.6708,None,00008,18-Dec-2015 11:34:01.682,"Creating a
writable ribbon istream for
C:\Users\Ken\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.6708,None,00009,18-Dec-2015
11:54:25.610,"UpdateSemanticHtmlPreviewAsyncOperation started for
blog(93bebe8e-354e-47d8-bab7-6a14eaebe914)",""
OpenLiveWriter,1.6708,None,00010,18-Dec-2015 11:54:30.729,"Creating a
writable ribbon istream for
C:\Users\Ken\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.6708,None,00011,18-Dec-2015 11:54:45.090,"Creating a
writable ribbon istream for
C:\Users\Ken\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.6708,None,00012,18-Dec-2015 11:55:00.101,"Creating a
writable ribbon istream for
C:\Users\Ken\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.6708,None,00013,18-Dec-2015 11:55:23.429,"Creating a
writable ribbon istream for
C:\Users\Ken\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.6708,None,00014,18-Dec-2015 11:55:57.265,"Creating a
writable ribbon istream for
C:\Users\Ken\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.6708,None,00015,18-Dec-2015 11:56:16.610,"Creating a
writable ribbon istream for
C:\Users\Ken\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.6708,None,00016,18-Dec-2015 11:56:27.346,"Creating a
writable ribbon istream for
C:\Users\Ken\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""

**Comment by willduff** [comment]
Hi @ezbiker, I assume you are working around issue #170. You actually don't need to change the username, and you don't even need to change the password. All that is needed is to hit Next to re-authenticate with Google Blogger. We will have a fix for this shortly.

**Comment by ezbiker** [comment]
Excellent! Thanks, have done what you suggested and it did OK! :-D
