### ISSUE TITLE
FTP help page is missing when you click on "How do I configure FTP site?

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter#179]
When in

Blog Account Tab
Blog Options
Pictures
FTP Settings
"How do I configure an FTP Site?

Opens browser to http://openlivewriter.org/WriterRedirect/WriterFTPHelpV3?Version=0.0&Build=5.0&Market=en-US

And gets a 404 File Not Found error
<img width="586" alt="image" src="https://cloud.githubusercontent.com/assets/7053084/11906231/ad6dcd36-a590-11e5-9c4f-c1f96481c46e.png">

**Comment by willduff** [comment]
@kathweaver thanks for opening an issue on the GitHub.io site, we should track the fix there. The product redirect URL looks fine to me and we already created one custom page for plugins on the GitHub.io site. In Open Live Writer, click on **Insert** on the Ribbon > **Add plugin** and you'll see the custom page. We should do the same for this.
