### ISSUE TITLE
Fix link to license in NUSPEC files

### ISSUE THREAD

**Issue by wasker** [OpenLiveWriter/OpenLiveWriter#18]
Guys, sorry, don't have tools on this machine to change this, but we need to update link to license in both NUSPEC files.

Right now it points to a
https://github.com/OpenLiveWriter/OpenLiveWriter/blob/bringup/license.txt?raw=true

We should also consider using the same approach to passing version to SDK NuGet as we do for a setup package.

**Comment by RobDolinMS** [comment]
Tagging @RobStand and @martinwoodward  to see if either can help with this.

**Comment by willduff** [comment]
Issue #3 is related - we can do the version update with that issue. Let's just get the correct links in our NuGet packages in this issue to keep it simple.

**Comment by martinwoodward** [comment]
In the short term I just created a bringup branch

**Comment by willduff** [comment]
Fixed with pull request #21.
