### ISSUE TITLE
Please respect copyright link in Insert Video dialog box navigatges to missing page

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter#182]
Clicking on "Please respect copyright" navigates to http://openlivewriter.org/WriterRedirect/Copyright in the browser, and gives a 404 File Not Found error,

<img width="367" alt="image" src="https://cloud.githubusercontent.com/assets/7053084/11911556/085c6dda-a5df-11e5-81db-f204f41c94d6.png">

Also View Terms of Service and View Safety Tips navigate to missing pages

View Terms of Service http://openlivewriter.org/WriterRedirect/YouTubeTOU?Version=0.1&Build=5.2&Market=en-US

View Safety Tips http://openlivewriter.org/WriterRedirect/YouTubeSafety?Version=0.1&Build=5.2&Market=en-US

**Comment by willduff** [comment]
@kathweaver Can you open an issue on the GItHub.io site for this and track it there? Thank you for finding these!

**Comment by kathweaver** [comment]
We may still need to change code to point to the correct page.
