### ISSUE TITLE
Error Regarding Label Limit

### ISSUE THREAD

**Issue by Indy27** [OpenLiveWriter/OpenLiveWriter#186]
So, I'm copypasting labels from the server to OLW the hard way, and the label limit to add is _20_, but I keep getting this error sometimes even though this also affects when I'm at **15 to 19** labels:

> The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
> We're sorry, but the value for field labels was not valid. [400]
> Errors [
> Message[We're sorry, but the value for field labels was not valid.] Location[ - ] Reason[invalid] Domain[global]
> ]
> 
> at Google.Apis.Requests.ClientServiceRequest`1.Execute()
> at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.NewPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
> at OpenLiveWriter.BlogClient.Blog.NewPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
> at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
> at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by Indy27** [comment]
So no one but me actually had this problem?

**Comment by nvella** [comment]
Hi all.

I wasn't able to reproduce this issue, making separate posts with 15, 16, 17, 18, 19 and 20 labels. I'll close this issue for now, but if you do encounter it again, please don't hesitate to drop a reply to this issue and I'll reopen it.

Cheers 👍
