### ISSUE TITLE
401 error connecting to Blogger with Dev Build

### ISSUE THREAD

**Issue by xrabohrok** [OpenLiveWriter/OpenLiveWriter#187]
After building and running OLW through the build scripts, clicking "Sign In" on the Startup Wizard drops me into a 401 screen from Google:

![image](https://cloud.githubusercontent.com/assets/3222168/11915551/e9f858ee-a670-11e5-9b07-d5e8f6aa8147.png)

Is there anything I should (know/do) about this?

**Comment by ScottIsAFool** [comment]
I've just submitted a pull request that has the documentation on this. If you want to see it now, have a look at https://github.com/ScottIsAFool/OpenLiveWriter/blob/Update-Build-Docs-for-Local-Blogger-Build/docs/Connectiong%20to%20Blogger%20From%20a%20Local%20Build.md.

If that file doesn't exist, then it means it's been merged into this repository, in which case, have a look in the docs folder and you'll see the instructions there.

**Comment by xrabohrok** [comment]
Oh cool, didn't know someone already knew how to do this, I'll give it a
shot tonight.

**Comment by xrabohrok** [comment]
I had to create a project after clicking "Enable and Manage APIs".  Might want to mention that and/or anything we might need to know there.

**Comment by xrabohrok** [comment]
That seemed to work, thanks!
