### ISSUE TITLE
Start an end user facing documentation site

### ISSUE THREAD

**Issue by lextm** [OpenLiveWriter/OpenLiveWriter#192]
Though currently Open Live Writer users come from Windows Live Writer user base, I think it is worth the while to provide enough documentation to teach new users how to use it. Then right now there is little official documentation from .NET Foundation on this part.

Thus, I propose that Read the Docs can be used to set up a documentation site. The maintenance of that doc site can be moved to a separate repo, and focus more on non-coding related topics. The split from this GitHub repo is because bloggers are not strictly developers who fork and code. We should find a way to treat non-developers better.

I defined the following tasks and would like to see what's your opinions to move on,

- [x] Create initial site contents at GitHub using reStructuredText
- [x] Set up a Read the Docs site with GitHub back end
- [ ] Bring over Windows Live Writer documentation (if related permissions can be granted)
- [ ] Write more documentation in a community driven way

The demo site is right now at https://openlivewriter.readthedocs.org/en/latest/, but ideally should be hosted as http://docs.openlivewrite.org. The test repo is right now at https://github.com/lextudio/openlivewriter_docs but ideally should be https://github.com/openlivewriter/docs.

**Comment by rebornix** [comment]
Thanks lextm ! ReadTheDocs is on the list when we consider adding documentation for OLW.

In the same time, we are thinking about linking OLW code with Docfx, which powers .Net Core and Asp.Net. It helps reflect the code and generation reference docs, that can be a good point for OLW. 

I'll sync with the team about the CI setup and share the details with community next week. Let's see whether we use ReadTheDocs or GitHub Page as the hosting platform.

**Comment by rebornix** [comment]
BTW, Docfx is a full featured docs generation tool. You can write Conceptual or Reference docs using Markdown or Rst, Conceptual is common user facing while Reference Page is developer facing. And of course it's GitHub based, giving you the ability of version control.

**Comment by lextm** [comment]
Let's see how it goes with docfx!
