### ISSUE TITLE
When creating new blog, EditURI section is not handled

### ISSUE THREAD

**Issue by Crypt32** [OpenLiveWriter/OpenLiveWriter#196]
I'm running my blog on a custom blog engine. In order to support Live Writer, I use MetaweblogAPI. In the web site's html I added an entry:

    <link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://www.domain.com/wlwrsd.xml" />

When follow the referenced XML from web browser, it downloads correct RSD XML file:

    <?xml version="1.0" encoding="UTF-8" ?>
    <rsd xmlns="http://archipelago.phrasewise.com/rsd" version="1.0">
      <service>
        <enginename>Metaweblog</enginename>
        <enginelink>http://www.domain.com/home/engine.aspx</enginelink>
        <homepagelink>http://www.domain.com</homepagelink>
        <apis>
          <api blogID="http://www.domain.com/default.aspx" name="MetaWeblogAPI" preferred="true" apilink="http://www.domain.com/mwbv1.ashx" />
        </apis>
      </service>
    </rsd>

However, when I add new blog, OLW (and WLW) asks me for the Metaweblog API URL (http://www.domain.com/mwbv1.ashx). Then the connection succeeds.

I believe, the format of RSD file is correct (I used MSDN to prepare RSD file).

**Comment by ScottIsAFool** [comment]
Can you try name="MetaWeblog" instead of MetaWeblogAPI in your <api> tag

**Comment by Crypt32** [comment]
Yes, that was the case. Now OLW automatically picks weblog.

**Comment by ScottIsAFool** [comment]
:+1:
