### ISSUE TITLE
Excerpt is not published from the first attempt [0.5.1.2]

### ISSUE THREAD

**Issue by Crypt32** [OpenLiveWriter/OpenLiveWriter#207]
Today I blogged two posts to my weblog. My MetaweblogAPI provider supports excerpts. Before publishing, I compose excerpt in the post properties. When I publish the post, excerpt is not published. At least, it is not shown on web site. No errors appear. When I publish the same post again (immediately), excerpt is published successfully and excerpt appears on web site.

I examined log file, there are errors.

**Comment by ScottIsAFool** [comment]
If there are errors in the log file, can you post the log file please.

**Comment by Crypt32** [comment]
I'm very sorry. It is not an OLW issue, it was a bug in my web site. I debugged my code and found the bug.
