### ISSUE TITLE
User feedback - no way to input categories on a blog post!

### ISSUE THREAD

**Issue by craftingbelle** [OpenLiveWriter/OpenLiveWriter#208]
I hope this is the right way to leave feedback on an issue...I'm just an end user and understand none of this behind the scenes stuff.

WLW has stopped communicating with blogger again, so I saw Open Live Writer and thought I would give it a try as I absolutely detest bloggers in built post writer.

Loving it so far but a big issue is there is no box to add categories to a post. The only workaround for me is publishing my post and then going into the dreaded blogger editor to add them....unfortunately blogger then undoes all the formatting that OLW so nicely let's us create. Help!!

**Comment by Indy27** [comment]
There is a nightly build version out there that has this beta feature, the beta version being a text box similar to Blogger instead of the almighty powerful drop-down check box feature in WLW. There's no speculation if we'll ever have the WLW one in OLW anytime soon or at all.

**Comment by willduff** [comment]
This has already been fixed in issue #157 - Support for Labels/Tags/Categories in Blogger. We haven't released an official build that contains this fix yet, but I plan to release a new build this week that you can use.
