### ISSUE TITLE
Publishing a post 

### ISSUE THREAD

**Issue by romona** [OpenLiveWriter/OpenLiveWriter#209]
Hi, 
There is a new thing happening now. I use Blogger. 
I can set up a post with text and images in OLW, then choose Publish. It goes through the usual steps to publish but when it's done, my blog opens up and the new post hasn't posted at all, it's still showing me the last post I did.  Also at the bar above the post, the categories have disappeared. If I click on Insert, I see the option to Post Tags, but I've never used that, only the categories and those are missing??? Any suggestions. Thanks so much..

**Comment by msniw** [comment]
After having spent about an hour and half downloading Open Live Writer for five blogs that worked very well in the former Windows Live Writer programme, I, too, am disappointed to discover a '403 forbidden' message when I tried to publish a test post a few minutes ago. Further, I am disappointed that for whatever reason, the OLW team has decided to dispense with photograph albums as the dispays available always enhanced blog features.

**Comment by ScottIsAFool** [comment]
@romona With moving to the new Blogger bits, we have had to drop support for categories (at least temporarily, we hope) as the new Blogger bits don't support it. As for your blog not displaying the post you just published, is that happening every time? 

@msniw We have a fix coming soon for the 403 forbidden message.

**Comment by msniw** [comment]
Hello - 
Thanks for your response. I must also point out that although I included Google-plus tags, the system displayed a 'tags not included' message.  BTW, at the risk of appearing churlish and unappreciative, would it not have been better to have sent a blanket message to your thousands of WLW users about the changes and then waited until everything was up-and-running; all glitches eliminated, before the launch? All the best fir the festive season. Natalie Wood.

**Comment by ScottIsAFool** [comment]
@msniw The fix is now available. If you leave Open Live Writer open for a minute, then close and restart it, you should have the fixed build.

**Comment by romona** [comment]
Before commenting, I tried to post again to my blog and this time it worked, so thank you whoever did their bit of magic since last night, you guys are great for working on this for us. There are still fixes coming, so it's all good. Once the categories can be resolved, I can easily go back and repost where they are missing,

**Comment by msniw** [comment]
Thank you. OLW now works very well. but I must advise you that while Google tags appear on the live blogs, the OLW pre-post still includes an error message stating that there are no tags present. Perhaps that problem will also be solved soon. All the best.

**Comment by willduff** [comment]
Hi @msniw, I just tried and I did **not** see the error message you mentioned. Can you follow the [instructions for sending your Writer log file](https://github.com/OpenLiveWriter/OpenLiveWriter/wiki/Instructions-for-sending-your-Writer-log-file) and reference GitHub issue #209 in your email? Thanks.

**Comment by msniw** [comment]
Dear Will Duff

I followed your instructions and found the log file easily. However  I am
unable to upload the file items either via an email or to GitHub. The
'Update' e.g., was refused for security reasons. I am now worried about
doing damage I cannot rectify myself and will have to leave it.

With thanks and apologies.

Natalie Wood

 http://www.esra.org.il/sites/default/files/esra_logo_new_2011.jpg



[image: --]

Natalie Wood
[image: http://]about.me/msniw
<http://about.me/msniw?promo=email_sig>

**Comment by willduff** [comment]
Hi @msniw, my only suggestion would be to right click on the *Open Live Writer.log* file and choose **Send to** > **Compressed (zipped) folder**. This will create an *Open Live Writer.zip* file that you might be able to email me using the [instructions for sending your Writer log file](https://github.com/OpenLiveWriter/OpenLiveWriter/wiki/Instructions-for-sending-your-Writer-log-file). I'm not sure why your email provider would flag a *.log file as a security issue, it's just a simple text file. You could also try renaming it to *Open Live Writer.txt*.

**Comment by msniw** [comment]
Hello - Pls. let me know if you receive this. I've copied and pasted it
from Google help:


"Some file types are blocked

"As a security measure to prevent potential viruses, Gmail doesn't allow
you to send or receive executable files (such as files ending in .exe).
Executable files can contain harmful code that might cause malicious
software to download to your computer. In addition, Gmail doesn't allow you
to send or receive corrupted files, files that don't work properly.

File types that can't be sent or received

You can't send or receive the following file types:

.ade, .adp, .bat, .chm, .cmd, .com, .cpl, .exe, .hta, .ins, .isp, .jar,
.jse, .lib, .lnk, .mde, .msc, .msp, .mst, .pif, .scr, .sct, .shb, .sys,
.vb, .vbe, .vbs, .vxd, .wsc, .wsf, .wsh

Messages containing the types of files listed above will be bounced back
and returned to the sender automatically. Gmail won't accept these file
types even if they're sent in a zipped format. Here are some examples of
zipped formats:

.zip, .tar, .tgz, .taz, .z, .gz, .rar

Zip file within another zip file

It isn't possible to send a password-protected zip file containing a zip
file. Please de-compress all files or remove the password protection if
possible.

Mac users, sending a zip file which also contains another zip file
increases your chances of file corruption. We recommend that you
de-compress all files first and create only one zip file."

Regards

NIW

Maximum file size

<https://support.google.com/mail/bin/answer.py?answer=6583&hl=en>
<https://support.google.com/mail/bin/answer.py?answer=8770>





 http://www.esra.org.il/sites/default/files/esra_logo_new_2011.jpg



[image: --]

Natalie Wood
[image: http://]about.me/msniw
<http://about.me/msniw?promo=email_sig>

**Comment by kathweaver** [comment]
Has this been resolved?

**Comment by msniw** [comment]
Dear Katherine Weaver - Thanks for your note. No, the issue has not been resolved but as it does not hinder my work over-much I've decided simply to cope with the problem, as is. However, if you and your colleagues are able to iron out the creases concerning tags and reintroduce the picture album feature, I'd be much obliged. T/A Regards, Natalie Wood.

**Comment by kathweaver** [comment]
Which part of your issue remains unresolved.  We did a new release recently and it should have solved everything but the photo issue.  Open Live Writer should automatically update when you open it.

**Comment by msniw** [comment]
Thank you for your response. By an unfortunate coincidence for me, my own
computer is being repaired and the machine I'm using to write to you cannot
access OLW. I will write again in a few days.

Thanks again

Natalie Wood

 http://www.esra.org.il/sites/default/files/esra_logo_new_2011.jpg





[image: --]

Natalie Wood
[image: http://]about.me/msniw
<http://about.me/msniw?promo=email_sig>

**Comment by msniw** [comment]
Dear Kathleen Weaver

I now have my own machine again.

The issues remaining with Open Live Writer are:


   1.  Tags are not recognised when I insert them although they appear in
   the published post.
   2. The spell-check facility does not work (it is greyed out).

T/A

Natalie Wood
 http://www.esra.org.il/sites/default/files/esra_logo_new_2011.jpgDEar
Kathleen Weaver

I now have my own machine again.

Thhe issues remaining with





[image: --]

Natalie Wood
[image: http://]about.me/msniw
<http://about.me/msniw?promo=email_sig>




---------- Forwarded message ----------
From: Natalie Wood <msniwood@gmail.com>
Date: 22 February 2016 at 19:52
Subject: Re: [OpenLiveWriter] Publishing a post (#209)
To: OpenLiveWriter/OpenLiveWriter <
reply@reply.github.com
>


Thank you for your response. By an unfortunate coincidence for me, my own
computer is being repaired and the machine I'm using to write to you cannot
access OLW. I will write again in a few days.

Thanks again

Natalie Wood

 http://www.esra.org.il/sites/default/files/esra_logo_new_2011.jpg





[image: --]

Natalie Wood
[image: http://]about.me/msniw
<http://about.me/msniw?promo=email_sig>

**Comment by kathweaver** [comment]
You don't have the latest version.  Try opening OLW again and see if the spelling is ungreyed.  If not, go to our page and download the latest:  http://www.openlivewriter.org

**Comment by msniw** [comment]
Hello

Thanks for your help. I've downloaded the new version twice but it's not
changed anything. Perhaps it's because I'm using Windows Vista? I know
you've stated that you can't support XP, so perhaps there's also a problem
with Vista. Anyway, as I'm not being prevented from using OLW, I won't
trouble you further. Thanks again for your efforts.

Best wishes

Natalie Wood

 http://www.esra.org.il/sites/default/files/esra_logo_new_2011.jpg





[image: --]

Natalie Wood
[image: http://]about.me/msniw
<http://about.me/msniw?promo=email_sig>

**Comment by lextm** [comment]
@msniw Spell check is only available on Windows 8 and above. Windows Vista and 7 are too old to have the underlying Windows API. See #130 for more details. It is not likely that there would be any effort to support spell check on Windows Vista and 7.

Meanwhile, Blogger tags/labels support was discussed in #157. As the label support was designed to be limited as revealed in #164, what you observed can simply be by design. There could be improvements if anyone has time to dive deeper into Blogger's API, but that should be tracked in another thread (feature request) instead of this old and lengthy one.

**Comment by msniw** [comment]
Thank you.

Natalie Wood

 http://www.esra.org.il/sites/default/files/esra_logo_new_2011.jpg





[image: --]

Natalie Wood
[image: http://]about.me/msniw
<http://about.me/msniw?promo=email_sig>

**Comment by kathweaver** [comment]
I guess I meant you didn'  t have the latest version of Windows :-)

**Comment by nvella** [comment]
Closing this issue as problems mentioned by @msniw seem to be fixed (in the case of Blogger labels) or won't be fixed (spell-check on Windows Vista).
