### ISSUE TITLE
OLW 0.5.1.3 Does not update the list of labels for Blogger

### ISSUE THREAD

**Issue by n0tb0dy** [OpenLiveWriter/OpenLiveWriter#214]
Even when you press the refresh button , the list of labels is not loaded. I use blogger service.

![2015-12-22_150214](https://cloud.githubusercontent.com/assets/10028543/11954774/3bf77a7e-a8bc-11e5-8f1b-1fd39dee2540.png)

**Comment by n0tb0dy** [comment]
How it was in WLW

![2015-12-22_151632](https://cloud.githubusercontent.com/assets/10028543/11954960/33fab7da-a8be-11e5-9510-9a39b97fef74.png)

**Comment by ScottIsAFool** [comment]
Unfortunately, we had to move to a new Blogger service in order for users to be able to actually authenticate and *use* Blogger. Moving to that had its own downside in that it doesn't support getting a list of your blog's categories/labels. All we can do right now is provide you a space to write your own tags (comma separated). We are investigating how best to try and bring this back though.

**Comment by n0tb0dy** [comment]
Thanks! I hope you can do it!

**Comment by Indy27** [comment]
@ScottIsAFool Did you try asking some of the devs at Blogger (or even Google) that helped with WLW, see if any of them would give info on this situation? I know it's a long shot, but any bit of information would be good.

**Comment by ScottIsAFool** [comment]
I believe @martinwoodward was planning to reach out. I don't know if anything came of it or whether he got any responses.

**Comment by Indy27** [comment]
Okay. I see 5.1.3's out, where to get?

**Comment by ScottIsAFool** [comment]
@indy27 open live writer, leave it a minute, the restart it, that should give you the latest version.

**Comment by martinwoodward** [comment]
I haven't reached out yet to the Blogger team - will do now we have 0.5.1.3 out.

@Indy27 the other way to force an update is to download again from http://openlivewriter.org.

**Comment by vasudevG** [comment]
I'm not getting even the space to write own tags... it has only the Set post date. This is for Blogger blog. While it shows for WordPress blog.

**Comment by martinwoodward** [comment]
@vasudevG - sounds like you are not on 0.5.1.3 yet? (check in your about box). If you restart you should be upgraded or you can force an update by downloading again from http://openlivewriter.org

**Comment by vasudevG** [comment]
I'm on 0.5.1.3

**Comment by vasudevG** [comment]
![olwblogger](https://cloud.githubusercontent.com/assets/16251943/11965299/cd003ddc-a919-11e5-89cb-37e0457e8018.png)

**Comment by martinwoodward** [comment]
Wow. Very odd. Can you take a screen shot of the about box and also the blog capabilities dialog? Many thanks.

**Comment by martinwoodward** [comment]
So, response from Google Blogger team as follows:

  [unique list of labels] isn't something we currently expose through the API. I've asked the API team if this is something we could expose easily. In the mean time I suggest you go ahead with a scan and cache approach

**Comment by Indy27** [comment]
Which, basically, come up with our own invention...nice, Google. That can take, I don't know, *weeks*, even **months** depending on various factors.

**Comment by vasudevG** [comment]
@martinwoodward And magically its appearing now :) 
![olwblogger1](https://cloud.githubusercontent.com/assets/16251943/11970796/175b95d8-a957-11e5-8ad2-32c923c15576.png)
But the username is some alphanumeric, tried to re-enter the values but it says, username, password is incorrect. 
![olwblogger2](https://cloud.githubusercontent.com/assets/16251943/11970853/0eca5732-a958-11e5-9516-02e8d51b9986.png)
Though I'm able to post to blogger blog. Thanks.

**Comment by vhanla** [comment]
What about the url `/feeds/posts/summary?alt=json&max-results=0&callback=cat` where you can get the labels as `term`, and it doesn't even need an API key?

**Comment by ScottIsAFool** [comment]
@vhanla have you got a link to where that's referenced?

**Comment by vhanla** [comment]
@ScottIsAFool I'm not sure but I guess it is from Blogger's API 1.0, I suppose that old API is going to be deprecated, but I've also seen many third party widgets and tutorials that uses that old method.

BTW there is also a widget from Blogger that lists labels, hope they will allow to list labels in the newer APIs.

**Comment by ScottIsAFool** [comment]
I think that API is already deprecated (hence the Blogger issues we had recently)

**Comment by vhanla** [comment]
For example, this is what google chrome releases blogspot page show give that url
http://googlechromereleases.blogspot.de/feeds/posts/summary?alt=json&max-results=0&callback=cat
```json
// API callback
cat({
    "version": "1.0",
    "encoding": "UTF-8",
    "feed": {
        "xmlns": "http://www.w3.org/2005/Atom",
        "xmlns$openSearch": "http://a9.com/-/spec/opensearchrss/1.0/",
        "xmlns$blogger": "http://schemas.google.com/blogger/2008",
        "xmlns$georss": "http://www.georss.org/georss",
        "xmlns$gd": "http://schemas.google.com/g/2005",
        "xmlns$thr": "http://purl.org/syndication/thread/1.0",
        "id": {
            "$t": "tag:blogger.com,1999:blog-8982037438137564684"
        },
        "updated": {
            "$t": "2015-12-23T07:11:51.489-08:00"
        },
        "category": [{
            "term": "Dev updates"
        }, {
            "term": "Beta updates"
        }, {
            "term": "Chrome OS"
        }, {
            "term": "Stable updates"
        }, {
            "term": "Chrome Beta for Android"
        }, {
            "term": "Admin Console"
        }, {
            "term": "Chrome for Android"
        }, {
            "term": "Chrome for iOS"
        }, {
            "term": "Android WebView"
        }, {
            "term": "Chrome OS Management"
        }, {
            "term": "Chromecast Update"
        }, {
            "term": "Flash Player update"
        }, {
            "term": "Chrome Dev for Android"
        }, {
            "term": "dev update"
        }, {
            "term": "chrome"
        }],
        "title": {
            "type": "text",
            "$t": "Chrome Releases"
        },
        "subtitle": {
            "type": "html",
            "$t": "Release updates from the Chrome team"
        },
        "link": [{
            "rel": "http://schemas.google.com/g/2005#feed",
            "type": "application/atom+xml",
            "href": "http:\/\/googlechromereleases.blogspot.com\/feeds\/posts\/summary"
        }, {
            "rel": "self",
            "type": "application/atom+xml",
            "href": "http:\/\/www.blogger.com\/feeds\/8982037438137564684\/posts\/summary?alt=json\u0026max-results=0"
        }, {
            "rel": "alternate",
            "type": "text/html",
            "href": "http:\/\/googlechromereleases.blogspot.com\/"
        }, {
            "rel": "hub",
            "href": "http://pubsubhubbub.appspot.com/"
        }],
        "author": [{
            "name": {
                "$t": "laforge@chromium"
            },
            "uri": {
                "$t": "http:\/\/www.blogger.com\/profile\/05995691326314939344"
            },
            "email": {
                "$t": "noreply@blogger.com"
            },
            "gd$image": {
                "rel": "http://schemas.google.com/g/2005#thumbnail",
                "width": "16",
                "height": "16",
                "src": "http:\/\/img2.blogblog.com\/img\/b16-rounded.gif"
            }
        }],
        "generator": {
            "version": "7.00",
            "uri": "http://www.blogger.com",
            "$t": "Blogger"
        },
        "openSearch$totalResults": {
            "$t": "1824"
        },
        "openSearch$startIndex": {
            "$t": "1"
        },
        "openSearch$itemsPerPage": {
            "$t": "0"
        }
    }
});
```
There is says version 1.0

**Comment by ScottIsAFool** [comment]
Ah, interesting. Thanks for this, it might prove *very* useful. @willduff

**Comment by martinwoodward** [comment]
FYI - I know it's easy for the community to diss the Blogger team but they have been very responsive to us when we've asked for things and have always been very classy. I personally have nothing but good things to say about them.

I'd be fine with us using an older API that appears to be working as a temporary measure until we have a better API or we've built an algorithm to extract the data from existing supported API's as long as we code around it defensively (i.e. work on the assumption that the API might stop working at some point and fail quietly rather than crash the entire app or give lots of scary warnings to the user).

If someone wanted to take a go at doing it using the API above then this is where the logic would be called https://github.com/OpenLiveWriter/OpenLiveWriter/blob/master/src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Client.cs#L312

**Comment by ScottIsAFool** [comment]
@martinwoodward already on it ;)

**Comment by ScottIsAFool** [comment]
ICanHazCategories 
![image](https://cloud.githubusercontent.com/assets/1658896/11980440/ae3ba19c-a992-11e5-8003-43125bc3ec70.png)

**Comment by ScottIsAFool** [comment]
A WIP pull request is in #234

**Comment by Indy27** [comment]
Wait, that ACTUALLY worked!? (or is that just Wordpress and y'all trying to fool us)

But what I was going to say was that the one @vhanla posted was for the API 1.0 how would that work anyway? Did Microsoft and other desktop editors used the 1.0 version when Blogger went 2.0 and it somehow still worked, or what?

----------------
Different problem but it really needs to be answered:

> Limit for labels is 20 on Blogger, that's a fact. Why is that sometimes I have a post with 15 to 19 labels, this pops up:

    The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
    We're sorry, but the value for field labels was not valid. [400]
    Errors [
    Message[We're sorry, but the value for field labels was not valid.] Location[ - ] Reason[invalid] Domain[global]
    ]

    at Google.Apis.Requests.ClientServiceRequest`1.Execute()
    at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.NewPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
    at OpenLiveWriter.BlogClient.Blog.NewPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
    at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
    at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

Is it a label issue or a character issue (character issue being that no more than 200 letters, which was the case if you was inputting labels WHILE MAKING A POST but not the case at the post/page menu)

**Comment by ScottIsAFool** [comment]
Here we go, this is better, multiple categories now working :) 
![image](https://cloud.githubusercontent.com/assets/1658896/11980728/d2520240-a994-11e5-85ac-11264c6a1a39.png)

**Comment by Indy27** [comment]
Well, can test this as soon as a nightly is available.

**Comment by ScottIsAFool** [comment]
Labels showing up in the blog post now, including new ones that get added http://scottisafool.blogspot.co.uk/2015/12/and-another.html

**Comment by ScottIsAFool** [comment]
If anyone wants to test this, they can run the Setup exe from here https://ci.appveyor.com/project/ScottHanselman/openlivewriter/build/1.0.178/artifacts I believe that should give them the build with which to test it :)

**Comment by Indy27** [comment]
Will this also fix the error I keep posting above?
https://github.com/OpenLiveWriter/OpenLiveWriter/issues/214#issuecomment-166941596

**Comment by ScottIsAFool** [comment]
@Indy27 yes, no, maybe. I have no idea :)

**Comment by Indy27** [comment]
I'll do a check then, brb.

**Comment by Indy27** [comment]
(http://funkyimg.com/i/25Kaq.png)

Notice the category box has an exact number of 20 which is Blogger's label limit.

**Comment by ScottIsAFool** [comment]
@Indy27 if you remove the last category, does it work?

**Comment by Indy27** [comment]
Removed the last category.
Same error.

This HAS to be a character issue, which should not be happening unless you was labeling while making or editing a post.

**Comment by ScottIsAFool** [comment]
I'm beginning to suspect it's the Google API libraries we're using because there's nothing wrong (that I can see) with what we're doing.

**Comment by Indy27** [comment]
Just counted how many characters that image has and it's well over 200 characters. WLW never had that problem and I'm pretty sure the rest of the blog editors before the Blogger API switch either.

**Comment by Indy27** [comment]
You could give this a try but dunno if it'll work but, what if there was a way to drag-and-drop labels instead of manually checking a box, as a way to save time.

**Comment by vhanla** [comment]
**Combined length** of all labels should be 200 characters max.

![bloggerlabelslengthlimit](https://cloud.githubusercontent.com/assets/1015823/11985843/04a6d408-a997-11e5-9173-59f26d9d9893.png)

**Comment by ScottIsAFool** [comment]
So what would people prefer? For Writer to just remove any labels that take it over that limit? Or a warning before doing so?

**Comment by vhanla** [comment]
Maybe disabling unchecked categories and disabling _Add category_ input text too, but also showing a message below it or inside that input text.
![olwbloggercategorylimit](https://cloud.githubusercontent.com/assets/1015823/11986700/9c150464-a9a0-11e5-9024-62ae2a66ef86.png)

**Comment by Indy27** [comment]
Maybe to remove any label that takes it over the limit. But there should be a way to take off the limit anyway. I remember a trick where at the Pages screen you can check a page and add up to 20 labels WITHOUT worrying about character limit. That trick still works today. Even WLW used that trick before the software 'died'.

**Comment by jtbworld** [comment]
Testing now and find that opening an existing post with categories does not show the categories in OLW.

**Comment by Indy27** [comment]
Yeah @jtbworld is right. Tested this now, labels disappear when opening existing posts. Don't know if this was posts made before altering the labels code or what.

**Comment by Indy27** [comment]
Okay, so I made a draft post with labels, saved it to blogger, open new post, then went back to open the draft post. After getting past the 'Unable to Retrieve from Server' crap, it opened the post with same labels I gave it, so yeah, any saved posts containing labels you guys did before the category fix will show up without them.

**Comment by martinwoodward** [comment]
Thanks @Indy27 - are you still getting that error message with 0.5.1.4?

**Comment by ScottIsAFool** [comment]
@jtbworld Sorry, I should have updated my post with a newer installer https://ci.appveyor.com/api/buildjobs/19jjjw36d5kadqai/artifacts/Releases/OpenLiveWriterSetup.exe That is fixed.

**Comment by n0tb0dy** [comment]
As it all became very strange after upgrading to 0.1.5.4. In the program directory are preserved and the old version 0.1.5.3. When I run the old version (0.1.5.3) there appears a list of tags from my blog.

![2015-12-24_165243](https://cloud.githubusercontent.com/assets/10028543/11995343/498c3d6e-aa60-11e5-9dc2-0e4851749ec8.png)

![2015-12-24_165302](https://cloud.githubusercontent.com/assets/10028543/11995346/51ffe2a2-aa60-11e5-8cf8-88fb3be4bc4d.png)

 And when launch a new version (0.1.5.4) the list of labels disappears.

![2015-12-24_165346](https://cloud.githubusercontent.com/assets/10028543/11995351/6effc110-aa60-11e5-82a6-4e098325ea06.png)

![2015-12-24_165405](https://cloud.githubusercontent.com/assets/10028543/11995355/743f56fe-aa60-11e5-9a18-a7a0969657de.png)

**Comment by ScottIsAFool** [comment]
Had you been trying the category fix?

**Comment by n0tb0dy** [comment]
How to applay category fix?

**Comment by n0tb0dy** [comment]
How to completely remove OLW with all settings?

**Comment by Indy27** [comment]
*Thanks @Indy27 - are you still getting that error message with 0.5.1.4?*

Don't know cuz I'm still at 5.1.3 and neither the setup.exe to the main site nor appveyor upgrades to the new version nor the OLW I have now auto-update.

**Comment by Indy27** [comment]
Okay, never mind, it auto-updated when I click it in the Start Menu.

**Comment by Indy27** [comment]
Tried 514, few problems:
- Still have the 'Unable to Retrieve from Server' when you open up a saved or drafted post although you can just click it and the post will show anyway
- No label list; uses Blogger-style way of labeling
- Labels disappear when opening up saved posts from 5.1.3 (haven't tested 5.1.4)

**Comment by ScottIsAFool** [comment]
@Indy27 you wont have the fixed labels unless you use the installer I mentioned earlier. What's the exact error you're getting for the retrieving from server error? can you post your log file?

**Comment by Indy27** [comment]
Log file (http://www.multiup.org/download/ada8fc658c62a4c19368fa1847a21301/Open_Live_Writer.rar)

**Comment by ScottIsAFool** [comment]
@Indy27 The error you're seeing is being tracked with bug #96

**Comment by willduff** [comment]
Thank you very much @ScottIsAFool for fixing this issue! You'll see this functionality in Open Live Writer the next time we push out an official version. It was fixed with pull request #234 - Support Blogger categories.

**Comment by ScottIsAFool** [comment]
Thanks go to @vhanla for finding that endpoint to use :)

**Comment by DawnL43072** [comment]
thanks for the fix!!
