### ISSUE TITLE
Code Formatting Option for WordPress

### ISSUE THREAD

**Issue by Skatterbrainz** [OpenLiveWriter/OpenLiveWriter#216]
The "Pre" formatting option would be very helpful for posting program source code content.  If it's already baked in, I can't seem to find it.  Any help would be greatly appreciated.  Thank you!

**Comment by ScottIsAFool** [comment]
There are plugins that will allow you to do this. We will be announcing something for the plugins soon.

**Comment by Skatterbrainz** [comment]
ok.  thank you!
