### ISSUE TITLE
Unable to Open OLW (for ver 5.1.2 only), Trick to Open OLW

### ISSUE THREAD

**Issue by Indy27** [OpenLiveWriter/OpenLiveWriter#219]
This is for people who're getting this problem to open up OLW: If you can't open OLW and got this message (may be different) in your log file as shown below:
**This was for o.5.1.2. I just downloaded 5.1.3 and opened with no problems**

> 2015-12-22 13:22:47> Program: Starting Squirrel Updater: --install .
> 2015-12-22 13:22:47> Program: Starting install, writing to C:\Users\Josh\AppData\Local\SquirrelTemp
> 2015-12-22 13:22:47> Program: About to install to: C:\Users\Josh\AppData\Local\OpenLiveWriter
> 2015-12-22 13:22:47> Program: Install path C:\Users\Josh\AppData\Local\OpenLiveWriter already exists, burning it to the ground
> 2015-12-22 13:22:47> Utility: The files inside C:\Users\Josh\AppData\Local\OpenLiveWriter\app-0.5.1.2 could not be read
> 2015-12-22 13:22:47> Utility: The directories inside C:\Users\Josh\AppData\Local\OpenLiveWriter\app-0.5.1.2 could not be read
> 2015-12-22 13:22:47> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.UnauthorizedAccessException: Access to the path 'C:\Users\Josh\AppData\Local\OpenLiveWriter\app-0.5.1.2' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.SetAttributes(String path, FileAttributes fileAttributes)
>    at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
> 2015-12-22 13:22:47> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Josh\AppData\Local\OpenLiveWriter\app-0.5.1.2' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.SetAttributes(String path, FileAttributes fileAttributes)
>    at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Update.Program.<Install>d__4.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()
>    at Squirrel.Update.Program.executeCommandLine(String[] args)
>    at Squirrel.Update.Program.main(String[] args)
> ---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\Josh\AppData\Local\OpenLiveWriter\app-0.5.1.2' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.SetAttributes(String path, FileAttributes fileAttributes)
>    at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

So what I had to do was open up the AppData OLW and deleted the app folder that you could not authorize, and then re-open OLW and voila! But, anyway to NOT undergo through this over and over?

**Comment by paulcbetts** [comment]
Looks like you tried to install 5.1.3 when 5.1.2 was still running (perhaps in the background?)
