### ISSUE TITLE
Feature Parity with WLW 2012?

### ISSUE THREAD

**Issue by chrisaswain** [OpenLiveWriter/OpenLiveWriter#22]
Does this version of Live Writer have the same features as the 2012 version I have installed currently?

**Comment by RobDolinMS** [comment]
Thanks for writing @chrisaswain.  The current version is v0.5.  Our target for full feature parity is v1.0.  You can see a "roadmap" at: https://github.com/OpenLiveWriter/OpenLiveWriter/blob/master/roadmap.md

**Comment by martinwoodward** [comment]
You can take a look at [Scott Hanselman's](http://www.hanselman.com/blog/AnnouncingOpenLiveWriterAnOpenSourceForkOfWindowsLiveWriter.aspx ) post for some more background color on what isn't there and why.

 - REMOVED: Spell Checking. The implementation was super old and used a 3rd party spell checker we didn't have a license to include an open source release. Going forward we will add Spell Check using the built-in spell checker that was added in Windows 8. Open Live Writer on Windows 7 probably won't have spell check.
 - REMOVED: The Blog This API. It was a plugin to Internet Explorer and Firefox and was a mess of old COM stuff.
 - REMOVED: The "Albums" feature. It uploaded photos to OneDrive but depended on a library that was packaged with Windows Live Mail and Live Messenger and we couldn't easily get permission to distribute it in an open source project.
 - [ADDING VERY SOON](https://github.com/OpenLiveWriter/OpenLiveWriter/issues/5): Google runs the excellent Blogger blog service. We've worked with the Blogger Team within Google on this project, and they've been kind enough to keep an older authentication endpoint running for many months while we work on Open Live Writer. Soon, Google and Blogger will finally shut down this older authentication system. Blogger will use the more modern OAuth 2 and Open Live Writer will be updated to support OAuth 2. Windows Live Writer will never support this new OAuth 2 authentication system, so if you use Blogger, you'll need to use Open Live Writer.
 - BROKEN/KNOWN ISSUES: We are actively working on supporting Plugins. We have an plan in place and we are looking for your feedback on the most popular plugins that you want brought over from the Windows Live Writer ecosystem.
