### ISSUE TITLE
Post title box

### ISSUE THREAD

**Issue by romona** [OpenLiveWriter/OpenLiveWriter#225]
When I open OLW, the cursor defaults below the post title box. A few days ago I was unable to change the font in the post title box. Now I can see the font I set up in the customize section of the blogger dashboard, but i should be able to change the font directly in the post title box. I can't access it from OLW directly because the function is greyed out, I have to go back to customize on the blogger dashboard, and change the font there if I need/want to do that. It's a small problem but wondering if others are seeing this as well. 
Thanks so much.

**Comment by martinwoodward** [comment]
This is by design I'm afraid - we pick up the title used by your blog's theme and deliberately disable the font controls in the toolbar.
