### ISSUE TITLE
open live writer

### ISSUE THREAD

**Issue by MariaDarwin** [OpenLiveWriter/OpenLiveWriter#229]
Hola no si me estoy dirigiendo al sitio apropiado,pero es que me estoy volviendo loca; descargué el programa y no me funciona y ni siquiera se si funciona con windows 7  que es el sistema que tengo. No se adonde dirigirme y todo lo que encuentro esta en ingles. Haber si alguien puede ayudarme. Muchas gracias

**Comment by martinwoodward** [comment]
Lo siento si esto no es correcto - Estoy utilizando la traducción automática para responder. No hemos hecho mucho con Windows 7, la mayoría de nuestro desarrollo que ocurre en Windows 10. Tenemos algunos problemas con Windows 7 (# 107 ) . Voy a cerrar esto como una copia de # 107, pero si usted tiene otros problemas en Windows 7, háganoslo saber.

**Comment by MariaDarwin** [comment]
Muchas gracias y un saludo

El 23 de diciembre de 2015, 16:59, Martin Woodward <notifications@github.com
> escribió:

> Lo siento si esto no es correcto - Estoy utilizando la traducción
> automática para responder. No hemos hecho mucho con Windows 7, la mayoría
> de nuestro desarrollo que ocurre en Windows 10. Tenemos algunos problemas
> con Windows 7 (# 107 ) . Voy a cerrar esto como una copia de # 107, pero si
> usted tiene otros problemas en Windows 7, háganoslo saber.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenLiveWriter/OpenLiveWriter/issues/229#issuecomment-166930862>
> .
>



--
