### ISSUE TITLE
Support TLS 1.2

### ISSUE THREAD

**Issue by bmaehr** [OpenLiveWriter/OpenLiveWriter#248]
Blogs which require TLS 1.2 could not be connected.
To fix this have a look at https://stackoverflow.com/questions/4137106/are-there-net-implementation-of-tls-1-2

Also the workaround 
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319]
"SchUseStrongCrypto"=dword:00000001
is working.

**Comment by Crypt32** [comment]
If I understand it correctly, .NET do not have its own implementation of SS:/TLS, it uses operating system's SSL module. In the case of Windows, it is SChannel. SChannel is differen in certain (old, but still supported) OS versions may not support all modern protocols. For example, Windows Server 2008 do not support TLS v1.2.

**Comment by bmaehr** [comment]
The OS does support TLSv1.2, otherwise my workaround with the registry would not work.

It is only necessary to allow OpenLiveWrite to use TLSv1.2 like in the linked example shown:

System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls; // comparable to modern browsers
var response = WebRequest.Create("https://www.howsmyssl.com/").GetResponse();
var body = new StreamReader(response.GetResponseStream()).ReadToEnd();

**Comment by dorianmuthig** [comment]
The .NET framework (on Windows) will use the operating system's SSL/TLS library and preferences to make any SSL/TLS connections. Unless you explicitly specify the protocol version or cipher suite order to use it will be chosen automatically based on the clients supported cipher suites and the cipher suites supported by the server. The industry standard configuration for TLS enabled servers is to enable cipher suite order enforcement on the server, which means, the client will be forced to use the first commonly supported cipher suite from the server's supported cipher list.
So unless OpenLiveWriter explicitly specifies that TLS1.2 not be supported when connecting (and I don't see it doing that), it should work just fine, if your operating system's cipher suites include at least one your server wants to use. To be able to use TLS1.2 in client mode, you need to use Windows Vista (Server 2008) with Service Pack 2 or newer. I am not sure which version of Mono introduced TLS1.2 support (and so far OpenLiveWriter doesn't work with Mono, yet)
On Windows not all TLS1.1/TLS1.2 cipher suites are enabled by default, even on the latest versions of the operating system, even though they are supported by the SChannel security library. The default cipher suite order also does not list the most secure options first, which means that if you are running your website on a Windows server, you will not get the best protection the system has to offer.
Please see the following links for more information:
* [How to restrict the use of certain cryptographic algorithms and protocols in Schannel.dll](https://support.microsoft.com/en-us/kb/245030 "How to restrict the use of certain cryptographic algorithms and protocols in Schannel.dll")
* [TLS/SSL3 Cipher Suites](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380512(v=vs.85).aspx "Information about the cipher suites available with the TLS protocol in Windows Server 2003 and Windows XP.")
* [Schannel Cipher Suites in Windows Vista](https://msdn.microsoft.com/en-us/library/windows/desktop/ff468651(v=vs.85).aspx "Schannel Cipher Suites in Windows Vista")
* [Prioritizing Schannel Cipher Suites](https://msdn.microsoft.com/en-us/library/windows/desktop/bb870930(v=vs.85).aspx "Prioritizing Schannel Cipher Suites")
* [Windows NT 10.x recommended TLS cipher suite order](https://pastebin.com/aCJXbEAR "[INI file] Windows NT 10.x recommended TLS cipher suite order - Pastebin.com")

**Comment by bmaehr** [comment]
This is really annoying. Instead of fixing the problem which is one line of code linked by me in the first post there is a long discussion about some other things. http://stackoverflow.com/questions/26389899/how-do-i-disable-ssl-fallback-and-use-only-tls-for-outbound-connections-in-net/26392698#26392698
It is ok if you don't understand it and you don't want to fix the problem then you can close the issue, cause I have found a workaround (posted also in the first comment) for me.

**Comment by Crypt32** [comment]
Why are you so mad?

Sent from Outlook Mobile<https://aka.ms/sdimjr>




On Sun, Jan 3, 2016 at 2:09 PM -0800, "bmaehr" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #248<https://github.com/OpenLiveWriter/OpenLiveWriter/issues/248>.

-
