### ISSUE TITLE
Login not working for blogger account

### ISSUE THREAD

**Issue by kunal2383** [OpenLiveWriter/OpenLiveWriter#25]
Tried login to OLW with blogger credential with an active blog account on Google blogger, but was not able to do so. It always says "Invalid username or password". Not facing this issue on WLW. Please check login system on OLW for blogger.

**Comment by martinwoodward** [comment]
Possibly related to #5 - should definitely be fixed by it.

**Comment by willduff** [comment]
See [Scott Hanselman's post](http://www.hanselman.com/blog/AnnouncingOpenLiveWriterAnOpenSourceForkOfWindowsLiveWriter.aspx) about this:

>ADDING VERY SOON: Google runs the excellent Blogger blog service. We've worked with the Blogger Team within Google on this project, and they've been kind enough to keep an older authentication endpoint running for many months while we work on Open Live Writer. Soon, Google and Blogger will finally shut down this older authentication system. Blogger will use the more modern OAuth 2 and Open Live Writer will be updated to support OAuth 2. Windows Live Writer will never support this new OAuth 2 authentication system, so if you use Blogger, you'll need to use Open Live Writer.

Issue #5 tracks switching to use OAuth2 for connecting to Blogger accounts.

**Comment by gregornoriskin** [comment]
I am using 2 factor authentication on Google and all attempts to log in with a application password fails.
