### ISSUE TITLE
Version Control

### ISSUE THREAD

**Issue by SteveP-UK** [OpenLiveWriter/OpenLiveWriter#250]
Hi Guys. Thanks for all your hard work with OLW. I was so pleased to be able to blog over Christmas. Without your help, I wouldn't have been able to. 

My question: is there any way for me to keep track of any upgrades to OLW? I'm not a Programmer, but am I right in thinking that OLW upgrades 'silently' when the app is launched? Is there a Changelog I can view? Big Thanks

Steve

**Comment by ScottIsAFool** [comment]
Yes, we are updating the Releases section when we do an update with what's been fixed https://github.com/OpenLiveWriter/OpenLiveWriter/releases

**Comment by SteveP-UK** [comment]
Cheers Scott - does it show the version number of OLW? I can't see it.

**Comment by ScottIsAFool** [comment]
Yes
![image](https://cloud.githubusercontent.com/assets/1658896/12016535/ff1fe0fa-ad43-11e5-81f0-5a59c6747bf5.png)

**Comment by SteveP-UK** [comment]
My bad! Off to SpecSavers now! ☺
