### ISSUE TITLE
can't sign with blogger

### ISSUE THREAD

**Issue by kolamfindel** [OpenLiveWriter/OpenLiveWriter#258]
when i authorize a blog, this error appears:

![image](https://cloud.githubusercontent.com/assets/16476491/12044673/66b94964-ae74-11e5-8eb4-4e866e5560f0.png)

**Comment by kathweaver** [comment]
Can you send us a log:  it's in %localappdata%\OpenLiveWriter

You can also get to it by clicking on the File Tab, Clicking on About, and at the bottom click on Show Log File.  

Thanks!

**Comment by kolamfindel** [comment]
Hi!
  There is the log.

Thanks!

2015-12-30 0:37 GMT-03:00 Kathleen Weaver <notifications@github.com>:

**Comment by willduff** [comment]
@kolamfindel What operating system are you using?

The updater is failing, we should make sure to show the proper Writer 'unexpected error' dialog here instead of what the screenshot shows above.

**Comment by kolamfindel** [comment]
i've a trouble with my computer, reinstaling windows. now all works fine...
