### ISSUE TITLE
New Post not showing

### ISSUE THREAD

**Issue by romona** [OpenLiveWriter/OpenLiveWriter#259]
The last two posts I've put on my blog, (google) are not the posts that I just finished. OLW is re-posting the previous post. The next day when I check my blog, the new post is now there. I don't know why because it goes through the process of uploading the new posts, but they don't show up right away, just the previous one.
The other thing I discovered tonight was that the bullets don't work. Occasionally I do a bullet list, but that feature isn't working. 
Thanks for all the work as always, that you're all putting in...

**Comment by kathweaver** [comment]
Can you send us a log: it's in %localappdata%\OpenLiveWriter

You can also get to it by clicking on the File Tab, Clicking on About, and at the bottom click on Show Log File. 

Thanks!

**Comment by romona** [comment]
I hope this works, I had to do it notepad, it wouldn't attach as a word doc.Thanks.

[OLW log Dec29.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/74611/OLW.log.Dec29.txt)

**Comment by romona** [comment]
I'm wondering if you've been able to figure out what is causing my posts to
not show up right after publishing them. I did sent the log as requested,
and posted that on GitHub,
https://github.com/OpenLiveWriter/OpenLiveWriter/issues/259, The bullet
option isn't working right yet either. When I click on the bullet option,
the paragraph i put the bullet in front of; indents, but the actual icon
doesn't appear. Thanks so much.

mailto <romona@shaw.ca>:romona.king@gmail.com

WEBSITE:  http://www.northbrookdesigns.com

BLOG1: http://northbrookdesigns.blogspot.com

PINTEREST: http://pinterest.com/romonak/

**Comment by kathweaver** [comment]
The developers seem to be on a short break.  I'm just helping out as I can -- facilitating issues for them.

**Comment by romona** [comment]
Okay.... thanks for responding...

mailto <romona@shaw.ca>:romona.king@gmail.com

WEBSITE:  http://www.northbrookdesigns.com

BLOG1: http://northbrookdesigns.blogspot.com

PINTEREST: http://pinterest.com/romonak/

**Comment by willduff** [comment]
Sounds like this is issue #224 - Publishing hour bug.

**Comment by romona** [comment]
Thank you yes, Same issue. I posted yesterday and it was 9 hrs later before
the post showed up, but at least it did, I'm thankful for that..

mailto <romona@shaw.ca>:romona.king@gmail.com

WEBSITE:  http://www.northbrookdesigns.com

BLOG1: http://northbrookdesigns.blogspot.com

PINTEREST: http://pinterest.com/romonak/

**Comment by willduff** [comment]
OK, I will look into fixing that bug soon, we are getting lots of feedback about it. Thanks for letting us know!

**Comment by romona** [comment]
I'm just wondering if there has been anything worked on re: the delay in
posts showing up since I first asked about it a few weeks ago. I know there
are a ton of things happening, just wondered if there is a fix coming or
any kind of update about the problem.
Thanks so much.

mailto <romona@shaw.ca>:romona.king@gmail.com

WEBSITE:  http://www.northbrookdesigns.com

BLOG1: http://northbrookdesigns.blogspot.com

PINTEREST: http://pinterest.com/romonak/
