### ISSUE TITLE
Open Live Write closes when I try to update a theme from Blogger

### ISSUE THREAD

**Issue by mannrw** [OpenLiveWriter/OpenLiveWriter#267]
My blog is www.mannkindperspectives.blogspot.com. When I try to update the theme I get the message attached and Live Writer closes. I had the same message when I tried to set up the theme when adding the account for the first time.

![openlivewriter stopped working](https://cloud.githubusercontent.com/assets/16504324/12068038/447475fa-afc2-11e5-86a2-b2d396db650e.JPG)

**Comment by ScottIsAFool** [comment]
Can you attach your log file, it can be found at %localappdata%\openlivewriter

**Comment by mannrw** [comment]
Here's the log file. BTW thanks for taking live writer into the open source
community. You are doing a wonderful service.

Regards,

Rod

On Thu, Dec 31, 2015 at 1:38 PM, Scott Lovegrove <notifications@github.com>
wrote:

> Can you attach your log file, it can be found at
> %localappdata%\openlivewriter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenLiveWriter/OpenLiveWriter/issues/267#issuecomment-168243597>
> .
>



-- 
Rod Mann
801-847-2051
www.mannkindperspectives.com

**Comment by ScottIsAFool** [comment]
Unfortunately, attaching the log to the email doesn't attach it to the issue.

**Comment by mannrw** [comment]
Here's the log file. I had to rename it to a .txt file.
[Open Live Writer - Copy.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/75764/Open.Live.Writer.-.Copy.txt)

**Comment by agoosa** [comment]
I'm having the same problem. 

Here's the kicker though, I have it working fine on my pc, but it's on my laptop that this error is occurring. 

[Open Live Writer.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/76011/Open.Live.Writer.txt)

**Comment by agoosa** [comment]
I'm very curious as to what this "stopped working" error is caused by. The signing in process for blogger (for me) gets all the way to the "download finished" but does not actually complete then comes the popup. Is this a time-out problem? I've tested it with other blogger blogs and they work fine. The one it crashes on is a blog that has 500+ posts and 1000+ comments and is media heavy just FYI.

**Comment by rgssolutions** [comment]
I'm having the same problem so I feel bad for you son, I got 99 problems but large blog ain't one.

**Comment by nelsonkodama** [comment]
I'm having the same problem but when trying to open a post specifically: 

![bug](https://cloud.githubusercontent.com/assets/16329205/12076117/bb73bb1a-b185-11e5-9f28-7f748eec5a4d.jpg)

Here is the log file:


[Open Live Writer.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/76398/Open.Live.Writer.txt)

**Comment by gmilazzoitag** [comment]
Same issue. Blogger configuration. 
I've used for a while OLW but a week ago it started to crash once opened after few seconds, also with no action at all.
So I've removed everything from %appdata% and from registry. 
Running the OpenLiveWriterSetup.exe from scratch it starts the configuration, download everything, themes and so on, create the temporary post, finalizes the config but calling the program this immediately crashes.

**Comment by willduff** [comment]
@agoosa @mannrw @rgssolutions @gmilazzoitag Are you all using Windows 10?

I do not reproduce this issue - downloading my theme from Blogger works fine. I have the latest Windows 10 update on my Surface Pro 3.

**Comment by mannrw** [comment]
I am running Windows 10 on a laptop. I have the problem with my primary blog but not another one that has  simpler layout and uses fewer widget.

**Comment by gmilazzoitag** [comment]
Really weird!!!
Today I ran setup again and now it has worked to the end. I've also tried to update theme from blog with no issue.

**Comment by romona** [comment]
This is great. I can also now see what I'm typing in the title box as it is
defaulting to the colour of text I set it at. Also the colour of the text
in the message window is also now defaulting to black which is great. It
was in both cases white... Thanks for the fixes...

mailto <romona@shaw.ca>:romona.king@gmail.com

WEBSITE:  http://www.northbrookdesigns.com

BLOG1: http://northbrookdesigns.blogspot.com

PINTEREST: http://pinterest.com/romonak/

**Comment by agoosa** [comment]
@willduff Yes, on both machines I'm running Win10 x64 

The laptop is now running smoothly! I'm loving OLW and so is everyone I'm giving it too! The fear of losing WLW is no longer an issue!

**Comment by mannrw** [comment]
Whatever was done resolved my issue. Thanks.
