### ISSUE TITLE
Watermark?

### ISSUE THREAD

**Issue by cgroveacademy** [OpenLiveWriter/OpenLiveWriter#268]
Is there a way to automatically water mark uploaded pictures?  Thanks!

**Comment by ScottIsAFool** [comment]
There certainly is, when you add your image to your blog post, click on the image, then click on the Picture Tools Format tab, then watermark
![image](https://cloud.githubusercontent.com/assets/1658896/12070123/2d1c2d66-b059-11e5-90b3-95750e79c745.png)
