### ISSUE TITLE
Rename Setup.exe

### ISSUE THREAD

**Issue by stefanstranger** [OpenLiveWriter/OpenLiveWriter#27]
Please change the setup.exe fle on the http://openlivewriter.org/ website to something more unique please.

Not sure if this is something which should be fixed within this repo though...

**Comment by RobDolinMS** [comment]
@stefanstranger  Can you elaborate on the relative priority here?  Is this blocking/breaking install or more of a nice-to-have?

**Comment by stefanstranger** [comment]
Nice to have. There are more applicatons who have a setup,exe file so if you download again a setup.exe file in your download folder it gets 'messy'. No big deal but don't like to have multiple setup.exe files for different applications.

**Comment by panjkov** [comment]
Seems a bit confusing, so I would give it a little bit higher priority here.
 Once you download it, you can only distinct proper application installer by its icon. Something like "OpenLiveWriterSetup_0.6.0.exe would be a little bit better

**Comment by martinwoodward** [comment]
I agree - not sure about the version part as we're using [Squirrel](https://github.com/squirrel/squirrel.windows) to auto-update but definitely be good to be OpenLiveWriterSetup.exe if we can do it without breaking too much.

**Comment by shiftkey** [comment]
This seems to be the simplest solution:

> https://github.com/Squirrel/Squirrel.Windows/issues/219

This should be separate to the updating - which goes through `Update.exe`

**Comment by RobDolinMS** [comment]
I'm :+1: to @martinwoodward's suggestion of OpenLiveWriterSetup.exe (assuming it's supported.)

**Comment by willduff** [comment]
This is easy enough. I'll look into renaming it for the next release.

**Comment by shanselman** [comment]
Now that we are released, as long as this doesn't break ANY existing
installs, I'm OK with it. I don't see the need for the version number in
the file name, though, as we are using an evergreen installer.

On Wed, Dec 9, 2015 at 2:05 PM, Rob Dolin (MSFT) <notifications@github.com>
wrote:

> I'm [image: :+1:] to @martinwoodward <https://github.com/martinwoodward>'s
> suggestion of OpenLiveWriterSetup.exe (assuming it's supported.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenLiveWriter/OpenLiveWriter/issues/27#issuecomment-163410761>
> .
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by shiftkey** [comment]
:thumbsdown: to version number in file name

**Comment by DavidBurela** [comment]
:+1: to changing name to OpenLiveWriterSetup.exe
:-1: to version number in file name

**Comment by paulcbetts** [comment]
You can rename the Setup.exe to whatever you want, it won't break anything

**Comment by stefanstranger** [comment]
Ok now everyone agrees to renaming setup.exe to something more descriptive, “make it so” with or without version number. :-)
