### ISSUE TITLE
I don't get an e-mail when I post in open live writer

### ISSUE THREAD

**Issue by anserq** [OpenLiveWriter/OpenLiveWriter#271]
I have set blogger to e-mail me when i publish a post, but i'm not getting any e-mails. Is this known?

**Comment by ScottIsAFool** [comment]
If you go to your blog and the blog post is there, that's the end of Live Writer's involvement. Any emails sent out would be done from your blog provider.

**Comment by anserq** [comment]
Okay thanks

**Comment by chbwien** [comment]
That can't be true, because using WLW, this worked perfectly. This would be a coinsitant, that Google changed the behaviour in the same moment as OpenLiveWriter took over.
