### ISSUE TITLE
Crashes when Insert Video From Web and use valid http://youtube address

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter#275]
It get the following crash:

<img width="279" alt="crash" src="https://cloud.githubusercontent.com/assets/7053084/12077003/fbd41fc2-b18c-11e5-9a01-fcb9124d1aae.png">

[Open Live Writer.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/76464/Open.Live.Writer.txt)

**Comment by nvella** [comment]
Just tried to reproduce then and the video object seemed to insert successfully, however, it inserted the old YouTube Flash player which is no longer functional, and the insert form didn't work with a https link (had to replace with http). I'll close this issue, and add both those observations to their relevant issues.
