### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by Happy4OLW** [OpenLiveWriter/OpenLiveWriter#283]
I have scheduled a post for January 8th @ 8pm.  When I go to my blog and check my drafts the post shows as being scheduled for Jan 9th @ 1am.  My blog is set to my correct timezone.  Is there something I need to change within OLW to make it sync?  So grateful that (o)LW is back!!

**Comment by kandiphillips** [comment]
I'm having the same issue, would love to know the answer to fix this!

**Comment by DawnL43072** [comment]
Same trouble, scheduled posts are for 8am but blogger shows 1pm!

**Comment by survivor303** [comment]
Yep same problem with blogger!

**Comment by hashhar** [comment]
Sorry for the late response. Could you try scheduling a post and see when it gets published?

It could also be possible that OLW is only showing the wrong time according to your timezone but is publishing it at the correct time.

**Comment by hashhar** [comment]
I'll look into this. Also could you tell me your time zone?

**Comment by banders03** [comment]
I'm wondering where one sets the time zone? I've looked in my account 
and don't see it. Thanks for any help!

Barbara

**Comment by DawnL43072** [comment]
Eastern…. thanks

**Comment by kathweaver** [comment]
The time zone is probably retrieved from your computer, but I will also acknowledge that I haven't read the code.

**Comment by willduff** [comment]
Closing as dupe of issue #262 - Google Blogger scheduled post is scheduled at the wrong time
