### ISSUE TITLE
Text wrapping around picture fails for numbered and bulleted lists

### ISSUE THREAD

**Issue by StephenTurners** [OpenLiveWriter/OpenLiveWriter#288]
When I insert a picture from my local computer into the post and then select the text wrapping option for the picture to Left the text flows correctly around the picture obeying the defined margin settings except for if the text contains a numbered or bulleted list.
If there is a list in the text then the bullet or number remains in the indented position that it would have been in if the picture wasn't present.  The text after the bullet or number does however move to the correct location to the right of the picture.  This is shown in the picture below.
![wrapping issue snip](https://cloud.githubusercontent.com/assets/1795616/12113751/de0fe86a-b39c-11e5-85f1-c1b2202c9421.PNG)
I'm using version 0.5.1.4 and running on Windows 7 Professional with SP1 - 64bit.  I'm publishing to a SharePoint 2010 blog.

**Comment by willduff** [comment]
Hey Stephen, this seems to be an issue with your blog's CSS. If you go to the **Blog Account** tab in the Ribbon, you can turn off your blog theme by clicking the **Blog Theme** button and it should look fine then:

![image](https://cloud.githubusercontent.com/assets/134678/12357825/f73d5858-bb5e-11e5-92d1-418610e41dbc.png)
