### ISSUE TITLE
Configure Drafts and Posts folder

### ISSUE THREAD

**Issue by way0utwest** [OpenLiveWriter/OpenLiveWriter#29]
The existing version (and previous ones) had a path stored in the registry for keeping the drafts and posted items. Can we move this to an options setting to make it easy to reconfigure Open Live Writer?

**Comment by dhusemann** [comment]
Would be nice for future cross platform also.

**Comment by pekiZG** [comment]
I'm willing to help with this one.
Also usage of %AppData% would be nice.

**Comment by bsimser** [comment]
Trying to follow the plugin folder discussion (#74) and it's not clear to me that %AppData% is viable with squirrel. I think %AppData%/OpenLiveWriter should be the root for all of these things (with folders for each requirement /Posts /Drafts /Plugins etc. There's a new bug I'm logging about registry settings and it would be nice to just remove the registry dependency.

**Comment by pekiZG** [comment]
@bsimser yes of course I was thinking the same thing.
We should have apropriate folder under %APPDATA% as you wrote OpenLiveWriter or something similar. All other stuff under "home" folder of the OLW.

- %APPDATA%
  - OpenLiveWriter
    - Posts
    - Drafts
    - Plugins
    - Etc...

**Comment by pekiZG** [comment]
So I have managed to run the OLW.
Poking around the code to see how to make this happen :)

**Comment by ScottIsAFool** [comment]
This will be in the next version of Live Writer
