### ISSUE TITLE
GoogleApiException error

### ISSUE THREAD

**Issue by DawnScotting** [OpenLiveWriter/OpenLiveWriter#292]
Yesterday I had good luck in being able to post a draft to my blog with OLW. I can also post a TEST post just fine so I know I have OLW set up correctly.

However, this afternoon, I'm getting this error when trying to post a normal post that includes photos and text. I can still post a TEST post that includes only text AND a TEST post that included one photo plus text.

Anything other than that brings up this GoogleApiException error and it won't post at all.

Anyone else having this problem or is just me? Help please someone.

Cheers....Dawn

**Comment by ScottIsAFool** [comment]
Can you post your log file please, this can be found in %localappdata%\OpenLiveWriter

**Comment by DawnScotting** [comment]
Oh, I thought I posted my log file here last night but I see it's no longer there. It was very long so maybe I mucked it up somehow, will try again.
