### ISSUE TITLE
Unable to detect the BlogEngine blog settings..

### ISSUE THREAD

**Issue by niranjankala** [OpenLiveWriter/OpenLiveWriter#295]
Hi,
I am also .net guy and love to use blogengine for my personal website. After getting issue with my blogger blog today I switched to OLW and tried to configure these. Now it comes the time to configure my blog and OLW is not able to detect the blog settings. 

In the specified list of blog services I did not find the way to configure it. I found another issue that blogger categories are not still listing.

Regards,
Niranjan

**Comment by ScottIsAFool** [comment]
OLW does support blogengine.net are you able to provide a link to your blog?

**Comment by niranjankala** [comment]
Oh.. Sorry for late reply. Suddenly my blog had some issues. 
We have lots of things missing from WLW. Syntax Highlighting plugins etc. It would be hard to use these two tools for different blogs. 
Below is my blog url- http://niranjankala.in

Regards,
Niranjan

**Comment by nvella** [comment]
Hi there. I'll close this issue for now as your latest reply implies that you've resolved your issue. Source code highlighting is currently a work-in-progress, there is an open PR over at #658. If you have any further queries, please don't hesitate to reply. Cheers 👍
