### ISSUE TITLE
(500) Internal Server Error - Image Related

### ISSUE THREAD

**Issue by justmalt** [OpenLiveWriter/OpenLiveWriter#299]
Just started getting this error when posting to blogger:

The remote server returned an error: (500) Internal Server Error.

Worked fine all day then I noticed the error   Seems to be image related.  If I remove images fomr the post it works.

I'm hoping it's temporary but I thought I'd report it.

**Comment by ScottIsAFool** [comment]
To which blog type are you posting?

**Comment by justmalt** [comment]
blogger

**Comment by ScottIsAFool** [comment]
Ok, looks like someone else is reporting the same error in #300. This will likely be a problem on Blogger's side and should clear up soon. Will leave this bug open though in case it doesn't.

**Comment by justmalt** [comment]
Thanks...it may be related to their image server.  Hopefully it clears itself up but I wanted to report it in case it was the result of an update.

**Comment by justmalt** [comment]
Seems to have resolved itself.  A few hours later it started working.

**Comment by ScottIsAFool** [comment]
Thanks for letting us know.
