### ISSUE TITLE
Can't retrieve drafts from Google Blogger

### ISSUE THREAD

**Issue by Susheelkaram** [OpenLiveWriter/OpenLiveWriter#301]
When I am trying to open recent posts from my blogger blog, I can only see Published posts.
There are no Drafts.
File > Open Recent posts > MY BLOG and now here only published posts are listed and no Drafts that I have in my Blogger account.

**Comment by tubbystar** [comment]
I'm having the same problem too. I have to copy the html from Blogger back into OLW then continue editing.

**Comment by willduff** [comment]
I fixed this with pull request #367, and the fix will be included in the next public OLW release.
