### ISSUE TITLE
Backport OLW to Windows XP

### ISSUE THREAD

**Issue by fml2** [OpenLiveWriter/OpenLiveWriter#302]
I still use Windows XP and have no plans to upgrade soon. However, I'd like to use OLW to post entries to my Blogger blog. Since Windows Live Writer does not work with Blogger anymore, it would be nice if OLW would also work with Windows XP -- maybe after installing some software which is not part of a standard WinXP installation, e.g. a particular version of .NET.

**Comment by lextm** [comment]
Windows XP reached end of life years ago and it would be quite difficult and also not worth the while to work for such an obsolete platform.

**Comment by fml2** [comment]
You are right, XP is not supported anymore. But it's still widely used, according to some stats. Besides, isn't a pleasure to develop for a very stable platform? :-)

It's just a humble request though, I wouldn't insist hard that it must be implemented. Just out of curiosity: what makes OLW unusubale under XP?

**Comment by ScottIsAFool** [comment]
@fml2 It's the version of .NET that Live Writer has moved to that is no longer supported on XP.

**Comment by RobStand** [comment]
I would put this at the very bottom of the priority list.

**Comment by fml2** [comment]
What version of .NET is required for OLW to work? It's possible to install .NET separately on XP. If OLW is tied to a particular version of .NET (or above) and not to a version of Windows, then it might be possible that OLW will work under XP without the need to modify OLW's code.

**Comment by ScottIsAFool** [comment]
It uses .net 4.5 which doesn't support the older platforms http://blogs.msdn.com/b/dotnet/p/dotnet45xp.aspx

**Comment by fml2** [comment]
Thanks for the information! It would be helpful if this requirements were listed somewhere near (or directly on) the home page.

**Comment by ScottIsAFool** [comment]
It's in our FAQ (sort of, by omission) https://github.com/OpenLiveWriter/OpenLiveWriter/blob/master/faq.md , but we should probably add some clarification to that @kathweaver

**Comment by lextm** [comment]
@ScottIsAFool should move to .NET 4.5.2 now. All older releases are end of life after Jan 12, 2016. https://support.microsoft.com/en-us/lifecycle#gp/Framework_FAQ

**Comment by ScottIsAFool** [comment]
@lextm it is :) I was going on memory and it was easier to just say 4.5 :)

**Comment by TruboXL** [comment]
I don't know whether this is possible but if someone manages to port OLW to Linux/Mac OSX using Mono, it maybe possible to port OLW to Windows XP and have it run under Mono instead of .Net 4.5 in which Mono is still supported on XP and 4.5 is not.

PS: I thought OLW needs .NET Framework 4.6?
Windows 7 tells me to install that version then allow me to install OLW after I install 4.5...

**Comment by lextm** [comment]
@TruboXL just to remind you that Mono WinForms on Windows is different from .NET's WinForms. Running something on Mono might fill some of the gaps like .NET 4.5 support, but it would introduce new issues that .NET Framework does not have. Good luck on your adventure.
