### ISSUE TITLE
New Window is opened when preferences to use single window is choosing.

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter#303]
Go to File | Options | Preferences
Select radio button use a single window for editing all posts.

This works correctly if a post is started, but the post and title are empty, a new window is created.

**Comment by nvella** [comment]
I can confirm that this bug is still present.

**Comment by ranjanjharavi** [comment]
Hi @nvella, I would like to work on this one, May I? If yes, then please assign it to me. 😃

**Comment by nvella** [comment]
Sure @ranjanjharavi! 👍

**Comment by nvella** [comment]
Fixed in #875
