### ISSUE TITLE
Improve Smiley Feature

### ISSUE THREAD

**Issue by ibonobo** [OpenLiveWriter/OpenLiveWriter#308]
As it stands, inserting a smiley uploads a new smiley to your blog. That is rather inefficient, as smileys are not reused and even though these GIFs take little storage space, it would make more sense to have them reused and reusable.

In WLW I would always install the smiley plugin by Rahul Soni (rahulso@ms http://blogs.msdn.com/b/rahulso/) which had the MSN & Yahoo smileys predefined and also allowed defining custom smileys. It would be great if this functionality was included in the main program either as an option or replacing the "hardcoded" ones.

**Comment by nvella** [comment]
I'll close this in favour of #370 - emojis would be the way forward on this in 2019.
