### ISSUE TITLE
Live Writer do not show editing theme when cuts are enabled

### ISSUE THREAD

**Issue by Crypt32** [OpenLiveWriter/OpenLiveWriter#31]
I'm using a custom weblog engine that implements Metaweblog API. Main blog post view uses cuts and shows only excerpts in the paged view. Live Writer (Windows and Open) download and do NOT show downloaded theme. When I disable cuts (and main blog feed shows full posts), Live Writer shows editing theme.

**Comment by RobDolinMS** [comment]
Thanks @Crypt32 - Seems like this is an opportunity to leap Open Live Writer ahead of Windows Live Writer.  Do you know of other blogging platforms that implement cuts for folks to test a potential fix against?

**Comment by Crypt32** [comment]
I started to use cuts few months ago, but WLW was configured long time ago and don't know if this was an issue previously. Strange is that both writers show progress on theme download and do not complain about anything.
What I noticed that when cuts are disabled, download process shows "download support files" and this doesn't happen when cuts are enabled.

I think, many blogging platforms support cuts. WordPress, DasBlog definitely support them.

**Comment by martinwoodward** [comment]
@Crypt32 - if you want to start digging into this issue, if you fire up Visual Studio with the writer solution and have it running in debug mode during the import, you'll likely run into a bunch of errors that get supressed during the release build that will help you identity where to start looking.

**Comment by Crypt32** [comment]
I'm not that experienced developer, but I can try. Not sure what should I do with errors.

**Comment by martinwoodward** [comment]
If you have an example of a blog where you have cuts enabled let us know, I'm not that sure what you mean by "cuts" sorry (I'm mostly a MoveableType user so we probably don't have them)

**Comment by Crypt32** [comment]
For example, my own weblog: http://www.sysadmins.lv/blog-en/default.aspx
main page feed displays only excerpts. In order to read the full article you have to open that article. This is what I call "cuts".

**Comment by Crypt32** [comment]
Follow up: I temporarily disabled cuts on my website, launched OpenLiveWriter and refreshed the theme. Now it downloads and show up in the editor.
Deleted blog account and added back from scratch. The theme downloaded successfully.
Enabled cuts back and attempted to refresh the editing theme, refresh failed. Deleted and added back blog account -- theme is not updated. This definitely is a bug.

**Comment by nvella** [comment]
Seems to be similar to #548, just patched whilst working on static site gen support. OLW will attempt to navigate to the post in the event that it can't find the post content, which seems like it'd work in most cases. I'll close this issue once there's a merged PR.

**Comment by nvella** [comment]
Fix included in #844.
