### ISSUE TITLE
Spell Checkk & One other Question

### ISSUE THREAD

**Issue by JoniWebb** [OpenLiveWriter/OpenLiveWriter#311]
First, this is most fabulous thing you all did!  Major thanks!!!
Wondering,is there spelll check now?
Also - one question, I know you are always tweaking the program, but should I redownload the program for updates or is that automatically done when you post?  Confused about that.  
Thanks in advance!
Joni

**Comment by ScottIsAFool** [comment]
Spell check is coming shortly. And the app will auto update, you shouldn't need to do anything. If you launch the app and there's an update, it will download it and the next tine you launch the app it will have been updated.

**Comment by rkingett** [comment]
I think that you need to download it again from the website when they post.
I did not see an automatic updates option.

Robert Kingett*, Journalist <https://blindjournalist.wordpress.com/resume/>*

*My Patreon* <https://www.patreon.com/blindwriter>

*Other ways to contact me*
<https://blindjournalist.wordpress.com/contact-this-blogger/>

**Comment by ScottIsAFool** [comment]
Downloading again from the website is the quickest way to update, yes, but you don't *have* to do that.

**Comment by rkingett** [comment]
How do we enable the update option or what are the other ways of updating?

Robert Kingett*, Journalist <https://blindjournalist.wordpress.com/resume/>*

*My Patreon* <https://www.patreon.com/blindwriter>

*Other ways to contact me*
<https://blindjournalist.wordpress.com/contact-this-blogger/>

**Comment by ScottIsAFool** [comment]
There's nothing to do, it already does it. The other ways of updating are, as mentioned, download the installer and run it again.

**Comment by JoniWebb** [comment]
So - to reiterate - when I open Own, on my computer - it will update automatically?  No need to download it again?  thanks again.  Y'all are the best!

**Comment by rkingett** [comment]
I think the above poster meant we needed to get the file from the website
but I did not get what he was trying to say. I don't think that writer has
an auto update function but when you grab the latest setup file and run it,
it will upgrade the current version to the latest version.

Robert Kingett*, Journalist <https://blindjournalist.wordpress.com/resume/>*

*My Patreon* <https://www.patreon.com/blindwriter>

*Other ways to contact me*
<https://blindjournalist.wordpress.com/contact-this-blogger/>

**Comment by kathweaver** [comment]
Actually what @ScottIsAFool said is correct (unless you turn the feature off), Open Live Writer does an Autoupdate,  So once a new release is created, there is no user intervention.  I think the only way to know for sure is to look at the About page to know if it's been updated -- something that has been debated.
