### ISSUE TITLE
I don't get an e-mail when I post in open live writer

### ISSUE THREAD

**Issue by anserq** [OpenLiveWriter/OpenLiveWriter#313]
I made the changes on blogger, to send myself an e-mail. With windows live writer it was working fine. Once I started using open live writer, it's not been sending me an e-mail once i publish a post. I posted in the blogger forums, and they said to take this issue to the open live writer people. I already made sure I had the settings right in blogger.

**Comment by ScottIsAFool** [comment]
Is the post showing on your blog? If it is, then there's nothing more Live Writer has to do, it should be Blogger that is sending the emails, not Live Writer.

**Comment by anserq** [comment]
Oh wow interesting. So I should go back to blogger, and tell them that. Thanks for your input :)

**Comment by ScottIsAFool** [comment]
I believe so, yes. We publish the post, but it's Blogger themselves who actually send the email.

**Comment by anserq** [comment]
Okay
