### ISSUE TITLE
Chocolatey Package?

### ISSUE THREAD

**Issue by EdBlankenship** [OpenLiveWriter/OpenLiveWriter#314]
Will Open Live Writer have an official Chocolatey package published?  Thanks!

**Comment by ScottIsAFool** [comment]
There already is one https://chocolatey.org/packages/openlivewriter

**Comment by EdBlankenship** [comment]
Thanks @ScottIsAFool for the pointer.  It's not coming up in search results on the Chocolatey site.

**Comment by ScottIsAFool** [comment]
Really? That's how I got the link :)

**Comment by EdBlankenship** [comment]
Yikes!  Oh well  :face palm:

**Comment by gep13** [comment]
>@EdBlankenship said....
Thanks @ScottIsAFool for the pointer. It's not coming up in search results on the Chocolatey site.

Agreed, the search worked fine for me as well.  Can you confirm that exact steps that you are following?  If there is an issue with chocolatey.org we (the Chocolatey Team) can take a look at it.

Thanks!
