### ISSUE TITLE
May be a Blogger issue

### ISSUE THREAD

**Issue by jerrymills** [OpenLiveWriter/OpenLiveWriter#320]
I wanted to check with you first though as this may be an issue with Open Writer not being recognized fully when publishing.  I am able to publish from Open Writer to my blog no problem, but after publishing the post does not carry over to my google plus page.  If I publish directly from Blogger's dashboard it does carry over to my Google+ page so I know I have the permissions set properly.  Is there something in the publishing process from Open Writer that needs to "communicate" with Blogger to trigger this sharing activity to Google+?
In case you want to see:  http://jerrymills.blogspot.com/ 
On Google+  https://plus.google.com/b/116394054329402166307/ 
The only one that passed over to google plus was the one from the blogger site...

Jerry Mils

Adding to this.  I have another blog that I experiment with to compare with Blogger.com.  It is a WordPress blog at https://jerrymills.wordpress.com/  and I ran a similar test from Open Live Writer to that blog.  It works perfectly.  When publishing from Open Live it does in fact carry the post over to my Google+ page.  This looks to me to be some sort of authentication issue on Blogger.com but still not sure if it can be fixed on your end or if Blogger.com needs to be involved.  (doubtful they will be too excited to help though)

One thing I noticed is that I cannot use my regular user ID and password for the blogger.com when configuring within Open Live.  It appears you plug in some sort of hex string.  When I try to add the blogger.com account with my own username and password it says it is invalid.

**Comment by nvella** [comment]
I'll have to close this issue as Google+ has been shut down. Apologies we didn't get around to this in time.
