### ISSUE TITLE
ArgumentNullException when getting recent posts on empty blog

### ISSUE THREAD

**Issue by humbertoc26** [OpenLiveWriter/OpenLiveWriter#323]
I have a new blog on blogger with no posts or pages. 
When I go to "File"->"Open local draft" or "File"->"Open recent post" and on the "Open" dialog->"Open from:" list I select the item on the list with the name of my blog account 
Then I get the Unexpected Error->ArgumentNullException
![image](https://cloud.githubusercontent.com/assets/3011761/12463346/e8e886c8-bfba-11e5-9653-418af11cd1dc.png)

**Comment by ScottIsAFool** [comment]
I believe this will be fixed with the next release. To be sure, could you post your log file, it's located at %localappdata%\openlivewriter

**Comment by humbertoc26** [comment]
[Open Live Writer.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/98160/Open.Live.Writer.txt)

**Comment by ScottIsAFool** [comment]
Thanks, looks like it hasn't been fixed. I've just submitted a fix for this though, so should still hopefully be fixed in the next release
