### ISSUE TITLE
Suggestion : Add Writemonkey Plugin

### ISSUE THREAD

**Issue by win7guru** [OpenLiveWriter/OpenLiveWriter#325]
I would like to suggest you add Writemonkey as a plugin for OpenLiveWriter

>The program can be found here http://writemonkey.com/
The program is referenced in this SuperUser post http://superuser.com/questions/233269/is-there-a-way-to-use-markdown-in-microsoft-live-writer

**Comment by ScottIsAFool** [comment]
If it's for providing Markdown support, then that is coming soon and actively being worked on. Is that what this would be for?

**Comment by win7guru** [comment]
That is correct.  Will you be supporting tables and other GFM syntax?

**Comment by ScottIsAFool** [comment]
Not sure, best check with the dev who's adding the feature. This can be done (and tracked) at #11
