### ISSUE TITLE
Typographical error in FAQs

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter#33]
See https://github.com/OpenLiveWriter/OpenLiveWriter/wiki/Frequently-Asked-Questions-(FAQ)

In:

Q: How can I support this effort?

A: Here are a few ways you can support the Open Live Writer effort:
•Use the product
•If you like it, tell your friends
•If you have suggestions, tell the volunteer team
•Raise and issue or contribute code at GitHub 

Last bullet point should be "Raise an issue"

**Comment by martinwoodward** [comment]
Fixed - many thanks!
