### ISSUE TITLE
Email posts from Blogger

### ISSUE THREAD

**Issue by KiwiDon** [OpenLiveWriter/OpenLiveWriter#332]
When posting from OLW my Blogger does not forward emails of the post to the listed addresses. I am using the latest OLW downloaded and installed today 25/1/16.

**Comment by kathweaver** [comment]
This is a duplicate of #313 -- Open Live Writer can't send an email -- it should be coming from blogger.

**Comment by KiwiDon** [comment]
Thanks I am still trying to find my way round.

**Comment by kathweaver** [comment]
Absolutely no problem!  Thanks for closing.
