### ISSUE TITLE
Typepad blog themes are not working correctly

### ISSUE THREAD

**Issue by kathweaver** [OpenLiveWriter/OpenLiveWriter#34]
I have two blogs with the same theme:

http://blogs.kweaver.org/cs/ and http://blogs.kweaver.org/blog/

When I enable the theme in OpenLiveWriter I get a blank page, and cannot type on the page.  However, can see HTML in source tab and can edit HTML,  Once I remove the theme from OpenLiveWriter can see and edit post.

See http://screencast.com/t/JxXPiutKZr for a video showing the error.

**Comment by kathweaver** [comment]
I think we can close this but document this somewhere as a known feature.  I think the issue is with the Theme itself and not with Open Live Writer.

The theme causing the problem is a Nimble Design labs theme.  When I changed to several other different themes I could not duplicate the issue.

**Comment by RobDolin** [comment]
Thanks for digging into this @kathweaver and helping to identify the scope of impact as possibly limited to a specific theme.  Per your previous comment, I'll close this issue, but if you (or others) find it impacts more than a single TypePad them (or if that theme is rather widespread), please re-open.
