### ISSUE TITLE
Still unable to use Blogger

### ISSUE THREAD

**Issue by scrappinginontario** [OpenLiveWriter/OpenLiveWriter#342]
I am still unable to use OpenLiveWriter using a blogger account.  Get the same error about incorrect username and password.

**Comment by ScottIsAFool** [comment]
Can you confirm what version of Live Writer you're using (it should be 0.5.1.4). Also, when adding, are you using the Google Blogger option on the first page of the add account wizard?
![image](https://cloud.githubusercontent.com/assets/1658896/12713044/3f56c648-c8c4-11e5-88f2-3f0b5f655356.png)

**Comment by scrappinginontario** [comment]
Thank you so much for your help!  It's working now.  I SO appreciate your help!
