### ISSUE TITLE
Allow to install without configuring blog accounts

### ISSUE THREAD

**Issue by paulomorgado** [OpenLiveWriter/OpenLiveWriter#35]
I use Writer without any configured account.

It's a pain to have to configure an account just to be able to install Writer.

**Comment by panjkov** [comment]
So, if the blog has not been configured, main window should open without any theme configured? From technical standpoint, would the modification to ApplicationLauncher.cs be sufficient to accomplish that?

**Comment by panjkov** [comment]
I played around with source, and concluded that more than "hacking" applicationlauncher.cs is needed. :)

**Comment by jasonhorner** [comment]
Agreed this is a pain though minor

**Comment by zosoro** [comment]
I have solved this the simple way:

1. backup registry settings HKEY_CURRENT_USER\Software\Microsoft\Windows Live\Writer\
2. backup local themes folder c:\Users\vali\AppData\Roaming\WindowsLiveWriter\blogtemplates\

When installing Windows fresh, i just open WLW once, let it write the folder in the registry and on the harddrive, and then close it, copy the teme, import the .reg and i am done.

**Comment by JoniWebb** [comment]
Could you explain this in plainer language for idiots?  Thanks.  Sorry  to bother you.

**Comment by zosoro** [comment]
I have my blog accounts configured in WLW about 3-4 years back. 

Then run regedit.exe, made a copy of the keys and settings in HKEY_CURRENT_USER\Software\Microsoft\Windows Live\Writer\
and of the local folder c:\Users\vali\AppData\Roaming\WindowsLiveWriter\blogtemplates\

Now, when i install a new Windows (new SSD, new laptop), i just install wlw, run it once up to the point of blog accounts, close it, and then import the settings saved and copy the blog templates and i am good to go.

**Comment by JoniWebb** [comment]
Thank you...haha.  I'm so out of my league here.  Need to stick to interior design.

**Comment by ScottIsAFool** [comment]
@zosoro If you ever need to do that again, I'd recommend my backup/restore utility, rather than manually copying files and registry bits :) http://wlwbackup.codeplex.com/

**Comment by paulomorgado** [comment]
That doesn't get you past the fact that you need to have, at least, one blog configured to use it.

**Comment by JoniWebb** [comment]
Scott - I downloaded your backup/restore - everything is great but when I go to backup or restore my posts - you can't see them in documents - even though the posts are there.  I'm windows 10 - is that a problem?  any tips to get it to see the posts so I can back them up ?

**Comment by willduff** [comment]
I'd need to look at the code further to investigate, but my hunch is that this feature is not feasible unless we do a very large re-architect of the code. Given the effort involved and the little gain that we get from it, I'd recommend you just set up a free blog on Wordpress.com, Blogger.com or any other free provider and use that instead to get past the initial login.

It sounds like most of you would just like better migration between installs of Open Live Writer and Windows Live Writer and I definitely agree that would be great! We are already tracking that with issue #100.

**Comment by nedtwigg** [comment]
Just an idea - maybe you could mock out a very simple blog server and embed it into the app, and connect to it over localhost when the user picks "None".  Record whatever stuff that Wordpress.com sends you, and replay it as a mock for a real server.

**Comment by willduff** [comment]
@nedtwigg Yes, I thought of that a little after my last post. This could potentially be solved using the [Null Object](https://sourcemaking.com/design_patterns/null_object) design pattern (i.e. a NullBlogClient).

>Sometimes a class that requires a collaborator does not need the collaborator to do anything. However, the class wishes to treat a collaborator that does nothing the same way it treats one that actually provides behavior.

Still, it's easy to add a free blog provider to get past the initial screen, so this is still low priority.
