### ISSUE TITLE
i cannot publish article on blogger

### ISSUE THREAD

**Issue by moinebs** [OpenLiveWriter/OpenLiveWriter#353]
hello
Since a long time i cannot publish article on blogger with OpenLiveWriter
When I try to publish an article  i get this error

http://i.imgur.com/Po0N60a.png

pls try to fix this problem

**Comment by ScottIsAFool** [comment]
You need to re-add your blog to Live Writer and choose this option when adding it:
![image](https://cloud.githubusercontent.com/assets/1658896/12824195/f873bcb2-cb67-11e5-9102-ccda8de8a596.png)

**Comment by moinebs** [comment]
yes i ' m already used that option
https://cloud.githubusercontent.com/assets/1658896/12824195/f873bcb2-cb67-11e5-9102-ccda8de8a596.png
--------------------------------
what you mean re-add your blog to Live Writer 
this my first time using OpenLiveWriter

**Comment by ScottIsAFool** [comment]
Sorry, when you go to add a new blog, you should be selecting that specific Google Blogger option, it will then give you a sign in button like this 
![image](https://cloud.githubusercontent.com/assets/1658896/12824591/d3646d7a-cb69-11e5-8e11-8123440c280c.png)
Once you've signed in (it will launch a browser window), you can then select your blog.

**Comment by moinebs** [comment]
When you press the button, nothing happen
https://lh3.googleusercontent.com/-FzLbcVbg7ZE/VrOUC9OFh_I/AAAAAAAAALU/ZAEIfWG8hYM/w433-h360/problem.gif

**Comment by moinebs** [comment]
i just downloaded OpenLiveWriter right now
that mean i m using the latest version

**Comment by moinebs** [comment]
plssss help!!!

**Comment by kathweaver** [comment]
Yes, you are using the latest release.  It should have blogger support.  Follow the directions above and if it doesn't work, provide us your log.

**Comment by AMMOUN123** [comment]
HI
I also have a problem to login to my Blogger!!

I follow the steps above, and when i click the sign in button it takes me to google chrome : 


![olw1](https://cloud.githubusercontent.com/assets/17080515/12842261/f14d010c-cbf1-11e5-9fb2-168ea8918837.PNG)

When i click "Allow" i get an error message : 


![olw](https://cloud.githubusercontent.com/assets/17080515/12842281/1728b42a-cbf2-11e5-940a-370f7fffbcae.PNG)



- I use windows 7 
- Allow less secure apps is turned On

Please help, thanks

**Comment by ScottIsAFool** [comment]
Can you please provide your log file, this can be found at %localappdata%\openlivewriter

**Comment by AMMOUN123** [comment]
what is exactly the name of the file please?

**Comment by ScottIsAFool** [comment]
It is called Open Live Writer.log. If you're not showing file extensions, it will just show as Open Live Writer, but will look like a text file.

**Comment by AMMOUN123** [comment]
Voila :)


[Open Live Writer.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/118901/Open.Live.Writer.txt)

**Comment by moinebs** [comment]
any help

**Comment by kathweaver** [comment]
@moinebs Please send us a log.

**Comment by moinebs** [comment]
@kathweaver 
[Open Live Writer.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/120659/Open.Live.Writer.txt)

**Comment by AMMOUN123** [comment]
Is there anyone here??!!

**Comment by ScottIsAFool** [comment]
Looking at the log file from @moinebs, it still looks like the wrong you're using the wrong blog authentication type (not using Google Blogger option on the first screen).

@AMMOUN123 Can you confirm what version of Live Writer you have installed? To do this, go to %localappdata%\OpenLiveWriter and there should be a folder called app- and then some numbers, can you tell me what you have there? Looking at your log file, the error that's showing in there I thought was fixed already.

**Comment by AMMOUN123** [comment]
Thanks for your replay @ScottIsAFool  :)

I have this version : app-0.5.1.4

**Comment by moinebs** [comment]
@ScottIsAFool 
i m using Google Blogger option
this is my screen record ... take a look

https://lh3.googleusercontent.com/-FzLbcVbg7ZE/VrOUC9OFh_I/AAAAAAAAALU/ZAEIfWG8hYM/w433-h360/problem.gif
