### ISSUE TITLE
Transferring categories and tags from Windows Live Writer

### ISSUE THREAD

**Issue by rfidler** [OpenLiveWriter/OpenLiveWriter#355]
In Windows Live Writer I had many categories which I applied to texts before posting to Blogger. But in Open Live Writer these categories don't appeal and I see means for adding categories. Same for tags. Under Blog Capabilities in OLW, it says my blog does not have Categories, New Categories, Multiple Categories, Hierarchical Categories, or New Categories Inline. So how do I get OLW to recognize the categories that I already have on my Blogger posts, and how do I add categories if needed?

**Comment by ScottIsAFool** [comment]
Hi, thanks for raising this. Categories will be returning with the next update.

**Comment by rfidler** [comment]
Thanks, looking forward to it. And I don't understand how Tags work. In OLW, I am offered various Tags services. Does this mean I need to apply to one or another of those listed before accessing Tags in OLW?

**Comment by ScottIsAFool** [comment]
I wouldn't bother with those in all honesty. The new version of Writer will be along soon. In the meantime, you may just need to add categories manually from the blogger interface.

**Comment by rfidler** [comment]
OK. Thanks. And thanks to all of the team for providing this open source alternative to Windows LW. I really depend on LW when it comes to preparing posts for my Blogger account; sure makes it easier!
