### ISSUE TITLE
OLW Twitter feed

### ISSUE THREAD

**Issue by SteveP-UK** [OpenLiveWriter/OpenLiveWriter#356]
Hi Folks. Thanks for all you're doing to get OLW up and running - I'm sure I speak for many, when I say it's much appreciated. My question is _not_ a technical one: Who's monitoring the OLW Twitter feed? I posed a question there a week-or-so ago and haven't had a reply. Thanks. ^Steve

**Comment by ScottIsAFool** [comment]
Ah, I need to adjust my search then, I've been searching on #OpenLiveWriter, I guess I should change that to just OpenLiveWriter.

**Comment by SteveP-UK** [comment]
Cheers Scott.Looking forward to see the next release of OLW.
