### ISSUE TITLE
Link Options

### ISSUE THREAD

**Issue by tubbystar** [OpenLiveWriter/OpenLiveWriter#360]
Firstly, thanks for resurrecting Live Writer, it's REALLY appreciated.

Under the Picture Tools Format menu, there is Link Options button. Is it possible to have the option of Open in New Window enabled by default?

**Comment by ScottIsAFool** [comment]
Once you've changed the setting to open in new window and closed that dialog, click the Set to default button next to the Link options one and it will indeed then be your default option.

**Comment by tubbystar** [comment]
Great, thank you!
