### ISSUE TITLE
Nightlies

### ISSUE THREAD

**Issue by SteveP-UK** [OpenLiveWriter/OpenLiveWriter#366]
Hi Folks. Thanks for keeping the LW flag flying!

Is there such a thing as 'nightly builds' where we can test early versions?

Thanks

Nighty night!

Steve

**Comment by kathweaver** [comment]
Yes, there is a registry setting for that.

**Comment by SteveP-UK** [comment]
Cheers! Where do I get the setting from?

Regards

Steve

**Comment by kathweaver** [comment]
HKEY_CURRENT_USER\SOFTWARE\OpenLiveWriter

**Comment by ScottIsAFool** [comment]
HKEY_CURRENT_USER\SOFTWARE\OpenLiveWriter\Updates

Then you need to create a dword key for CheckForBetaUpdates 1 = beta, 0 = regular.

I have a plugin that will let you switch between them coming at some point.

**Comment by SteveP-UK** [comment]
Kathleen. OK thanks, this is helpful. What changes do I need to make to the
registry? Is there something I can read that explains the expected change
in behaviour of OLW if I'm on 'nightlies' (in terms of how it updates).

Is all this common knowledge? Have I fallen asleep at some point? 😊

Cheers

**Comment by SteveP-UK** [comment]
Cheers Scott

I'm away from the PC for a while where OLW is installed.

I'm currently running 0.5.1.4 on it, will switching things to include beta
updates give me a more up-to-date/more functional version?

Thanks for all your help.

Steve

**Comment by ScottIsAFool** [comment]
I'm not 100% certain. @martinwoodward?

**Comment by martinwoodward** [comment]
It should update to the latest build from the CI server so does give you a more up-to-date version.  "More functional" is harder to say, it might have more features but one you rely on might get accidentally broken.  We'd hopefully spot that and get it fixed quickly but OLW is only going to check once per day that you restart the app.

Basically, know that if you are on the CI builds then you might get broke.  The good news is that if that happens, uninstalling the app (making sure the reg keys get deleted) and installing the latest version from openlivewriter.com will get you back onto the stable build if something goes really badly wrong.

Having a certain amount of folks running on the latest build would be really helpful in case something got broke that we wouldn't have otherwise noticed, but please only do it if you are comfortable with living on the edge a little more.

**Comment by SteveP-UK** [comment]
Cheers Martin

I have a lot of free time on my hands so I'm happy to try slightly less
stable versions. ☺

I've made the changes in the Registry as per @ScottIsAFool 's advice and
I've relaunched OLW a couple of times. AFAIK it's still running the latest
stable build. Does the build number change if I download a nightly? How
would I know if a Nightly had been installed?

Is there a later nightlies than the current stable build?

And finally, does a changelog exist for the Nightlies?

Thanks in advance for your help - and for all the good work you're doing.

Steve

**Comment by ScottIsAFool** [comment]
Do you have spell checker? If so, you have the current latest build.

**Comment by SteveP-UK** [comment]
Nope!
😕

**Comment by SteveP-UK** [comment]
Scott, I've tried tweaking the registry on another PC with OLW latest stable build installed. That device is not showing a spell checker either after restarting it (and hoping an update takes place). I wanted to check that I'd tweaked the registry correctly. I've attached a screen shot of my registry after changing it - have I followed your previous suggestions correctly? Appreciate your help.
![screen_grab001](https://cloud.githubusercontent.com/assets/16260144/12927761/cb6fd3a6-cf61-11e5-9943-795634360649.PNG)

**Comment by ScottIsAFool** [comment]
I'm going to have to refer to @martinwoodward on this one again I'm afraid.

**Comment by SteveP-UK** [comment]
Cheers Scott

I'm not sufficiently competent to sus this one. Having checked various
folders related t OLW, I can't see any newer builds. Hoping that
@martinwoodward <https://github.com/martinwoodward> can advise me here.
Thanks all.

**Comment by willduff** [comment]
@SteveP-UK  Problem is that we haven't bumped the version number. Right now the nightly version number is the same as the public release version number, so your local copy thinks its already up to date and skips re-downloading the same version. Let me see if its safe to bump the version number now...

**Comment by willduff** [comment]
@SteveP-UK If you want to go install the nightly directly, the latest nightly is always at this URL: https://olw.blob.core.windows.net/nightly/Releases/OpenLiveWriterSetup.exe

**Comment by SteveP-UK** [comment]
Cheers Will

**Comment by SteveP-UK** [comment]
Cheers Will

I didn't know that - thanks!

Downloaded perfectly and I now have spell check too!

Anything else worth looking out for in this build that you want tested?

Thanks

Steve

**Comment by willduff** [comment]
I am mainly focused on fixing Google Blogger bugs, so if you use Google Blogger just let me know if you have any issues posting or retrieving posts from your blog. I just re-wrote Google Blogger support and there were some embarrasingly obvious bugs and missing functionality in the first version. I've got two more fixes coming (pull request #358 and #371 and then it will be pretty solid.  If you go look at issue #224 and #247, I have fixes out but I'm looking for volunteers to test. I have instructions and links to custom builds with the private fixes for each one if you're looking for something to do :smiley:

Also, I just bumped the version to 0.5.1.5. You should get auto-upgraded after you restart Writer a couple times.

**Comment by willduff** [comment]
One more thing to note, if you do go test those builds out that I linked to in issues #224 and #247, and you leave CheckForBetaUpdates = 1, then you'll actually get auto-upgraded to the nightly because I bumped the version. So, if you want to test those builds properly, you'll want to set CheckForBetaUpdates = 0 temporarily.

**Comment by SteveP-UK** [comment]
Hey Will. Mines just bumped to 0.5.1.5 - yay! :)

Happy to help with any testing of stuff - loads of time on my hands. Just
tell me what you want tested and I'll put some time aside to do this. Happy
to help and to move OLW forward!

Steve

**Comment by SteveP-UK** [comment]
Hi. OK @WillDuff, I've reverted 'CheckForBetaUpdates' in the registry back to '0' whilst trying out test builds. If you want me to test issues #224 and #247, am I OK to test these issues on version 0.5.1.5?
As software testing is not a natural part of my DNA, are there any disciplines I should follow to ensure the results/feedback are as meaningful as possible for you?

Cheers

Ste

**Comment by kathweaver** [comment]
There are test plans in the code that you might find helpful.  And if you want to enhance them, feel free.  Love to have some help.

Basically check lists so you drill down deep enough.

**Comment by SteveP-UK** [comment]
Hey @willduff and all. 
0.5.1.5 would always throw up an error if I exceeded '500' as the number of blogs I wanted to retrieve

In the meantime, on your advice, I've replaced the 0.5.1.5 version with your test version from 
https://ci.appveyor.com/api/buildjobs/eqm9fps0deaxkk5k/artifacts/Releases/OpenLiveWriterSetup.exe (it shows as 0.5.1.4) and carried out numerous tests
to check #247 and I can confirm that I can use '3000' as my retrieve limit and it pulls them all down without a problem. It also included my first blog back in 2004 - never could do that with WLW. :)

I could even choose 'All' and it allowed me to retrieve some very old posts.and allow me to edit them.

Great news (for me at least)!

I'm using a relatively new Windows 10, 64 bit machine.

Hope this is helpful.

Steve

**Comment by SteveP-UK** [comment]
Hey @kathweaver I wasn't sure if your shout out was to me, but I'm not a Software Designer so I wouldn't know where to start with Test Plans - but happy to help in as many other ways that moves us all forward.

Steve

**Comment by SteveP-UK** [comment]
Hi All. I'm testing issue #224 as we speak. 

My timezone on my PC is: UTC - Dublin, Edinburgh, Lisbon, London.

It's 14.20 here and I've created a test post scheduled for about an hour's time at 15.30. I'll report back later as to what happens. 

I'm using the OLW build from https://ci.appveyor.com/api/buildjobs/eqm9fps0deaxkk5k/artifacts/Releases/OpenLiveWriterSetup.exe labelled as 0.5.1.4

Fingers crossed!


Steve

**Comment by willduff** [comment]
@SteveP-UK Thanks Steve. I'm curious - is your Google Blogger blog timezone also set to UTC? You can find it by going to http://www.blogger.com, find your blog overview, click **Settings** > **Language and formatting** > **Time Zone**

**Comment by SteveP-UK** [comment]
Hi @willduff - thanks, I should have checked that too! It's set for GMT - London

**Comment by kathweaver** [comment]
A testplan is merely a checklist to make sure you check everything.  They are in a folder of the source called testplans.

**Comment by SteveP-UK** [comment]
Thanks for clarifying things Kathleen

Steve

**Comment by kathweaver** [comment]
Testplans came in quite handy in my last job  -- and primarily what I did for them.  We were able to get a mobile app to market.  They were useful because we used them to get all the parties to come to consensus -- both the developers and the QA team.

It's come in handy here, because I've found some bugs developing them.  And then anyone can follow behind me.

**Comment by kathweaver** [comment]
can we close this since we answered it?

**Comment by SteveP-UK** [comment]
I'm happy to close this one
