### ISSUE TITLE
no automatic email is sent when publishing a post 

### ISSUE THREAD

**Issue by chbwien** [OpenLiveWriter/OpenLiveWriter#368]
If you have set an email-adddress that should receive the post as email for any new published post, using OpenLiveWriter will not trigger an email. That worked with WLW very well. #

**Comment by kathweaver** [comment]
See issue #271 
  that would have to be a function of the blogging software.

**Comment by kathweaver** [comment]
Can this be closed since it was answered? @ScottIsAFool
