### ISSUE TITLE
Offering Help

### ISSUE THREAD

**Issue by SteveP-UK** [OpenLiveWriter/OpenLiveWriter#376]
@willduff and others: Thanks for bumping us all to [0.6.0.0](www.openlivewriter.org). All the essentials seem to be working fine on both my Windows PCs (Win10 32bit + WIn10 64bit).
:) :) :)

It may be my imagination, but the app seems to load a lot quicker on my two devices (wishful thinking?)

Thinking about moving us forward, is there any particular function you would like me to test out for you? I can't code, so I think I'm probably more helpful testing out features as an 'end user' on the main app or when the time comes, any plug-ins.

Cheers
Steve

**Comment by kathweaver** [comment]
What I do, and you can do too, is look at the pull requests and test them when they reach a point of completion.

You can also help by blogging, writing documentation and other functions developers don't like to do.

**Comment by SteveP-UK** [comment]
Hi @kathweaver - thanks for the pointer but I think you might be over-estimating my competence :)

If you recall, I'd mentioned before that I'm not from a software/software development background - I'm simply an EEU* *Enthusiastic End User :)
I suspect that you guys here are very familiar with GitHub, but for me, it's all new and I only discovered its existence when the OLW got started. For a newby, it's a nightmare to navigate through if you're a novice - there are so many things that one could click on - and the language is clearly not designed for a non-techy like me. Jargon such as 'Pull Request' doesn't shout 'test me' (to me) and there are plenty of other examples - 'pulse', 'branches' etc.  I'm the guy that thinks 'fork' means something completely different :)

When you suggest: "look at the pull requests and test them when they reach a point of completion", I've no idea what that means. Sorry! 

So, I want to be helpful, but I think you guys are going to have to be gentle with me and be (even) more specific with your suggestions. To use your example of adding to the Blog - I'm happy to do that, but there has been an assumption I know the login details for this - it's certainly not obvious how I add to the Blog at the moment without these credentials

I've got massive respect for all the hard work you folk are doing on our behalf, but if would like me to help, may I ask that you treat me like an idiot with GitHub (and maybe other things too!) and assume nothing in terms of my competence in this arena (or just say 'Steve - test x, y and z)
Hope this message is received in the spirit it was written - just trying to do my bit to make OLW the best blogging tool ever.

Thanks for reading.

Steve

**Comment by kathweaver** [comment]
Actually this is helpful, because I have been writing documentation, and it's good to know what people need to know to help.

Have you read anything of the blog entries I've written or any of the other documentation?  If you see typos, etc. raise an issue.

And so far, you have raise an issue down.

**Comment by SteveP-UK** [comment]
Cheers Kathleen

Thanks for understanding.

Yes, read your blogs. All very helpful, especially the part about getting
stuff from GitHub.

I'm getting there slowly.... 😊

Regards

Steve

**Comment by kathweaver** [comment]
I've got a new pull request for a blog post that will help.

**Comment by kathweaver** [comment]
Can we close this since I've put documentation on the website to help this?

**Comment by SteveP-UK** [comment]
HI @kathweaver Yes, sure, but if you are encouraging us to contribute to the blog, we'll need the details of how to log in. Thanks for all your doing for us.

**Comment by kathweaver** [comment]
Well, I created a blog post about it and it's in a pull.  You'll need to learn more git and GitHub.

**Comment by SteveP-UK** [comment]
Thanks for clarifying. I hadn't realised that I'd need to learn more about
GitHub to do this. That's not for me for the reasons I've explained a few
times in previous posts here.

**Comment by RobStand** [comment]
This would be a good conversation to have on Gitter. Closing this as there's nothing to resolve, strictly speaking. :)
