### ISSUE TITLE
CI badge is private

### ISSUE THREAD

**Issue by jublo** [OpenLiveWriter/OpenLiveWriter#38]
https://ci.appveyor.com/project/ScottHanselman/openlivewriter

**Comment by martinwoodward** [comment]
D'oh - @shanselman we forgot to make the CI build public when we shipped. Should I create a new public one from the .NET Foundation side now or can we quickly set yours public?

**Comment by shanselman** [comment]
Fixed.

On Wed, Dec 9, 2015 at 12:59 PM, Martin Woodward <notifications@github.com>
wrote:

> D'oh - @shanselman <https://github.com/shanselman> we forgot to make the
> CI build public when we shipped. Should I create a new public one from the
> .NET Foundation side now or can we quickly set yours public?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenLiveWriter/OpenLiveWriter/issues/38#issuecomment-163390028>
> .
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes
