### ISSUE TITLE
Link Glossary

### ISSUE THREAD

**Issue by SteveP-UK** [OpenLiveWriter/OpenLiveWriter#385]
Hi @ScottIsAFool 

Did you have any thoughts on my suggestion #375 ?

Thanks

Steve

**Comment by ScottIsAFool** [comment]
I saw it, but not had any thoughts on how best to implement it.

Closing this issue as not sure why a new one was opened for this.

**Comment by SteveP-UK** [comment]
Hi Scott. Sorry, I opened another because it's my lack of knowledge on how
to contact you guys individually when it's not an 'issue'. Ive mentioned
before tgat It's not my natural habitat here. Ive tried the OLW Twitter
feed for non issues but never received a reply there.

So, excuse my ignorance, but how do we follow up on stuff when issues
haven't been answered? I'm asking as a non-techy! 😊

Thanks for all you are doing for OLW.

**Comment by ScottIsAFool** [comment]
Do what you did in this issue, but do it in the correct one :) just @ someone, they'll get an email (depending on their notification settings).

**Comment by SteveP-UK** [comment]
Cheers Scott

GitHub 101 😊

So does an issue stay open until all parties are happy to close it? Does
the '@' designation determine who owns the issue?

Is there a way of contacting (say) you, via GitHub but as a sort of PM so
it doesn't appear on the GH site? Just asking.

**Comment by ScottIsAFool** [comment]
The issue will stay open until someone who has the rights clicks the close button. The @ designation doesn't assign the issue, again, that's reserved for people with the correct write permissions. As for PMing, keeping the discussion on github is best because if anyone else wants to join in the discussion, they have all the information available to them.

**Comment by SteveP-UK** [comment]
Thanks Scott. I get it. I recognise the importance of keeping stuff public
so that everyone can contribute. However I do have some observations about
the roll-out of OLW and how non-techies like me can help, that have not
been answered fully - I guess I was looking for a way to ask the following
without posiitioning it as a 'tech issue'. In short, I'm not a user of
GitHub and don't wish to learn it BUT I do have truck loads of experience
as an end-user with the old WLW and PCs in general. I *think* this is
useful to the development of OLW, but I can't seem to find a home here
currently. We've been encouraged to 'jump in' and I really want to, but the
water is just too deep. I realise this is early days in the project and you
guys all have day jobs too to keep you busy. I wonder, should I stick
around trying to stay involved or come back later when there's more for
someone like me to do?

I hope you appreciate my POV. I just want to do my bit for you guys to make
OLW the best blogging app going.

Steve
