### ISSUE TITLE
Constantly crash due to D3DIM700.DLL 

### ISSUE THREAD

**Issue by SunriseFox** [OpenLiveWriter/OpenLiveWriter#387]
问题签名
问题事件名称: BEX
应用程序名:    OpenLiveWriter.exe
应用程序版本: 0.6.0.0
应用程序时间戳:  56bfb5af
故障模块名称: D3DIM700.DLL_unloaded
故障模块版本: 10.0.14267.1000
故障模块时间戳:  56bf223d
异常偏移:   00004040
异常代码:   c0000005
异常数据:   00000008
OS 版本:  10.0.14267.2.0.0.256.48
区域设置 ID:    2052
其他信息 1: e5fc
其他信息 2: e5fcd7b48c8bae644915cd3efbaed325
其他信息 3: 58df
其他信息 4: 58df8a2781d063e9917218ae0b80eaef

关于该问题的额外信息
存储段 ID:   5cf75a344fe7c90df2f41fd4ce9d8832 (116114610630)

It seems to happen whenever you are not operating it. Sorry about the Chinese words.

**Comment by Laronski** [comment]
I'm running v6 and I'm not seeing this issue.
This looks like a good article:
http://www.fixerrorhelps.com/fix-pc-error/how-to-fix-d3dim700.dll-error.html
