### ISSUE TITLE
AtomPub is not on the list of blog providers

### ISSUE THREAD

**Issue by tugberkugurlu** [OpenLiveWriter/OpenLiveWriter#39]
I am not sure if this is really a valid issue but it feels like AtomPub should be inside the blog providers list below:

![image](https://cloud.githubusercontent.com/assets/328122/11697710/cd0f162a-9eb2-11e5-9093-f61244ea4aad.png)

**Comment by gduncan411** [comment]
One issue with the Atom Publishing Protocol not appearing in the list and also issue #40 appears to be with BlogProvidersB5.xml and the xpp flag.
```xml
<provider **xpp:if="version gte &wave2mship;"**>
    <id>D48F1B5A-06E6-4f0f-BD76-74F34F520792</id>
    <name>Atom Publishing Protocol</name>
    <link>http://bitworking.org/projects/atom/</link>
    <clientType>Atom</clientType>
    <postApiUrl>
      <![CDATA[
		http://<atom-service-doc>
		]]>
    </postApiUrl>
    <postApiUrlLabel>ServiceDoc</postApiUrlLabel>
    <reportingKey>zr</reportingKey>
    <options>
      <supportsScripts>Unknown</supportsScripts>
      <supportsEmbeds>Unknown</supportsEmbeds>
      <supportsCustomDate>Yes</supportsCustomDate>
      <defaultView>WebLayout</defaultView>
      <invalidPostIdFaultCodePattern>^404$</invalidPostIdFaultCodePattern>
      <maxCategoryNameLength>200</maxCategoryNameLength>
      <visible>true</visible>
    </options>
  </provider>```

If I remove the xpp: flag I am able to add a Atom Pub Blog

**Comment by timheuer** [comment]
Should be fixed with PR #87

**Comment by ScottIsAFool** [comment]
As #87 is merged in, this can be closed now?

**Comment by gduncan411** [comment]
My vote is: Maybe

While it IS fixed for now, my thinking is that the Version Flag (I.e. xpp) in the XML should likely go as it's going to be a pain to keep up to date (yeah, I should have said that in my original comment, sorry). 

But that could be created as a separate issue to be handled in the future.

**Comment by willduff** [comment]
@gduncan411, I agree, and I think we should remove all of XPP. I opened a new issue #181 with more details.

Thanks guys!
