### ISSUE TITLE
Enable package deployment

### ISSUE THREAD

**Issue by jleivo** [OpenLiveWriter/OpenLiveWriter#404]
Current shared package (.exe) is not deploy-able with package management software (example Puppet). Quick search on squirrel.windows installer shows that it could be deployed as a package if the MSI version is used.
Could both exe and MSI version of installation package be shared?

**Comment by gep13** [comment]
@jleivo have you tried using the Chocolatey Puppet Provider?  There is a Chocolatey Package for OpenLiveWriter that you could use.

**Comment by jleivo** [comment]
I be damned. I was sure I checked that. You are right! This can be closed.

**Comment by gep13** [comment]
:+1:
