### ISSUE TITLE
Adding HTML Code

### ISSUE THREAD

**Issue by DawnL43072** [OpenLiveWriter/OpenLiveWriter#407]
Is there a way to add code like there is in blogger where you can switch from '_compose_' to '_HTML_'? 
When I go into blogger to add the code (i.e. from thumblinky) it ends up changing the font size of most of my post! Only the wording directly above stays the same size. 
thank you

**Comment by ScottIsAFool** [comment]
You mean something other than the Source tab?

**Comment by ScottIsAFool** [comment]
Source tab:
![image](https://cloud.githubusercontent.com/assets/1658896/13432918/83e29016-dfc7-11e5-9091-4d89b7b36833.png)

**Comment by DawnL43072** [comment]
Thank you! I never knew what that was for…

Dawn

 

 

Source tab:
 <https://cloud.githubusercontent.com/assets/1658896/13432918/83e29016-dfc7-11e5-9091-4d89b7b36833.png>
