### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by Resonanz** [OpenLiveWriter/OpenLiveWriter#413]
These is no version number given on the download page.

**Comment by rkingett** [comment]
​Has it updated already?

**Comment by ScottIsAFool** [comment]
@Resonanz You mean something showing the currently available version?

**Comment by Resonanz** [comment]
Yes, exactly.  I have 0.5.1.2. installed but it is not obvious what the latest version is.

**Comment by ScottIsAFool** [comment]
Ok, thanks, I'll close the bug here and raise it for the website.

Also, 0.6.0.0 is the latest, if you go to openlivewriter.org and click install, it will update you to the latest version.
