### ISSUE TITLE
OpenLiveWriter installer sets an incorrect installation date

### ISSUE THREAD

**Issue by harcalion** [OpenLiveWriter/OpenLiveWriter#424]
Version 0.6.0.0, installed on the 11th of March, appears in Programs and features as installed on the 3rd of November (in the future!). The system has all regional settings (including language) set to Spanish (Spain).

**Comment by joshg253** [comment]
I just installed 0.6.0.0 and see today's date listed in Programs and Features.

**Comment by harcalion** [comment]
I have tested in again on another machine and the date is OK, even with non-US locale. I suppose this was just a glitch.
