### ISSUE TITLE
Text narrow down middle of the page

### ISSUE THREAD

**Issue by DarthWaldo** [OpenLiveWriter/OpenLiveWriter#426]
Running Dell XPS 13 and Windows 10.

Text seems to be in a narrow band down the middle of the page.  Will only type a few letters (both title and text) before going to the next line.

**Comment by Laronski** [comment]
What Blogging service [Blogger, LiveJournal, TypePad, WordPress, Etc.] are you using?
Does it happen with the theme turned off?

**Comment by DarthWaldo** [comment]
Blogger.  Turned the theme off and it seems normal.  

Have an Acer Timeline X with Windows 7 and it works fine with theme on.  Thanks for the help!

**Comment by Laronski** [comment]
Must be a dynamic part to the blog theme that's causing the problem.
I think the Open Live Writer team plans to help with theme issues/detection.

You can use Open Live Writer with no theme and it should work fine. 
Here's another link you may find informational; how to change the width of the default HTML template.
     http://bit.ly/Zbh2Iy
