### ISSUE TITLE
Blogger : Null refernce exception - While trying to detect settings for a Blogger blog which has no categories defined.

### ISSUE THREAD

**Issue by nimesh-madhavan** [OpenLiveWriter/OpenLiveWriter#428]
I ran in to this issue while trying to debug Open Live Writer for another issue. Looks like the issue is surfaced to the UI only in the debug builds, in the regular builds, the exception is caught and ignored

![screenshot 1](https://cloud.githubusercontent.com/assets/627928/14020248/55d3aa9c-f1fc-11e5-92ca-6521500a2476.PNG)
![screenshot 2](https://cloud.githubusercontent.com/assets/627928/14020247/55d146ee-f1fc-11e5-836a-6748d8f11616.PNG)
![screenshot 3](https://cloud.githubusercontent.com/assets/627928/14020249/55d3c662-f1fc-11e5-85b5-be8727cee960.PNG)

**Comment by ScottIsAFool** [comment]
Thanks for reporting this, will be an easy enough fix. Locally though, you can always make the change:

var cats = item?.Feed?.CategoryArray?.Select(x => new BlogPostCategory(x.Term));

**Comment by nimesh-madhavan** [comment]
Fixed now.
