### ISSUE TITLE
Categories drop-down layout messy on high DPI displays

### ISSUE THREAD

**Issue by flcdrg** [OpenLiveWriter/OpenLiveWriter#444]
Running on a 4K monitor, the layout looks like this:

![openlivewriter categories](https://cloud.githubusercontent.com/assets/384747/14426525/c0a59ed0-002e-11e6-8a2f-8351b43a336b.png)

**Comment by ScottIsAFool** [comment]
Thanks for reporting this. Yes, we have a number of issues surrounding high DPI usage.

**Comment by flcdrg** [comment]
I just got myself a new laptop so I think I'm probably going to experience a few of these first hand. I'll see if I can submit a few PRs when I get a chance.

**Comment by jongalloway** [comment]
Thanks for the report and fix, @flcdrg!

**Comment by flcdrg** [comment]
Thanks Jon for picking this up.. I'd almost given up hope.
Dave
