### ISSUE TITLE
Build is slow

### ISSUE THREAD

**Issue by flcdrg** [OpenLiveWriter/OpenLiveWriter#446]
The build seems to be recompiling quite a few things even after a full build has just completed.

I think the Bcl packages could be part of this, as well as the MarketXmlGenerator

**Comment by gep13** [comment]
Based on this comment (https://github.com/OpenLiveWriter/OpenLiveWriter/pull/447#issuecomment-285982521) I think this issue can be closed.

**Comment by ScottIsAFool** [comment]
Agreed
