### ISSUE TITLE
Errors building with VS2013 / Dev12 tools - requires .NET 4.5.2 targeting pack installed.

### ISSUE THREAD

**Issue by jthelin** [OpenLiveWriter/OpenLiveWriter#45]
Posting this here mostly for info because it might be useful as FAQ answer for some people.

If you don't have VS2015 (dev14) installed on your Win7 machine, then `build.cmd` will conveniently fall back to using VS2013 (dev12) build tools, but you will still get build errors if .NET 4.5.2 Targeting Pack is not installed. 
For example:
```
warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
```

The managed components in OLW are targeting .`NET 4.5.2`, so you also need the **Microsoft .NET Framework 4.5.2 Developer Pack** installed too even if you have .NET 4.5.2 runtime bits installed on your dev machine. 
Download is available here: http://www.microsoft.com/en-us/download/details.aspx?id=42637

See build log output on Win7 machine before and after installing 4.5.2 Targeting Pack for more details: https://gist.github.com/jthelin/435213878c0b8c1b9451

**Comment by martinwoodward** [comment]
Does the build work for you @jthelin after following these steps?

If so, be a good tip to add in to our developer docs (which need a bit more info anyway).  VS 2015 Community edition is a free download  as well that people can try if they wanted and that's what we use on the build server to generate the release versions.

**Comment by jthelin** [comment]
Yes, confirming that build.cmd works just fine with Win7+Dev12 once the 4.5.2 targeting pack is installed.

**Comment by martinwoodward** [comment]
Cool. Added to the [wiki](https://github.com/OpenLiveWriter/OpenLiveWriter/wiki/Building,-Testing,-and-Debugging) - thanks @jthelin!

**Comment by JawadS** [comment]
Great share, that solved an issue I had while building my solution. Thank you!
