### ISSUE TITLE
 Make OpenLiveWriter portable

### ISSUE THREAD

**Issue by vatterspun** [OpenLiveWriter/OpenLiveWriter#452]
**Current behavior**: 

Right now it looks like it writes everything to "My Weblog Posts" in Documents.

**Requested capability**: 

Ability to save any and all settings to the local folder.

**Who will benefit from this?**

* **Cloud capability** - An individual who has OpenLiveWriter stored on their cloud drive (Dropbox, Google Drive, etc.) and wants to have the same experience/settings from one machine to another
* **USB drive** - Someone who uses a public terminal at a coffee shop, computer lab, etc.
* **Ease of backup / encryption** (e.g. Just quickly a folder rather than trying to track down relevant files in in the My Documents folder; storing the program inside a TrueCrypt / VeraCrypt volume)
* **Mac/Linux users** (via WINE/Crossover Office) - lets users just use the Windows version rather than re-entering their config across systems

Other notes

As this program is fairly old and has a solid following, some users will invariably prefer the old behavior as it works better with their existing backup/restore system.  As a result, I recommend making this optional.

**Comment by ScottIsAFool** [comment]
Thanks for raising this. It's something we have been considering (although no decision has been made thus far), we have this tracked with #113 and it's worth noting that you can, at least in the next version, change the location of where your blog posts are stored, so you could move them to your dropbox/onedrive/other folder. I thought this option was in 0.6.0.0, but upon checking, it appears it's not just yet.

**Comment by vatterspun** [comment]
@ScottIsAFool : thanks for that, I apologize for not searching for something before I posted this.  Would you like me to merge them to avoid confusion?

**Comment by ScottIsAFool** [comment]
@vatterspun Sure, if you add your comments/thoughts to that one, I'll close this one off :)

**Comment by vatterspun** [comment]
Cool.  Just moved over the jist of my request.
