### ISSUE TITLE
Editing pages (not posts) on a wordpress site.

### ISSUE THREAD

**Issue by zippy1981** [OpenLiveWriter/OpenLiveWriter#455]
I'd like to be able to edit pages (e.g. the about page) on my wordpress site the way I can with post.

**Comment by ScottIsAFool** [comment]
You can. When you go to the Open dialog window, choose your blog, then select the Pages option:
![image](https://cloud.githubusercontent.com/assets/1658896/14798181/3ce53b72-0b2e-11e6-9cbc-31bd968529f7.png)
