### ISSUE TITLE
Can't open online Wordpress drafts

### ISSUE THREAD

**Issue by jdhitsolutions** [OpenLiveWriter/OpenLiveWriter#462]
I think I just might need an explanation on how something works. I have two Wordpress blogs I write for. My own self-hosted blog and an online publisher. I can create a draft in my blog and saved it. I then open OLW, select my blog and I see the drafts. But when I do the exact same on the other blog, I never see them. It used to work but I don't manage that blog so I don't know what they might have changed. 

I've verified that XML-RPC publishing works. Is there something else I can check? My blog is running Wordpress 4.5.1 and the other is running 4.5.2 so I don't know if that is related or not.

**Comment by jdhitsolutions** [comment]
I updated my blog to 4.5.2 and I can still see drafts in OLW so this doesn't appear to be a Wordpress version issue.

**Comment by jdhitsolutions** [comment]
I have verified that I can use xmlrpc and the wp.getposts() method to see drafts on both sites. Not sure what approach OLW is using.

**Comment by ScottIsAFool** [comment]
What are the Writer logs showing? File > About > Show writer logs.

**Comment by jdhitsolutions** [comment]
Turns out is was something as simple as not selecting enough posts. I had been using the default of 20 which in the past was always good enough. I changed it to 100 and now I see my drafts. There are other authors on the site so it appears to me that OLW needs to get X number of posts and then it pares the list down to those where I am an author.  I assumed the number of posts would be limited to me, but apparently not because I don't see 100 posts I just see my portion of the last 100 posts from the site.
Shouldn't the default behavior be to filter by the author?

**Comment by kilasuit** [comment]
It would be very useful to add in support to filter by author as default.

**Comment by jdhitsolutions** [comment]
I thought that was the default behavior which is why I thought I had a problem. If this isn't the case, then I can close this and open up a feature request.

**Comment by kilasuit** [comment]
Issues are also used for Feature Requests - One of the OLW team will need to mark it with the right label

**Comment by jdhitsolutions** [comment]
I'm going to close this as I worked out the issue and open a new item that is specifically a feature request.
