### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by ALCvA** [OpenLiveWriter/OpenLiveWriter#463]
General options are limited to: None, English (Canada), English (Liberia), English (Republic of the Philippines) and English (United States). Whereas, until recently, most languages were available. Please sort this. I need English United Kingdom. Many thanks.

**Comment by ScottIsAFool** [comment]
You need to install English UK on your system. Please see the note on the release here https://github.com/OpenLiveWriter/OpenLiveWriter/releases/tag/0.6.0.0 specifically where it mentions about installing your preferred input. Once you have English UK installed via that, restart Writer and you should see English UK as an option.

**Comment by ALCvA** [comment]
Dear Scott,

Many thanks.

Cheers

Dr Alfred L.C. van Amelsvoort
Hello! Contact me here <http://www.alcvanamelsvoort.com/contact-me>

**Comment by ScottIsAFool** [comment]
Closing as this issue seems to be resolved.
