### ISSUE TITLE
Open Live Writer and Joomla

### ISSUE THREAD

**Issue by jhwheuer** [OpenLiveWriter/OpenLiveWriter#476]
Right, am giving up. Everything I am googling is either in the last decade, or pending...

How do I use OpenLiveWriter to access Joomla's blogging feature??? I have XMLRPC and RDS installed and enabled, still getting 

.../index.php/component/xmlrpc/service?format=xml 

not found...

Infuriating

**Comment by ScottIsAFool** [comment]
I think this is something you need to bring up with Joomla in their forums as it looks like something that has broken on their side. I tried installing this http://www.joomler.net/download/145-joomla3x/999-xmlrpc-for-joomla25-and-31x-updated-v207.html and then enabling both the xml-rpc package and the rsd package. I can see the RSD info now appearing in the home page, which shows a link to the WLWManifest file, but the url, as you're seeing is giving a 404 error (not found). So it sounds like something is broken on their end.

**Comment by jhwheuer** [comment]
Hi Scott, and thanks for the effort. Will do once I am back from the hols.Cheers 
|   | Dr. Jürgen Heuer |
| Cell: +491747893956 |
| Skype: jhwheuer |

**Comment by ScottIsAFool** [comment]
I'm going to close this issue for now as I don't believe this is a Writer issue, but one with the Joomla platform.

**Comment by jhwheuer** [comment]
Scott, totally agree. Thanks for taking the time. Am on summer hols, will take it up with the joomla team once I am back. 
|   | Dr. Jürgen Heuer |
| Cell: +491747893956 |
| Skype: jhwheuer |
