### ISSUE TITLE
Blog platforms compatibility

### ISSUE THREAD

**Issue by thibautsergent** [OpenLiveWriter/OpenLiveWriter#485]
On the website, it's says OpenLiveWriter works with "WordPress, Blogger, TypePad, Moveable Type, DasBlog and many more". 

What are these "many more" ?

Thanks

**Comment by ScottIsAFool** [comment]
Things like BlogEngine.Net. There are protocols that blogging platforms use that Writer is compatible with, things like the XML-RPC protocol, so any platform that has implemented that would work with Writer.

**Comment by thibautsergent** [comment]
Thanks =)
