### ISSUE TITLE
Picture won't post to LiveJournal

### ISSUE THREAD

**Issue by ggreig** [OpenLiveWriter/OpenLiveWriter#49]
I tried to post to my LiveJournal using OLW, and although the blog capabilities look identical in WLW and OLW, OLW failed to post a simple entry containing a picture, with the attached dialog box:
![olwerror](https://cloud.githubusercontent.com/assets/2883831/11701413/4fa09546-9ec7-11e5-88b8-98db7a9f9cd9.png)
This functionality did/does work perfectly with LiveJournal in Windows Live Writer.

**Comment by timheuer** [comment]
@ggreig I'm actually getting the same error on WLW 2012 as well (just created a new livejournal.com account) and not able to upload pictures.

**Comment by timheuer** [comment]
Found the bug...submitting a PR now

**Comment by ggreig** [comment]
Oh cool, and thanks very much. I was just about to submit my log, having failed to find any difference in options. Sounds like you're on top of it, but if I can still help in any way let me know.
