### ISSUE TITLE
Suggestion: post excerpt

### ISSUE THREAD

**Issue by moisb** [OpenLiveWriter/OpenLiveWriter#491]
Field to write the post excerpt

**Comment by Crypt32** [comment]
There is already option to provide post excerpt if your blog provider supports them.

**Comment by ScottIsAFool** [comment]
Sorry, I should have looked at these suggestions a bit more :) @Crypt32 is correct, if your blog supports it, you can click on View all which will give you access to the Excerpt box:

![image](https://cloud.githubusercontent.com/assets/1658896/17511705/1b4d409a-5e1c-11e6-8da3-bb23ea16f61b.png)
