### ISSUE TITLE
Feature Request - Setting to change default save location

### ISSUE THREAD

**Issue by Justblair** [OpenLiveWriter/OpenLiveWriter#496]
I have managed to accomplish this by adding a string PostsDirectory via regedit so that Open Live Writer now saves and retrieves files from my OneDrive Directory.  But I am sure that others will want to do the same (especially as it allows access to drafts across several devices.

**Comment by ScottIsAFool** [comment]
This will actually be coming in the next release of Live Writer, the feature has been done.

**Comment by Justblair** [comment]
Oh Cool.  Thanks
