### ISSUE TITLE
Metadescription or additional field

### ISSUE THREAD

**Issue by iberodev** [OpenLiveWriter/OpenLiveWriter#520]
I'm new to OLW. I am using it for a blog with type Metaweblog API and I have noticed that OLW only allows to add a title and a comment fields.

Is there any option to add additional fields such as metadescription or summary or similar? Is there any merit on adding this capacity or the structure of a post should always be Title and Content + Categories and nothing else?

**Comment by ScottIsAFool** [comment]
If your blog supports it, that functionality is already there
![image](https://cloud.githubusercontent.com/assets/1658896/19091894/612e039c-8a7c-11e6-8080-b4a6ad118485.png)
Which gives you
![image](https://cloud.githubusercontent.com/assets/1658896/19091903/6c3ebd80-8a7c-11e6-9654-ed818ca028f3.png)

**Comment by iberodev** [comment]
ah, excellent! Thanks for that, I hadn't noticed an excerpt field was there
