### ISSUE TITLE
Question: Details on automatic image hosting?

### ISSUE THREAD

**Issue by szalapski** [OpenLiveWriter/OpenLiveWriter#531]
I created a Blogger post using Open Live Writer, and it seems that it hosted an image onto lh3.googleusercontent.com for me.  How can I find out details on this image hosting?  Will this image stay there forever?  What are the bandwidth limits on it?

My post:  http://www.szalapski.com/2016/11/scrum-guide-updated-to-include-valuing.html

**Comment by ScottIsAFool** [comment]
@szalapski those are questions you'd need to ask of Blogger as they are your blog provider and owner of the googleusercontent domain. You might be able to find your answers here https://support.google.com/blogger/?hl=en#topic=3339243

**Comment by szalapski** [comment]
I thought that Open Live Writer was uploading the images?  How does OLW upload images, is my real question.  Does OLW upload the image to the host domain directly? Does it use some other API?

**Comment by ScottIsAFool** [comment]
It posts the images to the blogger api, where they then get hosted is Blogger's call, we just get the resulting Uri from that call. You can change it in the Live Writer settings where it publishes to, but your options are really the blog platform or an ftp server.

**Comment by szalapski** [comment]
Great, thanks.  That's perfect.
