### ISSUE TITLE
Old branding/BlogThis in resources

### ISSUE THREAD

**Issue by timheuer** [OpenLiveWriter/OpenLiveWriter#54]
see: https://github.com/OpenLiveWriter/OpenLiveWriter/blob/master/src/unmanaged/OpenLiveWriter.Shortcuts/OpenLiveWriterShortcuts.rc#L16
Remove:
- Windows Live
- 2 Blog This entries

**Comment by martinwoodward** [comment]
Hey @timheuer - is this ready to close now after PR #87?

**Comment by willduff** [comment]
Looks like this can be closed.
