### ISSUE TITLE
BlogClient Plugins

### ISSUE THREAD

**Issue by oliverw** [OpenLiveWriter/OpenLiveWriter#549]
After studying the source I've come to the conclusion that implementing custom Blog Clients through <code>IBlogClient</code> is currently not possible. Correct?

**Comment by ScottIsAFool** [comment]
I think you can, but they'd have to be part of Writer's code, you couldn't do it as an external plugin dll like you can with regular plugins.

**Comment by oliverw** [comment]
Yeah I've meant implementing a client in an external plugin.
