### ISSUE TITLE
Support for High DPI

### ISSUE THREAD

**Issue by Mephisztoe** [OpenLiveWriter/OpenLiveWriter#553]
When using OpenLiveWriter on a Surface Pro 4, it seems as if there are rendering problems due to its High DPI capable display.

![2017-01-17 13_43_48-untitled - open live writer](https://cloud.githubusercontent.com/assets/5309613/22020952/1d1280c0-dcbb-11e6-8f6b-a568d78a228f.png)

**Comment by ScottIsAFool** [comment]
Yep, this is already logged with #44
