### ISSUE TITLE
Initial Authentication to Blogger broken in recent versions

### ISSUE THREAD

**Issue by nycdotnet** [OpenLiveWriter/OpenLiveWriter#561]
Version v0.6.0.0, v0.5.1.4, and v0.5.1.3 do not allow authentication to a Blogger blog when running the initial setup of the app.  When the user selects "Google Blogger" at the "What blog service do you use?" prompt, and clicks "Next" and then "Sign In", they are delivered to the following URL:

`https://accounts.google.com/o/oauth2/auth?access_type=offline&response_type=code&client_id=PASTE_YOUR_CLIENT_ID_HERE&redirect_uri=http:%2F%2Flocalhost:51895%2Fauthorize%2F&scope=https:%2F%2Fwww.googleapis.com%2Fauth%2Fblogger%20https:%2F%2Fpicasaweb.google.com%2Fdata`

Please note the `client_id` value in the URL of `PASTE_YOUR_CLIENT_ID_HERE`.

The client_id to use comes from `src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Secrets.json`, which is specifically in the repo's `.gitignore` file.  The computers used to build these recent versions appear to not have had this secrets file up-to-date.

Version v0.5.1.2 **does work** and passes what appears to be a valid client ID to Google when attempting to authenticate.  Updating to v0.6.0.0 after that seems to work fine; Open Live Writer remains authenticated to the user's blog.

**Comment by ScottIsAFool** [comment]
I'm unable to reproduce this. I've tried both 0.6.0.0 and the version that's in the Windows 10 Store, both provide the correct client id. Have you tried building the source yourself? I just want to make sure that it's not been using a local build?

**Comment by nycdotnet** [comment]
Hi Scott,

Thank you for looking into this.  It appears that this is a duplicate of issue #443 and seems to be related to installing via Chocolatey.  The installer there is bad and does not link to the actual download from the web site.  Note the comments on the package here: https://chocolatey.org/packages/openlivewriter.  My sincere apologies!

I will follow up with the Chocolatey folks to get the package there updated.
