### ISSUE TITLE
Support for BlogEngine?

### ISSUE THREAD

**Issue by jradxl** [OpenLiveWriter/OpenLiveWriter#575]
The orginal Live Writer 2012 supported BlogEngine oerfectly well.
OpenLiveWriter does not appear to have an (install) option for BlogEngine.
Can anyone advise?
Thx

**Comment by bayfieldbunch** [comment]
How to install an older version??

Sent from my BlackBerry - the most secure mobile device - via the Bell Network
          Original Message

        Show Details

**Comment by jradxl** [comment]
Oh, it does work.....
Rather confused there was no explicit option for BlogEngine, but fiddle around with it and perhaps using the dasBlog option, it now does work well. 
Sorry for the inconvenience.
