### ISSUE TITLE
Open live writer works local but does not work on server

### ISSUE THREAD

**Issue by pouyaSamie** [OpenLiveWriter/OpenLiveWriter#577]
Hi Every one 

i am using OpenLiveWriter with Orchard blog i build and run orchard on my local machine and it works fine but when i publish my website on server it can not connect it shows this error
![untitled](https://cloud.githubusercontent.com/assets/1997461/23619825/253e89be-02aa-11e7-8980-da2fbcb91510.png)

i even used my exact blog address and it gives me same error can anyone help me?

**Comment by ScottIsAFool** [comment]
What are you putting in the previous screen? If you look at the address it's giving there, including the XmlRpc, that gives a not found response.

**Comment by pouyaSamie** [comment]
I have tested this with my blog address like this picture
![untitled](https://cloud.githubusercontent.com/assets/1997461/23623206/65bab128-02b6-11e7-8469-ebebf8c964b2.png)
and even i used it with my blog name like this
![untitled](https://cloud.githubusercontent.com/assets/1997461/23623294/c2681348-02b6-11e7-802e-6a1a1fd28362.png)


and the result is the same 
by at my local machine i tested both of this methods and they are just fine

**Comment by ScottIsAFool** [comment]
It looks like this might be the culprit https://wordpress.org/support/topic/403-forbidden-on-xmlrpcphp/ where your hosting provider may have blocked access to it. It might be worth contacting them and find out if this is the case.

**Comment by pouyaSamie** [comment]
ok i found the problem.
when i enable Secure Sockets Layer module this problem will happen now i have disabled this module and everything works fine

**Comment by ScottIsAFool** [comment]
I'm going to close this issue as I'm dealing with it in issue #580 

@pouyaSamie Can you try re-enabling your Secure Sockets Layer module, then try the build mentioned in this comment https://github.com/OpenLiveWriter/OpenLiveWriter/issues/580#issuecomment-286349431 and see if that lets you add the blog ok. Any replies should be added to issue #580.
