### ISSUE TITLE
Blog entry will not publish

### ISSUE THREAD

**Issue by ruthross** [OpenLiveWriter/OpenLiveWriter#579]
I have 2 blogs to which I post using Open Live Writer. One works fine. Recently, the other (www.njartsmaven.com) is giving me trouble when I click Publish. I get this message: The remote server returned an error: (400) Bad Request. I have not changed a thing. The www.charmcityartsmaven.com blog posts just fine. If I remove photos or artwork attached to emails, then I can publish. But my blog depends on artwork and photos. Can anyone help me? I am afraid to delete and reinstall the njartsmaven blog.

**Comment by ScottIsAFool** [comment]
@ruthross the one that's stopped working, does this happen when you are trying to publish a post with images? If so, are you able to publish a post with no images?

**Comment by ruthross** [comment]
Yes to both questions. Some images will work, especially if they are on the internet. But attached jpg and pdf files result in no publishing. The Baltimore blog works just fine. A friend had a similar problem a couple of weeks ago. I didn't then.

Ruth

**Comment by ScottIsAFool** [comment]
OK, I think this is the same bug as #562 which we're investigating. If you look at that issue, there's a workaround in there too so it should get you back up and running ok.

**Comment by ruthross** [comment]
Scott, I tried to understand the directions in #562 about Google Photos. I have an album for NJ Arts Maven there. I was able to post using artwork that came in Constant Contact or an email, but when I tried to post using jpeg files attached, I got this message: The remote server returned an error: (400) Bad Request.  I tried to save them to a file on my computer and then retrieve them from there, but no go. HELP!

Ruth Ross

**Comment by ScottIsAFool** [comment]
The workaround is this:
1. Go to http://photos.google.com
2. Click on Create
![image](https://cloud.githubusercontent.com/assets/1658896/23786147/39c434fe-0563-11e7-83b5-ef12d55b7a9c.png)
3. Click Album
![image](https://cloud.githubusercontent.com/assets/1658896/23786163/4e1473ec-0563-11e7-8bb5-51dd3d4c0160.png)
4. Select any picture when you're presented with a list of pictures, then click Create in the top right
5. Call the album "Open Live Writer", then click the tick in the top left. 

You should be able to post with images then.

**Comment by pigtowndesign** [comment]
I tried the work-around suggested above and still got the error: The remote server returned an error: (400) Bad Request. I've been posting on my blog through Live Writer and Open Live Writer for ages, and can't stand the thought of doing it through the Google blogger platform. 

Thanks for any help!

**Comment by ruthross** [comment]
Don't know what to say. It worked for me, knock wood!

 

Try sending you request to Scott Lovegrove [notifications@github.com].

 

Ruth Ross

**Comment by ScottIsAFool** [comment]
@pigtowndesign When you created the album, did you create a regular album, or a shared one?

**Comment by pigtowndesign** [comment]
@scottisafool I created a regular album. Should i do a shared one?

Thanks!

**Comment by ScottIsAFool** [comment]
No, regular is correct. If "Open Live Writer" didn't work, try "Windows Live Writer" just in case, some people have found that to work.

**Comment by pigtowndesign** [comment]
Will do!

**Comment by crpaiva** [comment]
What am I doing to get around this error for now.
First I make the whole post issue in OLW. Then I upload the photos inserted in the direct post (final format) to the Google Photos Open Live Writer album.
Lastly, I replaced the local photos in the OLW with them, but using the address of the photo obtained directly from Google Photos.
So I can use the advantages of editing OLW. That done, just publish.
Last time was the way I solved it last year. A while later, the error stopped and I continued to use OLW without problems

**Comment by jritmeijer-muhimbi** [comment]
This problem appears to be back (error 400), even though I have the appropriate google Photos album, and OLW has worked fine for quite some time posting similar blog posts and uploading images.

@crpaiva how do you get the URL from Google Photos? It always return the UI when I try to copy the URL for just the image.

**Comment by crpaiva** [comment]
After upload the image to the album, click over to open the image and using
your right mouse button, copy the image address. Use this address to insert
image from the WEB.

Em sex, 18 de jan de 2019 15:43, Jeroen Ritmeijer <notifications@github.com
escreveu:

**Comment by ruthross** [comment]
I have used the copy image address to insert images that won’t cause the 400 error. It’s been successful. Haven’t had an error message in a long time. 

RR

**Comment by ruthross** [comment]
Contact Scott Lovegrove [mailto:notifications@github.com]

**Comment by ruthross** [comment]
I often get around it by finding a comparable photo on Google Images.

**Comment by thanislim** [comment]
If you are experiencing problems with this update - here's how to fix the multiple instances as well as the new error 404 issue http://www.thanislim.com/2019/03/how-to-fix-open-live-writer-error-400.html

Hope this is helpful for everyone and do drop me a follow on my Instagram as thanks ;)
