### ISSUE TITLE
The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by ruthross** [OpenLiveWriter/OpenLiveWriter#581]
Now I got this message when I tried to post to blogger via OLW. This is a different error message (the previous one was 500. Can someone help me?

**Comment by swbuehler** [comment]
Cannot publish to Blogger. The remote server returned an error: (400) Bad Request.

**Comment by ruthross** [comment]
Scott Lovegrove sent me this. It seemed to work.

 

The workaround is this:

1.	Go to http://photos.google.com
2.	Click on Create
 <https://cloud.githubusercontent.com/assets/1658896/23786147/39c434fe-0563-11e7-83b5-ef12d55b7a9c.png> image
3.	Click Album
 <https://cloud.githubusercontent.com/assets/1658896/23786163/4e1473ec-0563-11e7-8bb5-51dd3d4c0160.png> image
4.	Select any picture when you're presented with a list of pictures, then click Create in the top right
5.	Call the album "Open Live Writer", then click the tick in the top left.

You should be able to post with images then.

Ruth Ross

**Comment by ditchcrawler** [comment]
I had the same problem, The remote server returned an error: (400) Bad Request. 
 This started with the last JPG I tried to upload last night, tonight I can't upload and photos, including ones that would successfully upload last night.
 I store my photos on my hard drive not in Cloud

**Comment by ruthross** [comment]
Scott Lovegrove sent me this. It seemed to work.
 
The workaround is this:

Go to http://photos.google.com
Click on Create

Click Album

Select any picture when you're presented with a list of pictures, then click Create in the top right
Call the album "Open Live Writer", then click the tick in the top left.
You should be able to post with images then.



Ruth Ross

**Comment by ScottIsAFool** [comment]
We are addressing this issue with #564. Closing this one.

**Comment by ruthross** [comment]
Thanks for helping me. I want to post a video on my blog, but I don't know how to get it to work when somebody clicks on the arrow. I usually have to copy and paste the source of the video and say click here to watch trailer. Can you help me put a video in and have it work when somebody clicks on the arrow?

Ruth Ross

**Comment by pigtowndesign** [comment]
Hi...tried all of the above and still getting this "The remote server returned an error: (400) Bad Request"

**Comment by sboyd000** [comment]
Tried this.  It worked once but then I got the error the next time I tried to publish.  So I did it again....exactly with a different picture.  No luck.  Can't post.  What's up here?

**Comment by ScottIsAFool** [comment]
@pigtowndesign @sboyd000 Can you please try removing your blog from OLW and then adding it back again.

**Comment by sboyd000** [comment]
Can you tell me how to do that?   And what about creating an album called Open Live Writer1?

**Comment by sboyd000** [comment]
Worked with Open Live Writer1.   We'll see if I can post the next time without having to create Open Live Writer2

**Comment by ruthross** [comment]
Sboy,

Please take me off your cc list. I merely forwarded Scott Lovegrove's email address to you. I am merely a blogger who had trouble with OLW recently.  Here's his email: Scott Lovegrove [notifications@github.com]

 

Thanks,

ruthross

**Comment by sboyd000** [comment]
So sorry. Will do.  All seems well for the moment.

**Comment by ScottIsAFool** [comment]
@ruthross to stop getting emails from this issue, you need to go to https://github.com/OpenLiveWriter/OpenLiveWriter/issues/581 and click the unsubscribe button on the right
![image](https://cloud.githubusercontent.com/assets/1658896/25034136/4dc6e0ac-20dc-11e7-92ed-d00e99a8d854.png)

**Comment by ruthross** [comment]
Thanks?
Ruth
