### ISSUE TITLE
Google Auth redirects to localhost after successful login

### ISSUE THREAD

**Issue by jasonbrown1965** [OpenLiveWriter/OpenLiveWriter#583]
Did a reinstall of W10 and OLW. After adding back in permissions for blogger/blogspot accounts, I am getting the error below.

http://localhost:59596/authorize/?code=4/fUuEo9ypuG8z7dINfpzuV-XOuTRlDS_y9RCzVON56SI#

However OLW merrily carries on and adds the blog account anyway, and everything seems to work, as in publish, so not sure how serious this is. 

![image](https://cloud.githubusercontent.com/assets/11400799/23826984/ef187896-070d-11e7-83d9-dc3aaa06e080.png)

**Comment by ScottIsAFool** [comment]
That browser window can be closed without a problem, this is just the end of the Google authentication flow.

**Comment by ScottIsAFool** [comment]
Reopening as we should have a better landing page after authentication with Google.

**Comment by jongalloway** [comment]
//TODO:

- [ ] Get credentials to Google dev dashboard
- [ ] Create an "Authentication complete" page on openlivewriter.org
- [ ] Update in Google auth redirect to auth complete page

**Comment by jasonbrown1965** [comment]
Thanks gang, sorry to add to the workload ... just thought I'd better bring it to your attention in case there's a security aspect ... there's no security aspect is there?

**Comment by jongalloway** [comment]
Auth complete page is here: http://openlivewriter.org/WriterRedirect/AuthComplete.html

**Comment by jongalloway** [comment]
@jasonbrown1965 Thanks for reporting this. There's no security issue at all, but it is confusing to users and needed to get fixed. Thanks for the report!

**Comment by jasonbrown1965** [comment]
Many, many belated thanks again.

I was just looking at the main issues page for OLW and saw that there were 393 issues raised, and 206 closed, an impressive ratio for open source loveliness #simpleeasy ... then I had a moment of dread.

Yep, I'm one of the 206 not closing an issue report. Almost. One. Year. Later. 

#SAD

**Comment by jasonbrown1965** [comment]
#suggestionbox ?

An auto-bot sending quarterly reminders via email, FB etc ? 
And a complete URL list of every OLW news update, perhaps. 

Suggested [raw] text : 

[Was your issue at Github OpenLiveWriter solved? If so, please consider marking it "closed" under the "Close and Comment" talk button.]

[other links, e.g. unsubscribe, etc]
