### ISSUE TITLE
Cannot publish to google blogger when upload some images

### ISSUE THREAD

**Issue by retro777** [OpenLiveWriter/OpenLiveWriter#600]
I tried many times put to google blogger when upload some images.
but cannot it.

is this OpenLiveWriter problems??

**Comment by ScottIsAFool** [comment]
Can you please try the instructions here and see if that resolves the issue for you http://openlivewriter.org/tutorials/googlePhotoFix.html

**Comment by retro777** [comment]
oh thanks, problem is fix...
