### ISSUE TITLE
Set up .NET Foundation CLA automation bot

### ISSUE THREAD

**Issue by Eilon** [OpenLiveWriter/OpenLiveWriter#61]
It's used throughout many projects and would be great to have here.

@martinwoodward do you know who to contact to set that up? (For projects internal to MSFT we have a tool to set it up; I don't know how it works for these.)

**Comment by martinwoodward** [comment]
Working on it now

**Comment by ScottIsAFool** [comment]
This is up and running now, so can be closed I guess.
