### ISSUE TITLE
Ver 6.2 download - correct link?

### ISSUE THREAD

**Issue by Laronski** [OpenLiveWriter/OpenLiveWriter#618]
I got a notice that ver 6.2 was ready and to download it from  http://openlivewriter.org/

When I downloaded it; it was v6.

Is the right file in place for download?

**Comment by ScottIsAFool** [comment]
0.6.2.0 is in pre-release right now. I think you got notified about the Release from here https://github.com/OpenLiveWriter/OpenLiveWriter/releases/tag/0.6.2.0. We're getting ready for a release later today.
