### ISSUE TITLE
Open Live Writer not opening

### ISSUE THREAD

**Issue by SORJM** [OpenLiveWriter/OpenLiveWriter#624]
Suddenly Open Live writer stopped working on my windows 8.1. I re installed the application but the same problem exist. Please guide me how to solve this problem.

**Comment by jongalloway** [comment]
Can you check which version of .NET you have installed using the .NET Checker here: http://smallestdotnet.com/

**Comment by SORJM** [comment]
Thanks for reply. NET Framework 4.5.2 is installed on my desktop.

**Comment by ScottIsAFool** [comment]
@SORJM Can you please follow the same link as above but click on "Get .NET" and this should update your system to the latest .net framework. After this has installed, reboot, and you should be good to go.

**Comment by SORJM** [comment]
I updated to 4.6.2 version of Net Framework. Now software started opening. But another problem started appearing. The software has not adapted blog template well. I tried to download it again from software option. But it did not worked. So now editing is quite difficult. See the attached Images and guide me to solve this problem.

**Comment by ScottIsAFool** [comment]
@SORJM as a temporary work around, you can go to Blog Account tab and turn off the theme so you can at least see what youre doing. As for this issue, I'm going to close this one as the original problem is now fixed. If you could open a new issue about the theme rendering and include the screenshot (I don't see one attached above), that would be great.
