### ISSUE TITLE
Split Post visual indicator missing

### ISSUE THREAD

**Issue by rynehager** [OpenLiveWriter/OpenLiveWriter#629]
A recent update seems to have killed the visibility for the "Split Post" break, now you can't tell if one has been inserted.
![2017-05-29_19-21-36](https://cloud.githubusercontent.com/assets/13444140/26563742/fafb7486-44a4-11e7-8297-f68da22d26f2.png)

Using 0.6.2.0 on Windows 10 with a Wordpress site.

**Comment by ScottIsAFool** [comment]
Thanks for reporting this, I can reproduce this and we are investigating.

**Comment by kunal-chowdhury** [comment]
I am also facing the same issue. There's no visual indicator but in the HTML code, it's present.

**Comment by Laronski** [comment]
I reported this a while back; never got a reply from anyone. I'm glad it has some focus now.
https://github.com/OpenLiveWriter/OpenLiveWriter/issues/571
