### ISSUE TITLE
OLW will not open.  

### ISSUE THREAD

**Issue by vacationdreamer** [OpenLiveWriter/OpenLiveWriter#643]
I had not blogged since 4/28 or so and went to launch OLW on 6/20.  It would not open on my computer.  Some flickering on the screen and no further.  I looked into it a bit and had to move on with my day.

The next day I tried to uninstall it, so that I could reinstall it.  I've since tried that a few more times.

Oddly enough, it launches on my laptop.

I could not download the newer version, either.  I've confirmed all pop-up blockers are off and that it is a trusted site. I've turned off Norton.

**Comment by ScottIsAFool** [comment]
Could you please go to www.smallestdotnet.com and install 4.6 of .net, reboot then try again.

**Comment by vacationdreamer** [comment]
Thank you for responding.  In the process of downloading that, although it actually says 4.6.1 so I may have selected the wrong one.  I will see what happens.

**Comment by vacationdreamer** [comment]
Thank you for your help.  
It seems to be working now with a small test entry.  
I appreciate your help!!!!!!!
