### ISSUE TITLE
Save dialog prompt pops up even if nothing was changed

### ISSUE THREAD

**Issue by hmemcpy** [OpenLiveWriter/OpenLiveWriter#65]
Open OLW, then close it immediately, without changing anything. You'll get the "unsaved changes" dialog. It shouldn't appear until the title or the content was changed.

**Comment by martinwoodward** [comment]
That's very odd. FWIW I don't get the prompt on my machine with build 0.5.0.0 but I've no idea why you are. The only thing I would try is to see if you could debug from the source code of OLW in Visual Studio and see if you and trace back why the dirty buffer flag is being set on initial load for you.

**Comment by hmemcpy** [comment]
Really not sure why this is happening, but at some point after initializing, the `IHTMLChangeSink.Notify()` is firing, forcing `IsDirty` on `MshtmlEditor` to be true.
Nothing obvious from the stack trace... any ideas?

**Comment by martinwoodward** [comment]
What operating system and IE version are you running on?

**Comment by hmemcpy** [comment]
Windows 10.0.10586, and IE 11.

**Comment by willduff** [comment]
I can repro this as well. It's a bug that was constantly popping up even on Windows Live Writer back when we were developing it, so it's going to be a bit of a battle to get this working, but I'd like to fix it.

**Comment by hmemcpy** [comment]
Any tricks to diagnose those events firing? My COM is a bit rusty :)

**Comment by hmemcpy** [comment]
@martinwoodward could you tell me what blog provider you're using? I'm using a custom wordpress, are you using something else?

**Comment by martinwoodward** [comment]
I'm using Moveable Type on Windows 10. But from the issues you are describing it sounds like some interaction inside the editor rather than the blog clients.

**Comment by hmemcpy** [comment]
I had some help on twitter from Justin Rogers (IE/Edge team), he gave some hints on how to diagnose this issue! I'll post in greater detail later, but I've made progress: I managed to get the "Change log" structure from the Notify change event (by using `IMarkupContainer.CreateChangeLog`), it seems that I'm getting an event that contains the text `<SPAN>` during startup. Roger's [response](https://twitter.com/JustRogDigiTec/status/679412918090203136) to this suggests this may be because of the caret being placed in a "containing block".

I suspect this is because of the post title element: I'm getting the `Notify` event shortly before the post title element is drawn in the editor. I asked which provider you were using to try and compare those behaviors...

Anyway, it's a very interesting bug, I'll keep digging!

**Comment by hmemcpy** [comment]
@martinwoodward while I couldn't truly pinpoint the source of the problem (I still have a suspicion this happens during the attaching of a behavior to the title element in `BlogPostHtmlEditorControl`, or somewhere in the neighborhood). However, I was able to work around this problem by simply suppressing handling of the `Notify` callback during document completion.

Please review :)
