### ISSUE TITLE
Unable to run/install OpenLiveWriter version 0.6.2.0

### ISSUE THREAD

**Issue by iindex** [OpenLiveWriter/OpenLiveWriter#655]
Downloaded latest version from the http://openlivewriter.org/
OS: Windows 8.1 Enterprise, 64-bit
When I execute OpenLiveWriterSetup.exe it does nothing. In event viewer there are following errors:
First, source .NET Runtime:
Application: OpenLiveWriter.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingMethodException
Stack:
   at OpenLiveWriter.ApplicationMain.Main(System.String[])

Second, source Application Error:
Faulting application name: OpenLiveWriter.exe, version: 0.6.2.0, time stamp: 0x59248655
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18666, time stamp: 0x58f32841
Exception code: 0xe0434352
Fault offset: 0x00015608
Faulting process id: 0x220c
Faulting application start time: 0x01d300933c58d4b3
Faulting application path: C:\Users\vkov\AppData\Local\OpenLiveWriter\app-0.6.2\OpenLiveWriter.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report Id: 7a0e21e5-6c86-11e7-82ad-8019346b3c70
Faulting package full name: 
Faulting package-relative application ID:

**Comment by iindex** [comment]
Report:
Version=1
EventType=APPCRASH
EventTime=131449446497533495
ReportType=2
Consent=1
UploadTime=131449446498771532
ReportIdentifier=7a0e21e6-6c86-11e7-82ad-8019346b3c70
IntegratorReportIdentifier=7a0e21e5-6c86-11e7-82ad-8019346b3c70
WOW64=1
NsAppName=OpenLiveWriter.exe
Response.BucketId=12d07ce1e8d9c097c0accb800dfc9adf
Response.BucketTable=1
Response.LegacyBucketId=108939227202
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=OpenLiveWriter.exe
Sig[1].Name=Application Version
Sig[1].Value=0.6.2.0
Sig[2].Name=Application Timestamp
Sig[2].Value=59248655
Sig[3].Name=Fault Module Name
Sig[3].Value=KERNELBASE.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=6.3.9600.18666
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=58f32841
Sig[6].Name=Exception Code
Sig[6].Value=e0434352
Sig[7].Name=Exception Offset
Sig[7].Value=00015608
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.3.9600.2.0.0.256.4
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1049
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=5861
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=5861822e1919d7c014bbb064c64908b2
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=5f25
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=5f2531ae070278f893fa99352dadd49e
UI[2]=C:\Users\vkov\AppData\Local\OpenLiveWriter\app-0.6.2\OpenLiveWriter.exe
UI[3]=OpenLiveWriter.exe has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Users\vkov\AppData\Local\OpenLiveWriter\app-0.6.2\OpenLiveWriter.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\WINDOWS\SYSTEM32\KERNEL32.dll
LoadedModule[4]=C:\WINDOWS\SYSTEM32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\SYSTEM32\ADVAPI32.dll
LoadedModule[6]=C:\WINDOWS\SYSTEM32\msvcrt.dll
LoadedModule[7]=C:\WINDOWS\SYSTEM32\sechost.dll
LoadedModule[8]=C:\WINDOWS\SYSTEM32\RPCRT4.dll
LoadedModule[9]=C:\WINDOWS\SYSTEM32\SspiCli.dll
LoadedModule[10]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[11]=C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll
LoadedModule[12]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll
LoadedModule[13]=C:\WINDOWS\SYSTEM32\SHLWAPI.dll
LoadedModule[14]=C:\WINDOWS\SYSTEM32\combase.dll
LoadedModule[15]=C:\WINDOWS\SYSTEM32\USER32.dll
LoadedModule[16]=C:\WINDOWS\SYSTEM32\GDI32.dll
LoadedModule[17]=C:\WINDOWS\system32\IMM32.DLL
LoadedModule[18]=C:\WINDOWS\SYSTEM32\MSCTF.dll
LoadedModule[19]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
LoadedModule[20]=C:\WINDOWS\SYSTEM32\MSVCR120_CLR0400.dll
LoadedModule[21]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\mscorlib\c90ef9a73ea0044641d31b19023aad61\mscorlib.ni.dll
LoadedModule[22]=C:\WINDOWS\SYSTEM32\ole32.dll
LoadedModule[23]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[24]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[25]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
LoadedModule[26]=C:\WINDOWS\SYSTEM32\OLEAUT32.dll
LoadedModule[27]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[28]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[29]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[30]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System\1c5fe4cb68f67046baec4c3a854f722f\System.ni.dll
LoadedModule[31]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Drawing\8efdc7a3726640f79d9333da88accaf8\System.Drawing.ni.dll
LoadedModule[32]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Windows.Forms\2506ba594ad5d30a471e4bbb603333dd\System.Windows.Forms.ni.dll
LoadedModule[33]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=OpenLiveWriter.exe
AppPath=C:\Users\vkov\AppData\Local\OpenLiveWriter\app-0.6.2\OpenLiveWriter.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=D891227B5B42BF691F15DFADA16D5CFB

**Comment by ScottIsAFool** [comment]
Can you go to http://www.smallestdotnet.com/ and make sure to install .net 4.6, after rebooting, try running OLW again.

**Comment by iindex** [comment]
Thank you! it worked
