### ISSUE TITLE
SSL or Wordpress Multisite

### ISSUE THREAD

**Issue by demortes** [OpenLiveWriter/OpenLiveWriter#66]
I'm trying to connect a Wordpress Multisite server, and it refuses to connect. Gives me "You signed in successfully with a blog account, but you do not have a blog with this service provider. S#xA:Check with the blog service provider and then try again."

I run the site on my server, using SSL forced. The certificates are trusted through StartSSL and then the CDN is through Cloudflare (all free options).

**Comment by onovotny** [comment]
I was able to connect this to my SSL WordPress blog. I self-host on Azure App Service.

**Comment by demortes** [comment]
What version of word press? I tried turning off SSL but my server refuses to do so. I suspect it's a problem with multi site

**Comment by onovotny** [comment]
I've been using SSL since this summer on https://oren.codes. It's currently on 4.4 running in an Azure App Service. In those settings, I have oren.codes as a hostname attached to the site and a SSL Cert listed there as an SNI SSL.

That was it, it just worked. Then, I had to set the default site url in the wp-admin settings but that was just to make the defaults the way I wanted them.

**Comment by hajekj** [comment]
I agree with @demortes, having the same issue with multisite WordPress.

**Comment by willduff** [comment]
I don't think this is specifically an SSL issue. @hajekj or @demortes, can you guys attempt to connect and then send me your log file? The log files should have details around why this failed. See [instructions for sending log file](https://github.com/OpenLiveWriter/OpenLiveWriter/wiki/Instructions-for-posting-your-Writer-log-file).

**Comment by hajekj** [comment]
@willduff: Well, I can't get past the blog initialization step so I cannot access the logs.

**Comment by willduff** [comment]
Good point! You'll need to manually find the log file via Windows Explorer. The log file is at %localappdata%\OpenLiveWriter\Open Live Writer.log. I've added this to the Wiki. Let me know if you're not able to find it.

**Comment by demortes** [comment]
Sent @willduff

**Comment by hajekj** [comment]
Okay, I just attached the log.
[Open Live Writer.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/67747/Open.Live.Writer.txt)

**Comment by demortes** [comment]
So, I downloaded the source and ran it, found the exception, and found that Open Live Writer isn't reading the response XML correctly. As my coding in C# is minimal, I'm not going to expect a patch to come from me. The XML-RPC services (which I forced, assumed that was the default for Wordpress in Open Live Writer, since I saw no other options in Worpdress itself) request and response should be attached shortly after I edit out my password (and any other sensitive data I might find.)

**Comment by demortes** [comment]
FYI, Submitted pull request. Works on my machine. C# is easier to get into than I thought... and the problem was easier to fix than I thought too.

**Comment by hajekj** [comment]
Another solution would be to replace the XML-RPC with WordPress's REST API which is being implemented into version 4.4 and onward: https://make.wordpress.org/core/2015/10/28/rest-api-welcome-the-infrastructure-to-core/ and http://v2.wp-api.org/

**Comment by demortes** [comment]
My only comment on that is that those using 4.4 would benefit, sure. But that was recently released, IIRC. Automatic upgrades would help adaptation, but that's an big limiting factor for those that might want to use OLW. No reason we can't fix this AND support REST, though.

**Comment by willduff** [comment]
Fixed with pull request #194.
