### ISSUE TITLE
Blogger: 'Category' data

### ISSUE THREAD

**Issue by SteveP-UK** [OpenLiveWriter/OpenLiveWriter#661]
Hi Folks. I'm using the latest version of OLW on two separate PCs. I'm syncing the blogs themselves as well and the Link Glossary (using DropBox).

I'm using a Blogger account.

I've noticed that when comparing the two machines, if I add a 'category' on machine 1, it's not updated on machine 2 - I _wouldn't_ expect it to automagically! :)

Anyone know where the blogger 'category' data is stored on the PC? I thought it might be under AppData/Roaming/OpenLiveWriter... but I can't see anything in there that's relevant.

Thanks people... and thanks for keeping this fantastic app alive!

Cheers
Steve

**Comment by ScottIsAFool** [comment]
These are actually stored in the registry. Now, depending on how you've installed the app, you may or may not have access to those entries. If you have installed via the Windows Store, then you can't access these unfortunately. If you installed via any other means, then you can get them from the registry at HKCU\Software\OpenLiveWriter\Weblogs\{BlogGuid}\Categories

**Comment by SteveP-UK** [comment]
Hi Scott

Thank you - that's really helpful.

Is there a way to sync the registry entries between the PCs?

Regards

Steve

**Comment by ScottIsAFool** [comment]
In a word: no. Although in the Writer interface and the list of categories, you should have the refresh button there, pressing that should updated all your categories for that blog, but only if those categories live on the server.

**Comment by SteveP-UK** [comment]
Cheers Scott

Good answer!

As a workaround, could I export the registry value on PC1 and then manually
import it into PC2?

Regards

Steve
www.StevePalmer.com
blog.StevePalmer.com
@TweetsBySteveP
+44 (0)1536 312 766
07860 639 661

On 2 Aug 2017 3:17 pm, "Scott Lovegrove" <notifications@github.com> wrote:

In a word: no. Although in the Writer interface and the list of categories,
you should have the refresh button there, pressing that should updated all
your categories for that blog, but only if those categories live on the
server.

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/OpenLiveWriter/OpenLiveWriter/issues/661#issuecomment-319686003>,
or mute the thread

**Comment by ScottIsAFool** [comment]
Yes.

**Comment by SteveP-UK** [comment]
Cheers Scott!

An even better answer! Thanks for responding so promptly!

Regards

Steve
