### ISSUE TITLE
Google Blogger credentials not being accepted

### ISSUE THREAD

**Issue by geeksrik** [OpenLiveWriter/OpenLiveWriter#67]
Hello, google blogger credentials are not being accepted while setting up a blog. is it because google is not yet supported? Please let me know how i can setup a Blogger blog.

**Comment by JetzeMellema** [comment]
Duplicate with #63

**Comment by martinwoodward** [comment]
Yeah - sorry. This is definitely being worked on. Closing as a dupe of #63
