### ISSUE TITLE
Nuget Package Restore

### ISSUE THREAD

**Issue by dneimke** [OpenLiveWriter/OpenLiveWriter#70]
Build.cmd failed due to packages not being restored on my machine.  Not sure why it couldn't find Nuget as a Package source, maybe because it's v3 format in my config?

<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />

Either way, would it be useful to add a Nuget.config to the solution to ensure that the build cannot fail due to local environmental configuration?

**Comment by dneimke** [comment]
refer: https://github.com/OpenLiveWriter/OpenLiveWriter/pull/79

**Comment by willduff** [comment]
This sounds like a duplicate of #59. Can you provide more details on your pull request #79 of why you think that is the right fix?

**Comment by nvella** [comment]
Closing as #79 has been merged.
