### ISSUE TITLE
BuildNuget.cmd fails if no Release build is done

### ISSUE THREAD

**Issue by WouterDeKort** [OpenLiveWriter/OpenLiveWriter#71]
BuildNuget.cmd fails with the error:

Could not find a part of the path '...GitHub\OpenLiveWriter\src\managed\bin\Release\i386\Writer'.

After doing a Release build with build.cmd, BuildNuget.cmd succeeds. The script should check if the folder exists and give an error that you should run a Release build first. Would be nice if it said that build.cmd defaults to Debug and you need to set OLW_CONFIG=Release before being able to run BuildNuget.cmd

**Comment by ScottIsAFool** [comment]
This script is only basic support, it will be getting properly fixed up soon. This is just so we can build a nuget package quickly.
