### ISSUE TITLE
Manipulating tables

### ISSUE THREAD

**Issue by crpaiva** [OpenLiveWriter/OpenLiveWriter#715]
Before we had the ability to drag the rows of the tables using the mouse. Today it is necessary to define its dimensions in the properties and the width of each cell, direct in the code.
I really miss this feature. Does anyone have the same demand as me?

![image](https://user-images.githubusercontent.com/16322079/35406409-f609ca78-01ef-11e8-9c01-3739d5fab888.png)

**Comment by razarahil** [comment]
Yes, I agree. Before it was very easy to manage tables but now the entire table section become very complicated. Also in the previous version, Pressing Tab button able to create new row but now it's no longer working.

**Comment by crpaiva** [comment]
I do not understand how such an important issue does not mess with the OLW user community. Creating, altering, deleting rows or columns has become hell. In the early versions of OLW the context menu worked with all possible options, the TAB key created new rows, the mouse dragged the column and row divisions. Now we need to modify directly in the source code (HTML). Please friends. Let's take this subject to the top.

**Comment by nvella** [comment]
Should be fixed as of PR #830. Table columns can be resized again by mouse, as well as cell, column and row selection.
