### ISSUE TITLE
can't set up new Blogger blog

### ISSUE THREAD

**Issue by ibonobo** [OpenLiveWriter/OpenLiveWriter#719]
I have set up a few of my Blogger blogs with OLW in the past. Today I tried setting up a new one and though I tried with both Edge and Chrome, couldn't do it.

I choose Blogger, the Edge browser window opens up, I authorize OLW with my Google account (which I've done before on each occasion), but when I get kicked back to OLW, I don't get to choose the Blogger blog among the few I have. Instead, I get a '500' error.
![bloggererror](https://user-images.githubusercontent.com/679170/36325587-494b9058-1326-11e8-98d2-5db366d2a8b1.JPG)

Pressing OK in the error window takes me to the add new account window: 
![olw_2ndwindow](https://user-images.githubusercontent.com/679170/36325643-79df3800-1326-11e8-9e01-34cfa6d404ae.JPG)

Pressing next seems to work, as it's "analyzing":
![olw_2bwindow](https://user-images.githubusercontent.com/679170/36325819-fe2f21ec-1326-11e8-95ad-ce1d202366bf.JPG)

..but it ends by bringing about the previous error message window: 

![olw_3rdwindow](https://user-images.githubusercontent.com/679170/36325704-a69886da-1326-11e8-9e77-bbecb694cf0b.JPG)

As such, I cannot add a Blogger Blog any more.

**Comment by toobob** [comment]
same problem trying to install olw on new pc. please fix ASAP High Priority

**Comment by ibonobo** [comment]
I no longer have this problem, however, I have found another one.
