### ISSUE TITLE
Backend Error [500] Can't Add New Google Blogger Blog

### ISSUE THREAD

**Issue by toobob** [OpenLiveWriter/OpenLiveWriter#724]
HIGH PRIORITY
for over a month now, OLW is unable to add a new Google Blogger blog. please someone fix this ASAP

![1](https://user-images.githubusercontent.com/16415096/37542447-1e8dca2a-2956-11e8-80ef-557d256e85f6.JPG)

![2a](https://user-images.githubusercontent.com/16415096/37542464-308dcf68-2956-11e8-84f9-5b12dba1a3dd.png)

![3a](https://user-images.githubusercontent.com/16415096/37542471-39d3c8b6-2956-11e8-9f6e-7f5537fc5ade.png)

![3](https://user-images.githubusercontent.com/16415096/37542475-3e159300-2956-11e8-96b6-2fde1782e16f.JPG)

![4a](https://user-images.githubusercontent.com/16415096/37542480-426a24fc-2956-11e8-8cbd-80fe8cfacdaa.png)

![4](https://user-images.githubusercontent.com/16415096/37542484-45a594bc-2956-11e8-9228-301245ae4015.JPG)

**Comment by nvella** [comment]
Hi there,

There seems to have been some patches made to the Blogger client which have fixed this issue in the year since it was lodged, so I'll close this issue for now. If this issue still persists for you, feel free to get back in touch 👍 Cheers
