### ISSUE TITLE
UnauthorizedAccessException while creating blog posts

### ISSUE THREAD

**Issue by niranjankala** [OpenLiveWriter/OpenLiveWriter#742]
Recently I have tried to create a blog post but failed due below issues:

When i try to create a post then it saying that you do not have permission to access the file even i have removed read only attribute manually. Below is the stack trace:

> System.UnauthorizedAccessException: Access to the path 'C:\Users\acer\Documents\My Weblog Posts\Drafts\test.wpost' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    at System.IO.File.Open(String path, FileMode mode, FileAccess access)
>    at OpenLiveWriter.CoreServices.TempFileManager.CreateNewFile(String dir, String pattern, Boolean asDir) in D:\DevWorkSpaces\GitHub\OpenLiveWriter\src\managed\OpenLiveWriter.CoreServices\TempFileManager.cs:line 260
>    at OpenLiveWriter.CoreServices.PathHelper.GetNonConflictingPath(String path) in D:\DevWorkSpaces\GitHub\OpenLiveWriter\src\managed\OpenLiveWriter.CoreServices\PathHelper.cs:line 178
>    at OpenLiveWriter.PostEditor.PostEditorFile.GetUniqueFileName(String targetFilePath) in D:\DevWorkSpaces\GitHub\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostEditorFile.cs:line 680
>    at OpenLiveWriter.PostEditor.PostEditorFile.ManagePostFilePath(Boolean isPage, String postTitle) in D:\DevWorkSpaces\GitHub\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostEditorFile.cs:line 643
>    at OpenLiveWriter.PostEditor.PostEditorFile.SaveBlogPost(IBlogPostEditingContext editingContext) in D:\DevWorkSpaces\GitHub\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\PostEditorFile.cs:line 453
>    at OpenLiveWriter.PostEditor.BlogPostEditingManager.SaveToDrafts() in D:\DevWorkSpaces\GitHub\OpenLiveWriter\src\managed\OpenLiveWriter.PostEditor\BlogPostEditingManager.cs:line 867

Strange behavior is that when i have installed OLW from windows market space the it is working fine.

**Comment by bpowellzebra** [comment]
I got a similar error, and it was caused by my (somewhat aggressive) antivirus software, that blocked access to OLW when trying to write to my Documents folder.  By granting access in the antivirus software to trust OLW, the problem went away.

**Comment by bpowellzebra** [comment]
I should add that I think part of the problem that antivirus systems have with OLW is that the main executable is stored in %AppData%, as opposed to %ProgramFiles%.

**Comment by bremhillbob** [comment]
I have the same problem and have tried disabling the antivirus (BitDefender) but no luck, error remains.
Did anyone get any further with this?

**Comment by bremhillbob** [comment]
I have used Windows Explorer to go to
D:\Users\Bob Local\Documents\My Weblog Posts\Drafts\
and manually created a file called
zxc zxc.wpost
That worked no problem but it made no difference to the error

**Comment by niranjankala** [comment]
@bpowellzebra You were right. BitDefender blocking the system folders to be modified by any application so i have granted permission to write in them and work for me. Added OpenLiveWrite exe to trusted apps also..

Hope this help others also.

Thanks..

**Comment by bremhillbob** [comment]
I did try to disable Bitdefender and that made no difference so I discounted this.  Once I added openLiveWriter to the trusted apps however everything worked perfectly so your advice has been spot on and I wouldn't have found it without you.  Thanks a lot, really appreciated.  I'll be using this a lot and will be showing several other people so this will have quite an impact locally.
