### ISSUE TITLE
Unable to publish on Windows 10 - After Reset Network Adapters

### ISSUE THREAD

**Issue by dnershi** [OpenLiveWriter/OpenLiveWriter#757]
After a couple days of being unable to connect to browsers other than MS Edge, I solved the issue by doing a reset of the network adapters. Now, I am unable to publish my blog post.

There is no error message, rather the publish icon, with the flying files, comes on and then disappears more quickly than usual.

Any help would be appreciated.

Dave

**Comment by comstech23** [comment]
Yes, same thing happens to me. Though I was able to post just with text. Once I added pictures, it wouldn't publish. It doesn't give you an error message. It just fails to post. I opened and issue as well, thinking it was the images to blame.

**Comment by dnershi** [comment]
Yes. I tried a test post with no pictures and it did publish. Perhaps it is the images...

**Comment by dnershi** [comment]
Closing this thread. It is the same as 759. More comments there.
