### ISSUE TITLE
OLW won't post with pictures 

### ISSUE THREAD

**Issue by comstech23** [OpenLiveWriter/OpenLiveWriter#759]
Hello, OLW was working great last week and just today it's not posting when you add pictures to the post again. Is this issue happening to anyone else? 

There is no error message - it simply doesn't post or upload. It just tries to go through the upload motion and stops. 
thanks!

**Comment by CCOSTAN** [comment]
This is happening to me as well.  Has been working without issue this morning as well (8/13 @ 1pm EST) and now seems to be failing.  No error message either.  Nothing I can see in the logs either.  Works fine with blog posts without pictures.  This is a Blogger blog.  I did see something in the release notes of 0.62 that was suppose to address something related to pictures?  But even after upgrading.. no dice.

**Comment by CCOSTAN** [comment]
Here is the log file from a failed upload if it helps.. 

https://hastebin.com/emirugimay.css

**Comment by farsideoffifty** [comment]
OLW will not publish with a photo.   Yesterday it worked just fine, today it won't publish it just saves a draft.   I opened another photo album in Picassa just in case an album was full and that did not help.

**Comment by dnershi** [comment]
I also have this same issue with posting to Blogger. Don't want to have to revert to the primitive Blogger interface!

**Comment by farsideoffifty** [comment]
It seems to have repaired itself, I just published a post with photos.  Thanks

**Comment by comstech23** [comment]
Yes!!! It's working for me now, too! :)

**Comment by dnershi** [comment]
I'm good as well! Case closed...
