### ISSUE TITLE
Back Up Blog Account?

### ISSUE THREAD

**Issue by villa1** [OpenLiveWriter/OpenLiveWriter#762]
i have let say 10 blog account saved in open live writer (my desktop )
is it possible to back up this account in case computer being reinstalled or use this account in another computer (My laptop )

**Comment by survivor303** [comment]
With blogger you still need to sign in, even you backup your appdata OLW folders, and that isnt so big deal if your blogs are in the same account on wordpress or blogger, just let the OLW do its thing, while importing the blog data to the application.

Your OLW articles are save on your document folder and you can backup that and use them on a new installation, they dosnt show up on your recent list anymore but they open to OLW when select and click them, so you can update articles with them. If you dosnt like use these local files, OLW can find your posts directly from the blog server, even drafts can be find there if you are saved them to server before. They found at: "File - > Open recent draft/post" and there is option list where OLW trying to find these.

**Comment by nvella** [comment]
Hi @villa1,

Open Live Writer's configuration is mainly stored in the registry under key `HKEY_CURRENT_USER\Software\OpenLiveWriter`, with some authentication tokens and other config stored in files under `%AppData%\OpenLiveWriter`. You can back-up Open Live Writer's configuration by backing up the registry key and folder, but admittedly this isn't quite a user-friendly solution.

I'll close this issue for now, but if you would like to see this implemented as a proper feature please don't hesitate to let us know; I'll open the issue back up and mark it as a feature request 👍 Cheers
