### ISSUE TITLE
IS THIS CODE STILL BEING UPDATED????

### ISSUE THREAD

**Issue by spoiledtechie** [OpenLiveWriter/OpenLiveWriter#780]
There are many PRs still open and what not.  So is the repo still open or are we ready to hand it off to someone else to monitor it?

**Comment by martingbrown** [comment]
Relates to #743

**Comment by martingbrown** [comment]
It's the first anniversary of the last commit today.

**Comment by jaypatrick** [comment]
Long live Windows Live Writer! Sad to see this hasn't been updated in a while. I've pulled the code and will start poking around, but it won't even build. Was excited when @jongalloway got this project off the ground, hope it's not dead!

**Comment by martingbrown** [comment]
I did a pull request for VS 2017. It builds fine from the command line and appveyor, and all but the packageing step work in VS. Someone in the past really went to town hand editing the csproj files. Makes getting it working with VS a bit tricky.

**Comment by jongalloway** [comment]
I merged the pull request for VS 2017 and am reviewing some others this weekend to include in a fix release for Blogger. We have been looking at doing a release for .NET Core 3, but that's still months away.
