### ISSUE TITLE
New window auto-opens every 10 seconds

### ISSUE THREAD

**Issue by taoduh** [OpenLiveWriter/OpenLiveWriter#798]
Open live writer opens a new untitled post every 10 seconds.  Windows 10, build 0.6.3.0.  I can't find a way to stop it.

**Comment by softwareengel** [comment]
I have the same problem.

**Comment by nvella** [comment]
High priority- issue is present in development builds and prevents testers from efficiently testing the application. Is probably related to the installer.

**Comment by nvella** [comment]
Fixed by #847.
