### ISSUE TITLE
Release Open Live Writer on GitHub

### ISSUE THREAD

**Issue by martinwoodward** [OpenLiveWriter/OpenLiveWriter#8]
Capturing the things we want to do as part of the release. Feel free to edit as necessary

- [x] Make this repo public
- [x] Rename testpage2.html to index.html
- [x] @shanselman publish blog post
- [x] @martinwoodward public the .NET Foundation guest post from @RobDolin
- [x] Post to the twitterverse 
- [x] Send a PR to https://github.com/dotnet/home adding Open Live Writer

**Comment by RobDolinMS** [comment]
@martinwoodward  are you taking care of the last checkbox here?

**Comment by colbyrussell** [comment]
> @martinwoodward are you taking care of the last checkbox here?

See https://github.com/dotnet/home/pull/32

**Comment by martinwoodward** [comment]
Done the last bit - http://www.dotnetfoundation.org/open-live-writer

Congratulations everyone!
