### ISSUE TITLE
Blog Issue

### ISSUE THREAD

**Issue by rontfox** [OpenLiveWriter/OpenLiveWriter#801]
I can no longer transfer photos from Live Writer to my blog dashboard.  I now get an error message. I've had no problems in the past.

**Comment by CCOSTAN** [comment]
Seems to be Duplicate of issue #786

**Comment by nvella** [comment]
Closing as a duplicate of #786 and fixed in #810. Please don't hesitate to get in touch if you have any further issues.

Regards, Nick.
