### ISSUE TITLE
Errors posting in my WP blog

### ISSUE THREAD

**Issue by akoppa** [OpenLiveWriter/OpenLiveWriter#804]
I'm experiencing problems with new posts in my WP blog. The following errors occur after trying to post using OLW or WLR.
I get errors as follows:

> www.example.com
> is protected by Imunify360
> We have noticed an unusual activity from your IP xxx.xxx.xxx.xxx and blocked access to this website.
> Please confirm that you are not a robot 

If I try to connect to cPanel using Firefox sometimes I get this error:

> The owner of xxx.xxx.com (server) has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

If I try to connect to cPanel using Opera sometimes I get this error:

> Invalid Certificate

OR

> Invalid Server response - The response to the blogger.getUsersBlogs method received from the blog server was invalid:
> Invalid response document returned from XmlRpc server
> Error 404 Page not found

OR

> An unexpected error ocurred while attempting to log in:
> Blog Post Address not found - The post web address for the blog was not found:
> https://www.example.com/blog/xmlrpc.php
> The remote server returned an error: (404) Not Found.

The link is okay and respond normally from my browser.

Immunify360 that was included recently in my cPanel along with modSecurity. The only way I could post with either OLW or WLR is dissabling the modSecurity.

Any help will be appreciated.

**Comment by nvella** [comment]
Hi @akoppa,

This seems to be a configuration issue with your hosting provider. I would recommend getting in touch with them regarding your issue; it seems to be related to your SSL certificates and the security software your hosting provider uses. Please don't hesitate to reply if you have any questions.

Regards, Nick

**Comment by akoppa** [comment]
ModSecurity has blocked access to xmlrpc.php. There are several cures but so far neither one seems to be effective. The best approach is to allow access by IP but I do not use a static IP address. Temporarily I have created a shortcut in my desktop in order to disable ModSecurity before posting.
