### ISSUE TITLE
Feature Request: Picture / Insert from Clipboard

### ISSUE THREAD

**Issue by aheil** [OpenLiveWriter/OpenLiveWriter#806]
It would be a major increase in usability if you could insert images directly from the clipboard into a blog post. 

Currently, you have to save the image to disk insert it from the file afterward.

**Comment by nvella** [comment]
For anyone wishing to make a start on this, I'd start by looking into finding the method that executes on a Paste command, and implementing logic to handle image content types. Images from the clipboard could be saved to a temp folder and then the path passed into the existing image insertion logic, or a more efficient integration can be sought.

**Comment by nvella** [comment]
Seems to be related to #779. Maybe there is image pasting support but it's currently broken?

**Comment by CCOSTAN** [comment]
I paste into OLW all the time. Never have an issue.

**Comment by nvella** [comment]
I checked then and pasting does seem to be working from regular Win32 apps such as Paint, but not UWP apps like Snip and Sketch. I'll close this issue for now as technically the feature is 'implemented', just not fully working. The UWP image pasting will be tracked in #779.
