### ISSUE TITLE
Authentication issues with blogger?

### ISSUE THREAD

**Issue by lokijota** [OpenLiveWriter/OpenLiveWriter#81]
Today I tried to post something with the original WLW and had the infamous NotFound: Not Found error, associated with auth problems (note: the password was stored, I don't insert it manually)

Downloaded and installed OLW, and I'm having the same issues: "The username or password is incorrect. Please try again." I went to the site, and authenticated with that same u/p with no problems. Generated a new app password on google, and still didn't work. Any ideas? is this some change on google's part?

PS: I did a post earlier today with success...

**Comment by ibonobo** [comment]
Had the same issue. I suspect Google may have pulled the plug on the old auth method.

**Comment by gerhardbock** [comment]
Same issue with both WLW and OLW.

**Comment by timheuer** [comment]
Duplicate core issue which will be resolved by #5
