### ISSUE TITLE
ClickOnce deploy?

### ISSUE THREAD

**Issue by bsimser** [OpenLiveWriter/OpenLiveWriter#82]
Any thoughts around a clickonce deploy (like github for windows) to get rid of the installer. These days apps don't really need an installer. There are some issues looking at using %AppData%/OpenLiveWriter as a root folder for configuration, posts, plugins, etc. Would be nice to always have the latest version just by launching it.

**Comment by timheuer** [comment]
The current infra auto updates for you. We have an 'evergreen' installer and you do have the latest each time you launch :-)

**Comment by bsimser** [comment]
Duh. Okay, ignore this. Too much eggnog.
