### ISSUE TITLE
Shortcut key for Show in Open dialog sets wrong focus

### ISSUE THREAD

**Issue by breyed** [OpenLiveWriter/OpenLiveWriter#820]
1. Press Ctrl+O to open the Open dialog.
2. Press Alt+S.
* Notice that Cancel gets focus. Instead, the item count box should get focus.

**Comment by nvella** [comment]
Sure @ranjanjharavi 😃

**Comment by ranjanjharavi** [comment]
Thank you 😄 @nvella,
I tried this issue and was able to get focus on the item count box. Please review the PR.

**Comment by nvella** [comment]
Fixed via #873
