### ISSUE TITLE
Make Categories drop-down for Page look & work as for Posts

### ISSUE THREAD

**Issue by tester0077** [OpenLiveWriter/OpenLiveWriter#828]
When I try to generate a new 'page' the categories drop-down (page parent) is way too narrow and disaorganized to be useful.
Is it possible to 'fix' this
TIA

**Comment by nvella** [comment]
Hi @tester0077,

Can you provide a screenshot of the fault? It would be very appreciated 😃

**Comment by tester0077** [comment]
See the attached images;
Open OLW -> file menu -> new post ->
![OpenLiveWriter-NewPage](https://user-images.githubusercontent.com/9053628/60187540-99306700-97e2-11e9-87cc-b8537214c8fd.jpg)
![OpenLiveWriter-NewPage2](https://user-images.githubusercontent.com/9053628/60187708-e14f8980-97e2-11e9-8dce-a77365727ed8.jpg)

 new page

**Comment by nvella** [comment]
Fixed in #833

![image](https://user-images.githubusercontent.com/8158648/60392089-beeda100-9b3f-11e9-8bda-74852d40b398.png)
