### ISSUE TITLE
Enhance splash screen

### ISSUE THREAD

**Issue by nvella** [OpenLiveWriter/OpenLiveWriter#846]
The splash screen is the first thing the user sees when they launch Open Live Writer, and does a lot in forming a user's first impressions of the software. The current splash screen feels outdated and suffers from DPI scaling problems, among other issues.

I've been thinking that it might be a good idea for the splash screen to be redesigned. One idea I've had is a splash much alike the Office 2019 splashes.

![image](https://user-images.githubusercontent.com/8158648/62595900-85b90580-b923-11e9-9ade-b80adae152fa.png)

The Microsoft logo would be substituted with a slimline .NET Foundation logo, and the background colour changed to match Open Live Writer's brand. It should be simple to implement a sliding title text animation using timers and altering a Label control's position and opacity.

If you have any ideas for a splash screen, feel free to leave them below 👍

**Comment by gep13** [comment]
@nvella this seems like a great idea to me!  I am assuming that you will be keeping the same existing colours, i.e. to match the icon:

![image](https://user-images.githubusercontent.com/1271146/62601418-39e96a80-b8e9-11e9-8b07-e485ff00f78c.png)

Or are you planning on changing that as well?

**Comment by nvella** [comment]
I'm planning on sticking with the same colours and icons 👍
