### ISSUE TITLE
Faults with Video 'Insert from Web' and YouTube

### ISSUE THREAD

**Issue by nvella** [OpenLiveWriter/OpenLiveWriter#849]
I've looked at the other issues and whilst this bug does get mentioned, nothing singles it out exactly. Creating a separate issue so it's more easily identifiable.

Two issues are currently present with YouTube videos and Video -> 'Insert from Web'

- The form does not recognise `https`, or `youtu.be` URLs.
- Changing the UR to a `http` URL results in the old Flash player being added, which is no longer functional.

The intended behavior is for `https` and `youtu.be` URLs to work in the form, and for the newer HTML5 player to be inserted, rather than the older Flash player.

**Comment by ranjanjharavi** [comment]
Hi May I pick this issue. @nvella

**Comment by nvella** [comment]
Sure Ravi 👍 Feel free to ask any questions if you need help

**Comment by ranjanjharavi** [comment]
Thank you, Nick. :) 
I tried this issue and was able to get the preview of the YouTube URLs containing https and youtu.be. 
But, while publishing the post to WordPress account I was getting one exception _ProgId missing for extension:: wpost_ and still was able to post after ignoring. 
Is this problem related to build or something?
Also using VS2015 I was getting lots of errors during the build but not in VS2017 which I use in general.
@nvella Should I give PR of the [branch](https://github.com/ranjanjharavi/OpenLiveWriter/tree/fix-849-Insert-From-Web-YoutubeURL) to get reviewed?

**Comment by nvella** [comment]
Hi @ranjanjharavi,

Looks like good work so far! Certainly submit a PR and I can give it a look.

The ProgId and extension wpost errors are a known issue to-do with file associations - I'm intending to give that a look as part of my work on MSIX packaging as MSIX supposedly handles setting up associations.

As for the Visual Studio version, I've been developing on 2017, however @wforney is working on moving the project over to 2019 in #863. Don't worry if you have to change the version on your branch to develop, we can fix it up later :)

Cheers, Nick

**Comment by ranjanjharavi** [comment]
Oh, good to know. Thank you @nvella

**Comment by nvella** [comment]
Fixed by @ranjanjharavi via #871.
