### ISSUE TITLE
Add YamlDotNet copyright to About dialog

### ISSUE THREAD

**Issue by nvella** [OpenLiveWriter/OpenLiveWriter#853]
For static site support, the YamlDotNet library was brought in. Its copyright should be added to the About dialog before release.

**Comment by caiovosilva** [comment]
I would like to work on this.
Where can I find the 'About' file?

**Comment by nvella** [comment]
Hi Caio, exciting to see some interest! The file can be found under ‘src\managed\OpenLiveWriter.PostEditor\AboutForm.cs’. 

YamlDotNet is MIT licensed, so it may be worth following how the other MIT libraries are credited in the dialog, to keep things simple and consistent. 

Cheers 🙂

**Comment by nvella** [comment]
Fixed by #864
