### ISSUE TITLE
Can't post to blogger if the post contains images

### ISSUE THREAD

**Issue by vvvlad** [OpenLiveWriter/OpenLiveWriter#854]
Title describes the issue.
Couldn't publish to blogger until removed all the images from the post.
If needed, can provide any additional information per request.
Have seen some previous issues which may be related talking about Drive permissions, but not sure if the same and how to overcome that.

**Comment by nvella** [comment]
Hi @vvvlad. This is a known issue, and has been fixed in development builds (#810 was the fix). We should have a new release out within the next few days, which will be published to the site as well as the Microsoft Store. Stay tuned!
