### ISSUE TITLE
Bug report: Blogspot upload images from local machine

### ISSUE THREAD

**Issue by CTrigger** [OpenLiveWriter/OpenLiveWriter#866]
Just can't upload as draft, or publish post with local images in the body

**Comment by nvella** [comment]
Hi @CTrigger, thanks for the report! This bug was tracked in #786, and is currently fixed in the development builds via #810. We're currently working on getting a new release out, so hang in there :) I'll close this issue for now, but please don't hesitate to reply if you have any questions. Cheers
