### ISSUE TITLE
Unable to authenticate on Blogspot account

### ISSUE THREAD

**Issue by indiwiz** [OpenLiveWriter/OpenLiveWriter#89]
Downloaded the latest version today morning. Tried to add my blogspot account. Selected "Other Services" on the first step, entered by blog's web address and username/password on the second. Clicked next and keep getting this error... "The user name or password is incorrect". I am on Windows 8.1.

**Comment by pekiZG** [comment]
@indiwiz 
Tnx for your report.
As I understand when https://github.com/OpenLiveWriter/OpenLiveWriter/issues/5 gets resolved Blogspot authentication will start working.

**Comment by martinwoodward** [comment]
Should do - closing as duplicate of #63
