### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by JohnBlood** [OpenLiveWriter/OpenLiveWriter#94]
I used Live Writer for a while (until Microsoft pulled the plug). Now that it is back as an opensource project, I'd like to help, but my knowledge is limited to basic HTML. Is there anything I can do to help?

**Comment by timheuer** [comment]
@JohnBlood the best way to help is to fix bugs and stabilize :-).  The second best way is to find bugs we need to stabilize!  Taking builds and keeping the client up-to-date (which happens automatically) is really helpful for those who don't feel comfortable digging deep into the code.
