### ISSUE TITLE
It is Working for me. try this setup file (Google App Blocked Error Fixed!) :ok_hand:

### ISSUE THREAD

**Issue by StudyToA9** [OpenLiveWriter/OpenLiveWriter#940]
**Answer From #882**

Okay. You're not a pain. I just feel awful the links don't work. Let's try this. This is a link to my Public Dropbox Folder. There is the current version in zip file and in exe file.

**https://www.dropbox.com/sh/uh9getd6zwkcjhy/AABjxsjEjpyi9n-WHRskp-Y1a?dl=0**

Now, here is a link to the page I downloaded it from. Ignore the version number it shows (0.5.1.2 NIGHTLY) in the download link. You will get the most current version when you click on it and it always updates.
https://www.mybloggertricks.com/2015/12/fixing-open-live-writer-errors.html
https://olw.blob.core.windows.net/nightly/Releases/OpenLiveWriterSetup.exe

And here it is in a zip file.
[OpenLiveWriterSetup.zip](https://github.com/OpenLiveWriter/OpenLiveWriter/files/4027251/OpenLiveWriterSetup.zip)

One of these has to work (fingers crossed) Let me know and good luck. This version has been working fine for me with no issues or hiccups at all.

_Originally posted by @PoSmedley in https://github.com/OpenLiveWriter/OpenLiveWriter/issues/882#issuecomment-571229039_

**Comment by lavanyadeepak** [comment]
From which branch was this built @StudyToA9 ?
