### ISSUE TITLE
Does installing OpenLiveWriter in anyway change my existing Live Writer?

### ISSUE THREAD

**Issue by microsmith** [OpenLiveWriter/OpenLiveWriter#95]
After installing OpenLiveWriter and discovering that I cannot currently use it to connect Blogger (issue #5 I guess), I opened my Live Writer, and now it can't connect to Blogger. I uninstalled OpenLiveWriter, but I still can't connect to Blogger with Live Writer. I was able to use Live Writer earlier this week with blogger.

Is this a known issue? If so, how can I get my Live Writer to work with blogger again?

**Comment by NazmusLabs** [comment]
No, it does not.

**Comment by RobDolin** [comment]
Thanks Mike.  Yes, both Windows Live Writer and Open Live Writer not working with Blogger blogs is a known issue.  We're working to fix Open Live Writer (#5)

Sent from my Windows Phone
________________________________

**Comment by microsmith** [comment]
I know that a while back Blogger changed their security and "broke" Live Writer. They reversed that change and it worked for me up through at least five days ago.  Have they changed their security again in the last week?
Any guesses on when #5 will be ready?

Thanks,
Mike

**Comment by timheuer** [comment]
Working on this now @microsmith tracked as #63
